### ISSUE TITLE
Remove clusterMonitoringOperator default metrics via metricsbridge

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1000]
Before sending logs to Geneva I want to send metrics is as clean format as possible. 
Currently Operator adds these metrics to each metrics:
prometheus
prometheus_replica

We want to purge them when converting metrics to Geneva format.

/kind cleanup

**Comment by jim-minter** [comment]
this was done here:
https://github.com/openshift/openshift-azure/pull/1002/files#diff-d171b35ae3e779c2520ce8d35dd58e9aR41
