### ISSUE TITLE
restore process restarts infra and compute nodes

### ISSUE THREAD

**Issue by 0xmichalis** [openshift/openshift-azure#1006]
See https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-etcdbackuprecovery-e2e/35/artifacts/e2e-azure-etcdbackuprecovery/container-logs/test.log.gz or https://github.com/openshift/openshift-azure/pull/999#issuecomment-452695432. I think this is unexpected, infra and compute VMs should be rotated only if there is a different hash in the blob.

@jim-minter @asalkeld 

/kind cleanup
/kind bug

**Comment by kargakis** [comment]
I wonder whether it is possible to restore to an etcd state that is drifting from the config blob (eg. different certificates are stored in etcd secrets from those in the config blob).
