### ISSUE TITLE
openshift router stats endpoints in non TLS

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#101]
currently haproxy exposes metrics in non-tls mode:
openshift/origin#20375

When this solved upstream, fix our code to scrape TLS endpoints.

**Comment by kargakis** [comment]
dupe of https://github.com/jim-minter/azure-helm/issues/25

**Comment by mjudeikis** [comment]
Not quite. We fixed by moving to http.  So scrape works, but upstream need to fix and do it properly via https

**Comment by kargakis** [comment]
Upstream issue?

**Comment by ehashman** [comment]
This won't get fixed in 3.11 and it's gone stale upstream so :woman_shrugging:
