### ISSUE TITLE
Check if CI is building images with binaries marked -dirty

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1024]
We link the git hash into the binaries in the images we publish, and may append `-dirty` if the git repo is not completely clean.

I think our build system:
* has a clean git repo
* builds binary1, linked git hash doesn't have `-dirty`, places binary in root of git repo
* builds image1
* builds binary2, linked git hash has `-dirty` when it shouldn't because of existence of binary1

Please check and if necessary fix

**Comment by jim-minter** [comment]
@kargakis fyi

**Comment by kargakis** [comment]
The binaries should be ignored by git since they are included in `.gitignore`.

**Comment by jim-minter** [comment]
the -dirty check ignores .gitignore.  Maybe that's paranoid and one way to fix this is to change that.

**Comment by kargakis** [comment]
Oh, that's definitely paranoid, the binaries are bind-mounted into a different image which is the final image that we publish in quay.

**Comment by kargakis** [comment]
For clarity, [this](https://github.com/openshift/release/blob/842ddb72ce785450578559efdb74d5157b9aa5f1/ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml#L13-L16) is where the bind-mounting happens (sync image).

**Comment by jim-minter** [comment]
fwiw I think the bind-mounting is after the bit that matters (was the git repo clean at *build* time?)

**Comment by jim-minter** [comment]
@Makdaam can I ask you to look at another thing: the Makefile dependency management that detects when to rebuild a binary when one already exists is broken.  i.e. if sync exists and I do `make sync`, nothing happens.  Worst case (easiest fix): all relevant targets should be marked .PHONY to force a build

**Comment by Makdaam** [comment]
@jim-minter alright

**Comment by kargakis** [comment]
> @Makdaam can I ask you to look at another thing: the Makefile dependency management that detects when to rebuild a binary when one already exists is broken. i.e. if sync exists and I do `make sync`, nothing happens. Worst case (easiest fix): all relevant targets should be marked .PHONY to force a build

Not sure this is correct, go incrementally builds the binary just fine.

**Comment by Makdaam** [comment]
Fixed by #1042, sorry for not updating.
