### ISSUE TITLE
remove reliance on lsof

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1036]
The following bash is horrid in multiple ways:
`trap 'return_id=$?; set +ex; kill $(lsof -t -i :8080); wait $(lsof -t -i :8080); exit $return_id' EXIT`

Replace all instances of it in our codebase as follows.  At the top of every bash script which should remove background spawned processes when it exits, add:
```bash
cleanup() {
    trap '' TERM
    kill 0
    wait
}

trap cleanup EXIT
```

The effect of this should be:
* in any case where the script is about to quit (normal exit, signal) call `cleanup()`
* in cleanup, set our script's SIGTERM handler to SIG_IGN
* send a SIGTERM to all processes in our process group (we'll ignore ours due to the previous line)
* wait for known child processes to exit

Also, this upgrades an incoming SIGINT to an outgoing SIGTERM, this handles the fact that by default bash presets background processes to ignore SIGINTs.

@kargakis @charlesakalugwu are you OK with the above?

**Comment by charlesakalugwu** [comment]
i just tested this out locally and it works. So sgtm

**Comment by charlesakalugwu** [comment]
unfortunately the fakerp server is still being leaked after @jim-minter's fix

**Comment by kargakis** [comment]
> unfortunately the fakerp server is still being leaked after @jim-minter's fix

Still? Was it an issue before? Pretty sure it wasn't leaked in the happy path.
