### ISSUE TITLE
Refactor util.Template & translate.go

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1054]
I want to refactor translate.go and util.Template so I use more complex translations, like xml, json, list and be able to use them easier in our code base. 

This needed for https://github.com/openshift/openshift-azure/pull/1030/files

/kind cleanup 
/kind feature

**Comment by ehashman** [comment]
I think this was covered by the azsecpack work, please reopen if that doesn't sufficiently address this issue.
