### ISSUE TITLE
Seperate Provisioning State for Admin Operations

### ISSUE THREAD

**Issue by shrutir25** [openshift/openshift-azure#1058]
We will need a seperate provisioning state for admin put operations such as `AdminUpdating` here https://github.com/openshift/openshift-azure/blob/master/pkg/api/types.go#L67.

This will allow us as engineers to look up clusters logs and distinguish between a regular update operation and an admin update operation. Also it will be used to block a regular put operation when an admin update operation is ongoing.

**Comment by shrutir25** [comment]
@mjudeikis Could you take a look at this ?

**Comment by mjudeikis** [comment]
/kind feature
@openshift/sig-azure needs an owner.

**Comment by charlesakalugwu** [comment]
@shrutir25 i'll have a look at this

/assign

**Comment by jim-minter** [comment]
ah, I see, #1079 already open :-)
