### ISSUE TITLE
ResourceGroupNotFound in fakeRP flake in multiple tests

### ISSUE THREAD

**Issue by Makdaam** [openshift/openshift-azure#1077]
`Original Error: autorest/azure: Service returned an error. Status=404 Code=\\\"ResourceGroupNotFound\\\" Message=\\\"Resource group 'e2e-sntcnqgh' could not be found.\\\"\\n\" error: json: cannot unmarshal number into Go value of type azure.RequestError"`

When running the test by docker run, the resource group is created but sometimes vnet creation or VMSS creation fails with 404 ResourceGroupNotFound. Possibly RG creation is not synchronous.

Looking into this.

**Comment by Makdaam** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1076/pull-ci-openshift-openshift-azure-master-e2e-azure/2115

**Comment by mjudeikis** [comment]
@Makdaam can it be it was quota issue? still relevant?

**Comment by jim-minter** [comment]
haven't seen recently, reopen if needed

**Comment by ehashman** [comment]
Seen this twice now on #2031:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2031/pull-ci-azure-master-upgrade-v10.1.1/63/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2031/pull-ci-azure-master-e2e-create-20190430/63/build-log.txt
