### ISSUE TITLE
Add unit test to check updates to azure sdk versions

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1103]
As a follow-up to #1096 we need to create a unit test that checks that the versions of the various azure service sdks imported in `pkg/arm/resources.go` match those specified in the `fixupAPIVersions(map[string]interface{})` function 

The function can be found at https://github.com/openshift/openshift-azure/blob/7f1b2807449498ab2868658bd6a83b942bc2d0e9/pkg/arm/resources.go#L51

/kind feature
/area tests

**Comment by jim-minter** [comment]
the intention here is to write a unit test which validates this comment:
https://github.com/openshift/openshift-azure/blob/fea61953a5ac591337a1f0c2fcaf4881fb66e0b2/pkg/arm/v8/resources.go#L19-L20
