### ISSUE TITLE
scrape etcd metrics

### ISSUE THREAD

**Issue by Makdaam** [openshift/openshift-azure#1104]
Etcd metrics in cluster prometheus are either missing or have 0 values.
Invetigate why and fix.
root@master-000000# curl --cacert ca.crt --cert ./peer.crt --key peer.key https://master-000000:2379/metrics
returns all expected metrics with non-zero values where appropriate.

**Comment by mjudeikis** [comment]
Does Prometheus config has etcd endpoints configured? we have slightly modified etcd config, so this might be a case

**Comment by Makdaam** [comment]
CMO has the features. I'll have to configure the certs and the /metrics endpoint in etcd + add some yaml

**Comment by Makdaam** [comment]
Forgot about
/assign @Makdaam

**Comment by jim-minter** [comment]
closing for AZURE-294
