### ISSUE TITLE
[Testing] testing requirements 

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#112]
For full CI/CD we will need to enhance our testing and image resolve capabilities.

We have a few types of `OKD` related testing.
1. Images build part of the core origin repo (all in the control-plain)
2. Images built from individual repositories (all in addons/plugins part)

1. Any commits to `origin` repo will need to get job triggered and ONLY control plain images overwritten (list https://github.com/openshift/release/blob/master/ci-operator/config/openshift/origin/master.json)
This means for our subset these images [1] will have to point to `oreg_url:=testregistry/example/ci-pr-as-${component}-${version}`
and all other images have to point to either upstream registry (`registry.redhat.io` for GA builds test and `aws-reg` for pre-ga builds.

[1]:
```
c.ControlPlaneImage = image(c.ImageConfigFormat, "control-plane", v)
c.NodeImage = image(c.ImageConfigFormat, "node", v)
c.RouterImage = image(c.ImageConfigFormat, "haproxy-router", v)
```

This implies for images like [2] we will need to overwrite to dynamic registry variable (either GA or pre-aws). *I suggest to add back `DEV_REGISTRY` variable and for `3.11` all other images are pointed to this one. for GA - they point to `registry.redhat.io`

[2]:
```
c.ServiceCatalogImage = image(c.ImageConfigFormat, "service-catalog", v)
c.AnsibleServiceBrokerImage = image(c.ImageConfigFormat, "ansible-service-broker", v)
c.TemplateServiceBrokerImage = image(c.ImageConfigFormat, "template-service-broker", v)
c.RegistryImage = image(c.ImageConfigFormat, "docker-registry", v)
```

The second set of jobs have to point to individual repositories for images like [3] and test them in our future E2E test by:
1. Installing either GA or Pre-GA stable release cluster.
2. Inject new images we need to test into sync plugin config and overwrite individual image we want to test.
3. Profit. 

[3]
```
c.OAuthProxyImage = "registry.access.redhat.com/openshift3/oauth-proxy:" + v
c.PrometheusImage = "registry.access.redhat.com/openshift3/prometheus:" + v
c.PrometheusAlertBufferImage = "registry.access.redhat.com/openshift3/prometheus-alert-buffer:" + v
c.PrometheusAlertManagerImage = "registry.access.redhat.com/openshift3/prometheus-alertmanager:" + v
c.PrometheusNodeExporterImage = "registry.access.redhat.com/openshift3/prometheus-node-exporter:" + v
```

For for the first step in next few weeks (post GA) we need to rearrange 
https://github.com/openshift/openshift-azure/blob/master/pkg/config/generate.go#L87-L90 
to be split for core images and individual images and introduce `DEV_REGISTRY` variable to the equation. 
Second individual `ci-operator` jobs need to be created.
Third e2e tests suit entry point created for:
1. Run unit tests
2. Create cluster
3. Run integration tests
4. Run smoke tests
5. Any other tests ?

cc: @openshift/sig-azure  for discussion ?

**Comment by mjudeikis** [comment]
This is situation now : 
```
default                             docker-registry-77b7bd6ddf-9b2bx          1/1       Running            0          8m                                                                                                                                                                  
default                             registry-console-7cb95796-2629f           0/1       ImagePullBackOff   0          8m                                                                                                                                                                  
default                             router-6dfcd456b9-rtw5d                   1/1       Running            0          8m
kube-service-catalog                apiserver-7694bfc778-kf97m                1/1       Running            0          8m
kube-service-catalog                controller-manager-7d86c997dd-95tcf       1/1       Running            0          8m
kube-system                         api-master-000000                         1/1       Running            0          8m
kube-system                         api-master-000001                         1/1       Running            0          8m
kube-system                         api-master-000002                         1/1       Running            0          8m
kube-system                         controllers-master-000000                 1/1       Running            0          8m
kube-system                         controllers-master-000001                 1/1       Running            0          8m
kube-system                         controllers-master-000002                 1/1       Running            0          8m
kube-system                         etcd-master-000000                        1/1       Running            0          8m
kube-system                         etcd-master-000001                        1/1       Running            0          8m
kube-system                         etcd-master-000002                        1/1       Running            0          8m
openshift-ansible-service-broker    asb-6874686f68-8q69b                      1/1       Running            0          8m
openshift-azure                     bootstrap-autoapprover-5c674446f7-jmrrb   1/1       Running            0          8m
openshift-metrics                   prometheus-0                              0/6       ImagePullBackOff   0          7m
openshift-metrics                   prometheus-node-exporter-9vb6t            0/1       ImagePullBackOff   0          8m
openshift-metrics                   prometheus-node-exporter-br7jr            0/1       ImagePullBackOff   0          8m
openshift-metrics                   prometheus-node-exporter-j4w2s            0/1       ImagePullBackOff   0          7m
openshift-metrics                   prometheus-node-exporter-r9f4g            0/1       ImagePullBackOff   0          8m
openshift-metrics                   prometheus-node-exporter-s7nnn            0/1       ErrImagePull       0          7m
```

Core images with oreg_url (from aws registry are fine) but any other ones need "other home"

**Comment by kargakis** [comment]
> Images built from individual repositories (all in addons/plugins part)

Not all, eg. the router and the SDN plugin are still part of origin.

> Core images with oreg_url (from aws registry are fine) but any other ones need "other home"

We don't need to fix configuring PR-built images for all images that are not part of origin now. We should get to it once we add tests in those repos (post PP). For now, oreg_url should apply only on origin images when the pre-release registry is used.

**Comment by mjudeikis** [comment]
@kargaki, agree Router and SDN being part of origin just makes things easier. And for the second point, I just wanted to capture requirement. I really would not want to do this before PP

**Comment by kargakis** [comment]
Not an openshift-azure issue, I would suggest bringing this up in an arch call if more discussion is warranted.

/close
