### ISSUE TITLE
Use of ProvisioningState in fakeRP

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1120]
We should tide-up how we use field `ProvisioningState` in our fakeRP code. 
Each test, action, function should cycle from a `healthy` state to `in progress` and back to `healthy`.
This would make any of these methods to be able to run in async mode. 

Currently, some test there populating state and leaving it hanging with the wrong status. This caused tests running after it to behave not as expected. 

Related:
https://github.com/openshift/openshift-azure/pull/1119
https://github.com/openshift/openshift-azure/issues/1118

**Comment by ehashman** [comment]
Is this still applicable @mjudeikis ?
