### ISSUE TITLE
retry code function - fakeRP utils

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1122]
MSFT are retrying code in multiple places, based on error codes. We need something similar in our fakeRP.  This should be aligned with MSFT code, so they could reuse our error codes, or return results and wrap our plugin code functions with their side "retry functions"/ 

MSFT comment:
``` 
generally, we have a retry function that takes two functions. One outputs err, the other accepts the error and decides if it an error that should be retried
```
If we built something under these lines MSFT could reuse this on their end too. 

We should retry anything that goes "over the internet" in our code. Like kube api calls, arm calls, etc.

**Comment by jim-minter** [comment]
A slightly different take on a similar issue (@charlesakalugwu fyi): if a fake RP admin function returns a 500, the client will automatically retry it, which I don't think is a great plan.  An example code path is RotateSecretsAndWait -> RotateSecrets -> RotateSecretsSender -> DoRetryWithRegistration -> DoRetryForStatusCodes.
An example case of this happening is https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1205/pull-ci-openshift-openshift-azure-release-v2-e2e-azure-keyrotation/22

**Comment by jim-minter** [comment]
should retry InternalExecutionError on scaleset update (#1297)
