### ISSUE TITLE
Scale Up/Down rotates all VMs

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1127]
The scale up/down e2e tests have been failing in CI since 1st February 2019: https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/periodic-ci-azure-scaleupdown-e2e/

It appears that from this day, `CreateOrUpdate`  on the non-admin `OpenshiftManagedClustersClient`, with a manifest whose only update is the count of compute instances, sends a request which results in all VMs being updated/rotated instead of scaling up/down only the compute scale set.

This results in the test taking longer than it should and it effectively gets timed-out after the configured timeout of 30 minutes.

I am not yet sure if this is a problem on the MSFT RP side or on our side.

sample artifacts: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1092/pull-ci-openshift-openshift-azure-release-v1-e2e-azure-scaleupdown/2/

/cc @mjudeikis @kwoodson @julienstroheker @sozercan 
/kind bug

**Comment by kwoodson** [comment]
After taking @jim-minter's advice and dumping the hash during cluster creation and then also dumping it during the `make e2e-scaleupdown` it appears that properties inside of 
`properties.virtualMachineProfile.extensionProfile.extensions[0].properties.protectedSettings.script` are changing.

Looking further into this.

**Comment by kwoodson** [comment]
It appears that gzip includes the script name and the date which differs on each run and in turn causes the file to be different each time.
```
[root@master-000002 ~]# gzip  script.1.sh script.sh 
[root@master-000002 ~]# ll
total 248
-r-x------. 1 root root 123960 Feb 12 23:14 script.1.sh.gz
-r-x------. 1 root root 123958 Feb 12 23:10 script.sh.gz
[root@master-000002 ~]# md5sum script.1.sh.gz script.sh.gz 
d6dad4513977e6654c9e613b51a8d45c  script.1.sh.gz
209253fbdd03f83b6a68886a8f7fa48f  script.sh.gz
```

With the `--no-name` option removes name and time stamp:
```
[root@master-000002 ~]# gzip --no-name script.sh script.1.sh 
[root@master-000002 ~]# ll
total 248
-r-x------. 1 root root 123948 Feb 12 23:14 script.1.sh.gz
-r-x------. 1 root root 123948 Feb 12 23:10 script.sh.gz
[root@master-000002 ~]# md5sum script.*
c702f45d5c89878850aa373aafed73fe  script.1.sh.gz
c702f45d5c89878850aa373aafed73fe  script.sh.gz
```

**Comment by jim-minter** [comment]
@asalkeld ptal at this.  Putting the config blob on the master disk has meant that the masters rotate every time we scale up or down (the count changes in the compute AgentPoolProfile, so the hash changes, so there's a rotation).  This regression is blocking MSFT from rebasing.  One sorry way to work around this could be to remove all the non-master AgentPoolProfiles before serialising the config blob onto disk (probably zero out the ProvisioningState too for good measure) but it's pretty grim.

Another approach, now that we *know* we need two service principals, could be to revert the PR which got rid of the config blob.  Perhaps MSFT could ensure the worker service principal could not ListKeys on the config blob.  We could gradually move all the secrets from the config blob into a key vault later on.

@asalkeld do you have any other thoughts?

@amanohar could you chip in as well?

**Comment by jim-minter** [comment]
@kwoodson the output of gzip the command may depend on the input filename, but that doesn't mean that the same is true of golang compress/gzip.

**Comment by asalkeld** [comment]
@jim-minter I have zero'd out the count here: https://github.com/openshift/openshift-azure/pull/1129/commits/28c1edfaaa824e893df2dccead154ee237d53191

**Comment by mjudeikis** [comment]
I think we should not gzip if we dont need to. Until we hit the payload size limit. Introducing one more algorithm into the equation where we need stable output makes it difficult to determine where things fail.

**Comment by thekad** [comment]
I believe we were hitting the limit in the masters, that's why @asalkeld gzipped in the first place, threw me off for a loop there.
