### ISSUE TITLE
Quay shows vulnerabilities on our Docker images

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1130]
We must do a `RUN yum -y update && yum clean` as part of all our rhel based Dockerfile builds.  If that means we need to go to Dockerfile.foo.rhel7 and Dockerfile.foo.centos7 for local development, then so be it.

**Comment by kwoodson** [comment]
@jim-minter This was a topic of discussion around the team here https://github.com/openshift/openshift-azure/pull/1095#issuecomment-460663887.

We need to decide on which credentials we want to use for our builds.

**Comment by kwoodson** [comment]
This image is updated every sprint and is maintained by our internal infrastructure and build teams (aos-art).  The image is updated here https://access.redhat.com/containers/?tab=tags&architecture=AMD64#/registry.access.redhat.com/rhel7 and shows that the versions are up-to-date.

I will figure out why we are using an older version.  I docker pull'd the latest and the packages mentioned in the quay.io have been updated.

I think we want to continue using this rhel7 image but enforce a tag or use latest as it is the official image that we are using across Openshift.

**Comment by jim-minter** [comment]
@kwoodson https://github.com/openshift/release/pull/2854 should solve this

**Comment by jim-minter** [comment]
fixed
