### ISSUE TITLE
Miscellaneous test code cleanups

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1145]
Followups to #1092 

* stop exporting NewAzureClusterReaderClient, NewCustomerReaderClient, etc.
* simplify and standardise way above functions work
* remove AzureClusterReader, AzureClusterReaderKubeconfig from config struct, stop generating these in generate.go, generate on the fly in test like we do the other test logins
* remove shared.DataDirectory etc constants, make shared.FindDirectory take no argument, change things like
```
dataDir, _ := fakerp.FindDirectory(fakerp.DataDirectory)
cs, _ := managedcluster.ReadConfig(filepath.Join(dataDir, "containerservice.yaml"))
```
to
```
rootDir, _ := fakerp.FindDirectory()
cs, _ := managedcluster.ReadConfig(filepath.Join(rootDir, "_data/containerservice.yaml"))
```
* look at instantiating a ClientSet once globally for all e2e tests rather than doing it in BeforeEach stanzas, more efficient

**Comment by jim-minter** [comment]
@charlesakalugwu fyi
@y-cote please could you take these on?  The above notes are very sparse, please ping me for the unclear bits.

**Comment by jim-minter** [comment]
@Makdaam reassigning to you as you're in this bit of code currently.  The only thing left to do on this issue is to stop exporting the New.*Client() functions - 2 second job.

**Comment by ehashman** [comment]
@Makdaam can you update this issue with how much of this is completed?
