### ISSUE TITLE
Upgrade script rework

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1160]
currently, upgrade script https://github.com/openshift/openshift-azure/blob/master/hack/upgrade-e2e.sh is working with 2 repositories. One is cloned by prow/ci-operator, other we clone based on release tag provided with `make` target.

We need to simplify this script so we go `git checkouts tags/source` on prow/ci-operator provided code, instead of cloning it for the second time.

This will simplify `GOPATH` management and secret passing around.

**Comment by jim-minter** [comment]
@ehashman look at e2e-upgrade.sh - this is about removing the `git clone` there - use the git repo that is currently checked out in $PWD instead; record the commit you're on (like pushd), checkout the old commit of interest, then later pop back to the commit that you were on previously.

**Comment by ehashman** [comment]
Note: Script was moved to https://github.com/openshift/openshift-azure/blob/master/hack/tests/e2e-upgrade.sh in 917f75b2d862028f208570f9012e98731c999f99.

**Comment by jim-minter** [comment]
turns out the problem with this is that if a developer wants to run locally and their git repo isn't clean, we can easily scramble their work.  Let's not do this.  Sorry.
