### ISSUE TITLE
Automate container image build and promotion

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1161]
Currently, when the release is done we need to build images manually and push them to `quay.io`.

We need to automate this flow using post-submit jobs in prow and build images with git tag specification so images are published based on git tag as docker tag, and not static hardcoded tags from prow/ci-operator configuration.

This depends on registry we gonna publish too. If we need to start publishing to `registry.access.redhat.io`, this might change. Need to define a flow for it.

**Comment by ehashman** [comment]
I'm going to track this as part of the ACR work in JIRA (as opposed to doing this in quay.io) and will close this issue.
