### ISSUE TITLE
Sync-master pod labels

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#1181]
Looks like `sync-master-000000` is missing pod labels similar to 

```
    openshift.io/component: controllers
    openshift.io/control-plane: "true"
```

` openshift.io/component` label would be nice to have

https://github.com/openshift/openshift-azure/blob/master/pkg/arm/data/master-startup.sh#L642

cc @jim-minter

**Comment by jim-minter** [comment]
Reopening.  @sozercan why are you making this request? it's an internal OSA detail.

**Comment by jim-minter** [comment]
Reverting #1231 in #1232

**Comment by asalkeld** [comment]
@jim-minter what problem is this causing?

**Comment by jim-minter** [comment]
the labels chosen conflicted with the controllers, thus the sync pod was getting added to the controller service.  Also MSFT were looking at monitoring the sync pod via BBM when in fact we've got it covered with WBM.
