### ISSUE TITLE
don't hard-code 3 masters

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#119]
at the moment this is moderately hard coded

**Comment by mjudeikis** [comment]
Question:
Is this expected:
https://github.com/openshift/openshift-azure/blob/master/pkg/arm/data/master-startup.sh#L161-L166
We configure each master to point only to its local copy of ETCD.

Upstream: each master contains a full list of etcd clients. 
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_control_plane/templates/master.yaml.v1.j2#L54-L56

I see point for upstream to have this, as in most cases ETCD is external to masters. Now what we want to do on our end? 
@openshift/sig-azure ?

**Comment by kargakis** [comment]
I don't think we will be running etcd externally.

**Comment by mjudeikis** [comment]
This would explain upstream reasoning for having all the members in the config. In our case, what benefits/losses we would get if we have "each master point to its own ETCD vs having full list"?

**Comment by mjudeikis** [comment]
/close 
don't thin this is relevant anymore
