### ISSUE TITLE
look at autogenerating admin api client code

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1209]
don't want to maintain this all by hand.
one route is to try to use msft tooling, in which case step 1 is to autogenerate swagger like in https://github.com/Azure/azure-rest-api-specs, then step 2 is unclear (is the msft tooling even public?)
need to look at other routes too.

@charlesakalugwu fyi

**Comment by charlesakalugwu** [comment]
since we moved away from the autorest-oriented design for the admin api client, this is no longer necessary

/close
