### ISSUE TITLE
elb timed out waiting for the condition

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1336]
```
time="2019-03-23T22:15:04Z" level=debug msg="validating that the cluster can create ELB and ILB" func="github.com/openshift/openshift-azure/test/e2e/standard.(*SanityChecker).ValidateCluster" file="/go/src/github.com/openshift/openshift-azure/test/e2e/standard/sanitychecker.go:128"
STEP: waiting for elb to be ready (2019-03-23 22:15:06.488264642 +0000 UTC m=+1185.959672199)
time="2019-03-23T22:20:12Z" level=error msg="timed out waiting for the condition" func="github.com/openshift/openshift-azure/test/e2e/standard.(*SanityChecker).ValidateCluster" 
```

in artifacts:
```
count: 1
eventTime: null
firstTimestamp: 2019-03-23T22:18:05Z
involvedObject:
  apiVersion: v1
  kind: Service
  name: elb
  namespace: e2e-test-xpw2a
  resourceVersion: "11225"
  uid: 1d1c2e33-4db9-11e9-a72e-000d3a180cc8
lastTimestamp: 2019-03-23T22:18:05Z
message: 'Error creating load balancer (will retry): failed to ensure load balancer
  for service e2e-test-xpw2a/elb: Long running operation terminated with status ''Failed'':
  Code="InvalidResourceReference" Message="Resource /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/E2E-VQWMOVGJ/providers/Microsoft.Network/loadBalancers/KUBERNETES-INTERNAL
  referenced by resource /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-vqwmovgj/providers/Microsoft.Compute/virtualMachineScaleSets/ss-infra-1553376927
  was not found. Please make sure that the referenced resource exists, and that both
  resources are in the same region."'
metadata:
  creationTimestamp: 2019-03-23T22:18:05Z
  name: elb.158eb669839147a7
  namespace: e2e-test-xpw2a
  resourceVersion: "11734"
  selfLink: /api/v1/namespaces/e2e-test-xpw2a/events/elb.158eb669839147a7
  uid: 8807be0b-4db9-11e9-850b-000d3a180933
reason: CreatingLoadBalancerFailed
reportingComponent: ""
reportingInstance: ""
source:
  component: service-controller
type: Warning
```

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1335/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/78

**Comment by jim-minter** [comment]
very strange: creating the *external* load balancer, Azure invalid resource reference against kubernetes-*internal* load balancer?

**Comment by charlesakalugwu** [comment]
another one: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1351/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/54

**Comment by asalkeld** [comment]
So I have spent some time reading the azure cloudcontroller code and there maybe some explanations for the internal/external confusion.. (it's quite convoluted, so i could be wrong too).

we are creating 2 services elb (external) and ilb (internal).

1.
the loadbalancer's names are created based on: 
[clusterName] (for external lb)
[clusterName]-internal (for internal lb)

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_standard.go#L132

2.
EnsureLoadBalancer() first creates the lb in question (say the external lb "kubernetes") then does this

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L145-L146
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L590
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L594
this should then create the flipped lb (so "kubernetes-internal")
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L279
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L850

saying all that, it looks like the vm namespace is wrong

/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/e2e-vqwmovgj/providers/Microsoft.Compute/virtualMachineScaleSets/ss-infra-1553376927

e2e-vqwmovgj is the e2e generated namespace not the valid namespace for ss-infra-1553376927

**Comment by asalkeld** [comment]
because of the above, I might create and wait for each lb before moving onto the next one.

**Comment by mjudeikis** [comment]
I think this might be worth upstream issue too.

**Comment by mjudeikis** [comment]
Checked the logs and looks like this is a case, they are starting in sequence, only when one reconcile process is done. 
![image](https://user-images.githubusercontent.com/3225744/55313835-aa2a4000-5460-11e9-9787-8f136cb372ca.png)

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1425/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/438/build-log.txt

**Comment by jim-minter** [comment]
@asalkeld bump

**Comment by jim-minter** [comment]
last 5 instances:

2019/04/02 gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1393/pull-ci-openshift-openshift-azure-release-v3-e2e-azure-scaleupdown/6/build-log.txt
2019/04/02 gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1393/pull-ci-openshift-openshift-azure-release-v3-e2e-azure-scaleupdown/6/build-log.txt
2019/04/03 gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1411/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/385/build-log.txt
2019/04/03 gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1411/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/385/build-log.txt
2019/04/10 gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1425/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/438/build-log.txt

**Comment by asalkeld** [comment]
It seems like some of the older ones have azure ratelimiting issues. I'll ignore the older ones (prior to the new service principle changes) for now.

**Comment by asalkeld** [comment]
so the last one (2019/04/10)
```
time="2019-04-10T17:04:53Z" level=debug msg="validating that the cluster can create ELB and ILB" 
```
in the controller (I assume the times are not very accurate)

```
I0410 17:05:48.035962       1 azure_loadbalancer.go:477] reconcileLoadBalancer for service(e2e-test-8cfuh/elb) - wantLb(true): started
I0410 17:05:48.101918       1 azure_backoff.go:161] LoadBalancerClient.List(e2e-upgrade-asalkeld-1425-fimghy) - backoff: success
I0410 17:05:48.101958       1 azure_loadbalancer.go:484] reconcileLoadBalancer for service(e2e-test-8cfuh/elb): lb(kubernetes) wantLb(true) resolved load balancer name
I0410 17:05:48.153090       1 azure_loadbalancer.go:806] reconcileLoadBalancer: reconcileLoadBalancer for service(e2e-test-8cfuh/elb): lb(kubernetes) - updating
I0410 17:05:58.302576       1 logs.go:49] http: TLS handshake error from 10.0.0.11:51560: remote error: tls: bad certificate
I0410 17:05:59.065629       1 azure_loadbalancer.go:837] reconcileLoadBalancer for service(e2e-test-8cfuh/elb): lb(kubernetes) finished
I0410 17:05:59.102635       1 azure_loadbalancer.go:357] getServiceLoadBalancerStatus gets ingress IP "52.236.154.218" from frontendIPConfiguration "ac33a281a5bb211e9a369000d3a26e0d" for service "e2e-test-8cfuh/elb"
I0410 17:05:59.102674       1 azure_loadbalancer.go:138] EnsureLoadBalancer: reconciling security group for service "e2e-test-8cfuh/elb" with IP "52.236.154.218", wantLb = true
I0410 17:05:59.191423       1 azure_loadbalancer.go:1031] reconcileSecurityGroup for service(e2e-test-8cfuh/elb): sg(nsg-worker) - updating
I0410 17:06:01.005252       1 logs.go:49] http: TLS handshake error from 10.0.0.6:56358: remote error: tls: bad certificate
I0410 17:06:09.461281       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"e2e-test-8cfuh", Name:"elb", UID:"c33a281a-5bb2-11e9-a369-000d3a26e0dc", APIVersion:"v1", ResourceVersion:"19763", FieldPath:""}): type: 'Normal' reason: 'EnsuredLoadBalancer' Ensured load balancer
I0410 17:06:09.503698       1 service_controller.go:305] Ensuring LB for service e2e-test-8cfuh/ilb
I0410 17:06:09.503752       1 azure_loadbalancer.go:477] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb) - wantLb(false): started
I0410 17:06:09.503901       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"e2e-test-8cfuh", Name:"ilb", UID:"c34d4124-5bb2-11e9-a369-000d3a26e0dc", APIVersion:"v1", ResourceVersion:"19767", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
I0410 17:06:09.601246       1 azure_backoff.go:161] LoadBalancerClient.List(e2e-upgrade-asalkeld-1425-fimghy) - backoff: success
I0410 17:06:09.601299       1 azure_loadbalancer.go:484] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb): lb(kubernetes) wantLb(false) resolved load balancer name
I0410 17:06:09.601348       1 azure_loadbalancer.go:837] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb): lb(kubernetes) finished
I0410 17:06:09.651630       1 azure_backoff.go:187] PublicIPAddressesClient.List(e2e-upgrade-asalkeld-1425-fimghy) - backoff: success
I0410 17:06:09.651686       1 azure_loadbalancer.go:477] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb) - wantLb(true): started
I0410 17:06:09.709096       1 azure_backoff.go:161] LoadBalancerClient.List(e2e-upgrade-asalkeld-1425-fimghy) - backoff: success
I0410 17:06:09.709291       1 azure_loadbalancer.go:484] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb): lb(kubernetes-internal) wantLb(true) resolved load balancer name
I0410 17:06:09.793883       1 azure_loadbalancer.go:806] reconcileLoadBalancer: reconcileLoadBalancer for service(e2e-test-8cfuh/ilb): lb(kubernetes-internal) - updating
```
bla bla - much later (not sure why this takes 5 minutes)
```
I0410 17:11:34.178322       1 azure_loadbalancer.go:837] reconcileLoadBalancer for service(e2e-test-8cfuh/ilb): lb(kubernetes-internal) finished
I0410 17:11:34.179773       1 azure_loadbalancer.go:357] getServiceLoadBalancerStatus gets ingress IP "10.0.0.7" from frontendIPConfiguration "ac34d41245bb211e9a369000d3a26e0d" for service "e2e-test-8cfuh/ilb"
I0410 17:11:34.180770       1 azure_loadbalancer.go:138] EnsureLoadBalancer: reconciling security group for service "e2e-test-8cfuh/ilb" with IP "10.0.0.7", wantLb = true
```

**Comment by mjudeikis** [comment]
I got one more with 10 min time out:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1519/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/157

``` 
E0416 09:26:49.234747       1 azure_vmss.go:710] ensureHostsInVMSetPool() with scaleSet "ss-compute-1555405140" for service "e2e-test-i1zfr/ilb" failed: Long running operation terminated with status 'Failed': Code="AllocationFailed" Message="Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"```
Quota issue... 
And it got reconciled:

```
I0416 09:27:10.889817       1 azure_loadbalancer.go:357] getServiceLoadBalancerStatus gets ingress IP "10.0.0.11" from frontendIPConfiguration "a3ea5d320602811e993b4000d3a53011" for service "e2e-test-i1zfr/ilb"
```

Not sure if we want to re-open or what? @jim-minter

**Comment by jim-minter** [comment]
reopening.  @asalkeld please triage

here's another one:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1538/pull-ci-openshift-openshift-azure-master-vmimage/2/build-log.txt

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1538/pull-ci-openshift-openshift-azure-master-vmimage/4

**Comment by mjudeikis** [comment]
Some of the issues might be related to this issue https://github.com/openshift/openshift-azure/issues/1545 as ILB fails to create due the inability to update scaleset change LB settings.

**Comment by asalkeld** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1602/pull-ci-azure-release-v5-e2e-create/1

**Comment by asalkeld** [comment]
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1613/pull-ci-azure-master-upgrade-v5.0/22/
