### ISSUE TITLE
Define a way to update master-config.yaml

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#135]
As a SRE I would like to update `master-config.yaml` file without re-imaging or rotating master images.

Use case:
1. I build a cluster with default settings so my `FQDN` and `PublicHostname` got set to default RP values.
2. Now I want to change PublicHostname to my customer hostname. This invovles `OAuthClient`, `ConfigMaps` changes and `master-config.yaml` file changes.

At the moment this file is under control of master startup script. We should be able to change it without imaging all cluster as we might need minor changes like change whitelist for registries, configure AdmissionPlugin, etc.

@openshift/sig-azure ,  what do you think guys? Are we saying that "re-imaging" is the only way to change config?

**Comment by mjudeikis** [comment]
This prevents at the moment update PublicHostaname post cluster creation.

**Comment by kwoodson** [comment]
I like the idea of being able to update config without doing a complete _upgrade_ which is or could be a large hammer.  OTOH, I prefer our upgrade/update process be efficient enough that an upgrade isn't a scary/slow/terrible process.  If we are looking at < 1-3 hours for this process it might be acceptable.  If we are looking at much longer than that then I would be in favor of an out-of-band configuration update process.

I think configuration changes happen until the cluster settles and then they are mostly only touched during major upgrades.

**Comment by jim-minter** [comment]
@mjudeikis valid issue, needs to be a JIRA backlog item.  Please can you close this and create one.  It's sort of mixed in with AZURE-71, which needs to be divided up into sub-issues on a backlog call.

**Comment by mjudeikis** [comment]
Closing in favor of AZURE-97
