### ISSUE TITLE
write: connection reset by peer talking to storage account

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1400]
time="2019-04-02T00:37:12Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfgwdqw8oq44ss3x8eu4gd.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.16.144:44410->52.226.8.148:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1392/pull-ci-openshift-openshift-azure-master-e2e-azure/3270/build-log.txt

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1434/pull-ci-openshift-openshift-azure-master-e2e-azure/3400

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1485/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/511/

**Comment by asalkeld** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1493/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/572/build-log.txt

**Comment by mjudeikis** [comment]
not to the storage account but same issue:
https://github.com/openshift/openshift-azure/pull/1433

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1499/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/179

**Comment by jim-minter** [comment]
@asalkeld different failure mode:

time="2019-04-17T02:59:31Z" level=debug msg="400 Bad Request: Failed to apply request: WaitForReadySyncPod: Get https://vsemjeufeeankswgaalq.westeurope.cloudapp.azure.com/api/v1/namespaces/kube-system/services/sync/proxy/healthz/ready: dial tcp 40.74.17.51:443: connect: connection refused" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/tmp/tmp.ee0r2p61x5/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1516/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/181/build-log.txt

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1573/pull-ci-azure-master-upgrade-v4.2/14

**Comment by mjudeikis** [comment]
```
time="2019-04-30T11:19:26Z" level=info msg="waiting for API server healthz" func="github.com/openshift/openshift-azure/pkg/cluster.(*Upgrade).WaitForHealthzStatusOk" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/cluster/healthcheck.go:34"
time="2019-04-30T11:19:36Z" level=debug msg="ForHTTPStatusOk: will retry on the following error Get https://rjeylcjayckroxxshxfd.northeurope.cloudapp.azure.com/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" func=github.com/openshift/openshift-azure/pkg/util/wait.ForHTTPStatusOk.func1 file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/wait/wait.go:71"
time="2019-04-30T11:19:47Z" level=debug msg="ForHTTPStatusOk: will retry on the following error Get https://rjeylcjayckroxxshxfd.northeurope.cloudapp.azure.com/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" func=github.com/openshift/openshift-azure/pkg/util/wait.ForHTTPStatusOk.func1 file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/wait/wait.go:71"
time="2019-04-30T11:19:58Z" level=debug msg="ForHTTPStatusOk: will retry on the following error Get https://rjeylcjayckroxxshxfd.northeurope.cloudapp.azure.com/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" func=github.com/openshift/openshift-azure/pkg/util/wait.ForHTTPStatusOk.func1 file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/wait/wait.go:71"
time="2019-04-30T11:20:10Z" level=debug msg="ForHTTPStatusOk: will retry on the following error Get https://rjeylcjayckroxxshxfd.northeurope.cloudapp.azure.com/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" func=github.com/openshift/openshift-azure/pkg/util/wait.ForHTTPStatusOk.func1 file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/wait/wait.go:71"
time="2019-04-30T11:20:20Z" level=debug msg="ForHTTPStatusOk: will retry on the following error Get https://rjeylcjayckroxxshxfd.northeurope.cloudapp.azure.com/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" func=github.com/openshift/openshift-azure/pkg/util/wait.ForHTTPStatusOk.func1 file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/util/wait/wait.go:71"
time="2019-04-30T11:20:24Z" level=info msg="updating sync pod" func="github.com/openshift/openshift-azure/pkg/cluster.(*Upgrade).CreateOrUpdateSyncPod" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_syncpod.go:9"
time="2019-04-30T11:22:38Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfg1sq8h6ibjtkkxbnrb7z.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.234.227:35150->52.169.240.64:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:24"
time="2019-04-30T11:22:38Z" level=debug msg="ending:   PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1591-e2e-create-xnsuur/providers/Microsoft.ContainerService/openShiftManagedClusters/ci-1591-e2e-create-xnsuur?api-version=2019-04-30" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:17"
```

Failure even after retries.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1591/pull-ci-azure-master-e2e-create/115

**Comment by jim-minter** [comment]
here's the error:
```
time="2019-04-30T11:22:38Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateSyncPod: Put https://sacfg1sq8h6ibjtkkxbnrb7z.blob.core.windows.net/config/sync: net/http: HTTP/1.x transport connection broken: write tcp 172.16.234.227:35150->52.169.240.64:443: write: connection reset by peer" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/home/prow/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:24"
```

@asalkeld the problem here is that your error is having this unpleasantness done to it:
```
return fmt.Errorf("net/http: HTTP/1.x transport connection broken: %v", err)
```
(from net/http/transport.go)

This is going to need a horrible workaround - please take a look.  I've e-mailed go-nuts to ask about this as well.

**Comment by jim-minter** [comment]
(https://groups.google.com/forum/#!topic/golang-nuts/AkPSBPfZt0o)

**Comment by ehashman** [comment]
/reopen

Just saw this again: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1760/pull-ci-azure-master-upgrade-v4.4/294/build-log.txt

**Comment by m1kola** [comment]
Another one: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-upgrade-v5.2/136/build-log.txt

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1784/pull-ci-azure-master-upgrade-v5.1/329/build-log.txt in #1781

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1788/pull-ci-azure-master-upgrade-v5.2/174/build-log.txt in #1788

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1812/pull-ci-azure-master-upgrade-v5.2/460/build-log.txt in #1812

**Comment by asalkeld** [comment]
Note: " connection reset by peer" is not in here: https://github.com/openshift/openshift-azure/blob/master/pkg/cluster/kubeclient/roundtrip.go#L102-L127
I'll add it.
