### ISSUE TITLE
scale up times out

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1410]
```
time="2019-04-02T20:55:22Z" level=info msg="scaling ss-infra-1554236227 capacity up from 2 to 3" func="github.com/openshift/openshift-azure/pkg/cluster/scaler.(*workerScaler).scaleUp" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:107"
time="2019-04-02T21:10:23Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateWorkerAgentPoolUpdateScaleSet: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
```

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1397/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/224/build-log.txt

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1407/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/227/build-log.txt

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1408/pull-ci-openshift-openshift-azure-release-v4-upgrade-v3.2/11

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1430/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/334/build-log.txt

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1455/pull-ci-openshift-openshift-azure-master-upgrade-v4.0/172/build-log.txt

**Comment by asalkeld** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1455/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/31/build-log.txt

**Comment by jim-minter** [comment]
would like to prove that this is not #1409 before we add the retry logic.  Question: does VMSS scale up return before or after the CSE runs?  If after, then it could be that a CSE failure to run is causing the scale up to time out.

**Comment by jim-minter** [comment]
also happens starting masters:
```
time="2019-04-16T17:36:40Z" level=info msg="starting master-000001" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:64"
time="2019-04-16T17:51:40Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateMasterAgentPoolStart: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
```

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1526/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/167/build-log.txt

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1526/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/169/build-log.txt

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1584/pull-ci-azure-master-upgrade-v4.2/53

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1602/pull-ci-azure-master-upgrade-v3.2/144/build-log.txt

This log has a lot of debug info.

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1687/pull-ci-azure-master-upgrade-v3.2/300/build-log.txt

**Comment by y-cote** [comment]
Debug info available here :

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1690/pull-ci-azure-release-v5-upgrade-v3.2/17/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1687/pull-ci-azure-master-upgrade-v5.1/163/build-log.txt

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-upgrade-v5.1/322/build-log.txt in #1781

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1791/pull-ci-azure-master-upgrade-v5.1/366/build-log.txt #1791

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-upgrade-v5.2/402/build-log.txt in #1836

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1902/pull-ci-azure-master-upgrade-v7.0/174/build-log.txt in #1902

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1914/pull-ci-azure-master-upgrade-v7.1/54

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1901/pull-ci-azure-master-upgrade-v7.1/115/build-log.txt #1901

**Comment by olga-mir** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2133/pull-ci-azure-master-upgrade-v10.1.1/356/build-log.txt

(also logged this failing test in https://github.com/openshift/openshift-azure/issues/1442)
