### ISSUE TITLE
timeout while checking that cluster services are available

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1438]
Found a flake where a timeout occurs while checking that cluster services are available. This occured during the sanity checker's `checkCanAccessServices` method call during `ValidateCluster`

```
• Failure [178.329 seconds]
Openshift on Azure end user e2e tests [EndUser][Fake]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:12
  should validate the cluster [EndUser][Fake][Cluster] [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:28

  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "checkCanAccessServices",
              Err: {
                  Op: "Get",
                  URL: "https://openshift.e2e-create-charlesakalugwu-1417-awsptb.osadev.cloud/healthz",
                  Err: {
                      err: "net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
                      timeout: true,
                  },
              },
          },
      ]
  to be empty

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:30
```
artifacts; https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1417/pull-ci-openshift-openshift-azure-master-e2e-azure/3354/build-log.txt

/kind test-flake

**Comment by jim-minter** [comment]
should use prod roundtripper in test as well

**Comment by jim-minter** [comment]
@mjudeikis please can you set the test openshift clients to use the same retrying roundtripper that prod uses; also to fix the specific issue you'll need to mess with the RT in checkCanAccessServices

**Comment by charlesakalugwu** [comment]
#1642 

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-upgrade-v5.0/75/build-log.txt

**Comment by charlesakalugwu** [comment]
#1642
artifacts: 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-upgrade-v4.3/66/build-log.txt

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-e2e-create/192/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1656/pull-ci-azure-master-upgrade-v5.1/29/build-log.txt

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1652/pull-ci-azure-master-upgrade-v5.1/34

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1656/pull-ci-azure-master-upgrade-v5.1/31/build-log.txt

**Comment by mjudeikis** [comment]
This starts to look like something serious

**Comment by mjudeikis** [comment]
```
openshift-console                   12m         12m          1         console-6df8d84c8-vnvcw.159f33a61ed9895e                        Pod                                                                    Warning   FailedScheduling          default-scheduler                          0/5 nodes are available: 2 node(s) didn't match node selector, 3 node(s) were not ready.
```
```
openshift-web-console               12m         13m          21        webconsole-77bf7bbb76-6n47p.159f33a1ed4530b2                    Pod                                                                    Warning   FailedScheduling          default-scheduler                          0/3 nodes are available: 1 node(s) were not ready, 2 node(s) didn't match node selector.
openshift-web-console               12m         13m          12        webconsole-77bf7bbb76-vnhtp.159f33a1e8dd0b4d                    Pod                                                                    Warning   FailedScheduling          default-scheduler                          0/3 nodes are available: 1 node(s) were not ready, 2 node(s) didn't match node selector.
openshift-template-service-broker   
```

```
NAME                        STATUS    ROLES     AGE       VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION               CONTAINER-RUNTIME
compute-1558020463-000000   Ready     compute   12m       v1.11.0+d4cacc0   10.0.0.4      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
infra-1558020463-000000     Ready     infra     12m       v1.11.0+d4cacc0   10.0.0.5      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
infra-1558020463-000001     Ready     infra     12m       v1.11.0+d4cacc0   10.0.0.6      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
infra-1558020463-000002     Ready     infra     12m       v1.11.0+d4cacc0   10.0.0.7      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
master-000000               Ready     master    14m       v1.11.0+d4cacc0   10.0.0.8      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
master-000001               Ready     master    14m       v1.11.0+d4cacc0   10.0.0.9      <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
master-000002               Ready     master    13m       v1.11.0+d4cacc0   10.0.0.10     <none>        Red Hat Enterprise Linux Server 7.6 (Maipo)   3.10.0-957.12.2.el7.x86_64   docker://1.13.1
```

**Comment by Makdaam** [comment]
More flakes (more or less at the same time):
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1659/pull-ci-azure-master-e2e-create/219
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1659/pull-ci-azure-master-upgrade-v4.4/29
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1659/pull-ci-azure-master-upgrade-v5.1/33

**Comment by ehashman** [comment]
Re: the scheduling failures above, I do see those reproduced across many of the flakes but I think that's a red herring. Note that they're failing scheduling where the node count is only 3 or 5. The full CI cluster consists of 7 nodes (3 masters, 3 infra, 1 compute). I looked through the event logs (e.g. for [this build](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-e2e-create/194/artifacts/events)) and eventually once the infra/compute nodes post NodeReady everything gets scheduled. The final pod artifact shows all the console pods scheduled successfully and running: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-e2e-create/194/artifacts/pods

As I discussed with @asalkeld during standup, there are a lot of expected, transient failures when clusters initially start that make it hard to find real errors in all the noise.

I do have a question for @charlesakalugwu. For the `checkCanAccessServices` failure, I noticed there's a comment in the retry code that suggests that we reduced the default dial timeout from 30s to 10s. I don't really understand why we did this from the comment, so I thought I'd ask if that could that potentially be contributing to this issue? Code here: https://github.com/openshift/openshift-azure/blob/d90c077ff9f3ea084c33326329aa98c5c6c06123/test/e2e/standard/cluster.go#L300-L318

I am still pretty stumped... maybe we are just not waiting long enough for the cluster to finish spinning up to check this? The timestamp on the failure of the build I'm looking at is `time="2019-05-14T12:34:31Z"`. Pod events that indicate successful scheduling were posted 26m prior to the `kubectl get pods` dump but I can't find a corresponding timestamp for when that was run.

**Comment by y-cote** [comment]
Seen again at : #1670 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1670/pull-ci-azure-master-e2e-create/239/build-log.txt

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1698/pull-ci-azure-master-upgrade-v5.1/138/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1698/pull-ci-azure-master-e2e-create/321/build-log.txt

Also northeurope.

**Comment by ehashman** [comment]
Three more instances of this, all northeurope:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1769/pull-ci-azure-master-e2e-create/470/build-log.txt #1769 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1767/pull-ci-azure-master-upgrade-v5.2/98/build-log.txt #1767
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1723/pull-ci-azure-master-e2e-create/469/build-log.txt #1723

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1776/pull-ci-azure-master-e2e-create/504/build-log.txt in #1776

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-upgrade-v4.4/306/build-log.txt in #1781

**Comment by kwoodson** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1750/pull-ci-azure-master-upgrade-v5.2/204 in #1750

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1879/pull-ci-azure-master-upgrade-v6.0/96

**Comment by thekad** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1951/pull-ci-azure-master-e2e-create/1144/build-log.txt

**Comment by asalkeld** [comment]
may of these are of the following pattern

```
should be possible for an SRE to update a single container image
```
The above changes the image of the console deployment, and should cause it to restart. we then do "validateCluster" - which is rather excessive, but the normal failure is
```
  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "checkCanAccessServices",
              Err: {
                  Op: "Get",
                  URL: "https://console.apps.ci-1659-e2e-upgrade-ivotjr.osadev.cloud/health",
                  Err: {
                      err: "dial tcp 40.67.252.222:443: i/o timeout (Client.Timeout exceeded while awaiting headers)",
                      timeout: true,
                  },
              },
          },
      ]
  to be empty
```
which is unsuprising as it is restarting. I'll do the following:
1. make a more focused test
2. wait longer for the console to be available.

/assign
