### ISSUE TITLE
ssh rejected - administratively prohibited

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1442]
Saw a flake with the following entries in the logs

```
time="2019-04-05T13:34:41Z" level=warning msg="Dial failed: ssh: rejected: administratively prohibited (open failed)" func=github.com/openshift/openshift-azure/pkg/fakerp.debugDeployerError file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:69"
time="2019-04-05T13:34:42Z" level=warning msg="Dial failed: ssh: rejected: administratively prohibited (open failed)" func=github.com/openshift/openshift-azure/pkg/fakerp.debugDeployerError file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:69"
time="2019-04-05T13:34:42Z" level=warning msg="Dial failed: ssh: rejected: administratively prohibited (open failed)" func=github.com/openshift/openshift-azure/pkg/fakerp.debugDeployerError file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:69"
```
artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1430/pull-ci-openshift-openshift-azure-master-e2e-azure/3407/build-log.txt

/kind test-flake

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1520/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/162/build-log.txt

**Comment by jim-minter** [comment]
The fixes were made to master but not backported, thus this error can still occur on v3/v4 upgrade flows.  Will consider the priority of fixing this.

**Comment by ehashman** [comment]
/reopen

```
 time="2019-10-10T12:10:58Z" level=warning msg="Dial failed: ssh: rejected: administratively prohibited (open failed)" func="test/util/diagnostics.(*scalesetDebugger).GatherHostLogs()" file="test/util/diagnostics/scaleset.go:51"
time="2019-10-10T12:10:58Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateWorkerAgentPoolUpdateScaleSet: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded" func="pkg/fakerp.(*Server).badRequest()" file="pkg/fakerp/util.go:24"
time="2019-10-10T12:10:58Z" level=debug msg="ending:   PUT /admin/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1995-e2e-upgrade-vbktko/providers/Microsoft.ContainerService/openShiftManagedClusters/ci-1995-e2e-upgrade-vbktko" func="pkg/fakerp.(*Server).logger.func1()" file="pkg/fakerp/middleware.go:18"
time="2019-10-10T12:10:58Z" level=fatal msg="400: 400 Bad Request: Failed to apply request: UpdateWorkerAgentPoolUpdateScaleSet: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded\n" 
```

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1995/pull-ci-azure-master-upgrade-v7.1/198/build-log.txt #1995

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2009/pull-ci-azure-master-upgrade-v7.1/229/build-log.txt in #2009

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2019/pull-ci-azure-release-v10-upgrade-v9.0/8/build-log.txt #2019

**Comment by olga-mir** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2133/pull-ci-azure-master-upgrade-v10.1.1/356/build-log.txt

I've looked at a few logs linked in this issue and they are followed by the error logged here: https://github.com/openshift/openshift-azure/issues/1410
it's probably the same flake.
