### ISSUE TITLE
Update flake: timeout starting master

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1448]
```
time="2019-04-05T14:55:43Z" level=info msg="starting master-000002" func="github.com/openshift/openshift-azure/pkg/cluster.(*simpleUpgrader).UpdateMasterAgentPool" file="/go/src/github.com/openshift/openshift-azure/pkg/cluster/update_master.go:64"
time="2019-04-05T15:10:43Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateMasterAgentPoolStart: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
```

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1440/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/336/build-log.txt

needs retry logic

**Comment by asalkeld** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1497/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/496/build-log.txt

**Comment by mjudeikis** [comment]
request context got cancelled: 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1519/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/159

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1490/pull-ci-openshift-openshift-azure-master-e2e-azure/3627

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1490/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/581

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1526/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/167/build-log.txt

**Comment by y-cote** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1509/pull-ci-openshift-openshift-azure-master-e2e-azure/3637

**Comment by y-cote** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1509/pull-ci-openshift-openshift-azure-master-e2e-azure-scaleupdown/659

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1500/pull-ci-openshift-openshift-azure-master-e2e-azure/3666
