### ISSUE TITLE
customer-admin should be able to list groups

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1452]
trying to list groups and members of those in prod cluster but getting:
```
[mjudeiki@redhat openshift-azure]$ oc get group
Error from server (Forbidden): groups.user.openshift.io is forbidden: User "mjudeikis@rhcuppettgmail.onmicrosoft.com" cannot list groups.user.openshift.io at the cluster scope: no RBAC policy matched
```

This way there is no easy way to check if sync works or what got in. A little bit inconvenient.

**Comment by mjudeikis** [comment]
same with nodes:
```
[mjudeiki@redhat experience-managed-openshift-on-azure]$ oc get nodes
Error from server (Forbidden): nodes is forbidden: User "mjudeikis@rhcuppettgmail.onmicrosoft.com" cannot list nodes at the cluster scope: no RBAC policy matched
```

I scaled the cluster and I cant see what is happening :/

**Comment by jim-minter** [comment]
am not completely sure I want to do this - has knock-on effects which may be unwanted once there are more groups
fwiw you can check if you're customer-admin by listing clusterservicebrokers

**Comment by mjudeikis** [comment]
yes, but I dont want to give this answer to the customers, when they ask about groups, nodes, etc.

**Comment by ehashman** [comment]
/close

Should be covered by the OSD customer-admin parity changes.
