### ISSUE TITLE
add router LB metrics into metrics shim

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1461]
We need to track router load balancer and routers availability during upgrades

**Comment by jim-minter** [comment]
@mjudeikis please can you clarify this issue?  Router stats should get rolled up into metricsbridge now; cmd/monitoring should already check canary availability and hence router availability?  What else is wanted?

**Comment by mjudeikis** [comment]
Router has its own Loadbalancer/IP address. Metricsbridge is monitoring the availability of individual master and API via a load balancer. We should monitor router as "an application" too. 
So when we see canary application downtime in the data, we know this happened due to canary app itself, and not router outage during an upgrade. And another way around.
