### ISSUE TITLE
upgrades are failing with: "found 0 service principals, should be 1"

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#1468]
see: https://github.com/openshift/openshift-azure/pull/1465
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1465/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/393/build-log.txt

/kind test-flake
@jim-minter

**Comment by charlesakalugwu** [comment]
this also prevents us from bringing up clusters locally :(

**Comment by charlesakalugwu** [comment]
according to @mjudeikis `v3.2` and `v4.0` still expects `export AZURE_MASTER_CLIENT_ID` variables to be present. And these correspond to AAD instances in AAD. they used to exist until yesterday (8th April 2019).
