### ISSUE TITLE
API model and custom VNET comments

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#148]
**1)** `MasterProfile`: https://github.com/openshift/openshift-azure/blob/master/pkg/api/types.go#L95-L100  doesn't have a `VNETSubnetID` defined. 

Is this because in the custom VNET scenario we are expecting the master to be in a different VNET & subnet is going to created on the fly  by RP/service instead of the one specified by customer?

**2)** Public API model is missing `MasterProfile`: https://github.com/openshift/openshift-azure/blob/master/pkg/api/v1/types.go#L45 and `AgentPoolProfiles` is being used to define both `Master` and `Agent` nodes in addition to `Infra`. 

Master and agents conceptually have different roles to play in the architecture of this OSA resource/product. Repurposing `agentPoolProfile` to define them all using property `Role` is too generic and could lead to validation errors (e.g. if `role` == `master` then `count` can't be 6), overcrowding of property list in the struct that might only work for one role and not the other.

Additionally, public model represents an easy to understand and crisp definition of the resource to the customer and should be opinionated aka in this case it makes sense to separate masterprofile.

**3)** Additionally, recommend adding `NetworkProfile` section to the public API model for supporting custom VNET. Documentation for AKS custom VNET: https://docs.microsoft.com/en-us/azure/aks/networking-overview

```
type NetworkProfile struct {
	NetworkPlugin    NetworkPlugin `json:"networkPlugin,omitempty"`
	NetworkPolicy    NetworkPolicy `json:"networkPolicy,omitempty"`
	PodCidr          string        `json:"podCidr,omitempty"`
	ServiceCidr      string        `json:"serviceCidr,omitempty"`
	DNSServiceIP     string        `json:"dnsServiceIP,omitempty"`
	DockerBridgeCidr string        `json:"dockerBridgeCidr,omitempty"`
}
```

`NetworkPlugin` can default to `kubenet`. And Azure CNI can be added later.

**Kubernetes Pod CIDR** (sometimes cluster-cidr): Address range managed by a Kubernetes cluster used to assign IP addresses to customer Pods. 
When an overlay network, for example, Kubenet, is used, this address range is given by customer. The range does not have to live within the VNET but it should not collide with the subnet used for cluster nodes to avoid traffic mis-routing.

**Kubernetes Service CIDR:** Address range used to allocate IP addresses for Kubernetes cluster Services. This range does not need to live within the containing VNET. Validation is also required to make sure there is no collision with address ranges defined in node and pod CIDR. It also is not usually directly routable by VMs that are not participating in the Kubernetes cluster. 

**Docker Bridge**: Address range used inside the docker bridge interfaces. This range defaults to 172.17.0.0/16 and need only be changed if the customer is using an overlapping/conflicting subnet within their larger VNET. 

cc: @qike-ms @pweil-  @jim-minter

**Comment by pweil-** [comment]
First, thanks for taking a detailed look at this!  I'll try to address some of the items but I think we can leave this issue open for more discussion.

> 1) MasterProfile: https://github.com/openshift/openshift-azure/blob/master/pkg/api/types.go#L95-L100 doesn't have a VNETSubnetID defined.
> 
> Is this because in the custom VNET scenario we are expecting the master to be in a different VNET & subnet is going to created on the fly by RP/service instead of the one specified by customer?

`VNETSubnetID` is defined in the agent pool and master is just an agent pool with a specific role as noted below.

> 
> 2) Public API model is missing MasterProfile: https://github.com/openshift/openshift-azure/blob/master/pkg/api/v1/types.go#L45 and AgentPoolProfiles is being used to define both Master and Agent nodes in addition to Infra.
> 
> Master and agents conceptually have different roles to play in the architecture of this OSA resource/product. Repurposing agentPoolProfile to define them all using property Role is too generic and could lead to validation errors (e.g. if role == master then count can't be 6), overcrowding of property list in the struct that might only work for one role and not the other.
> 
> Additionally, public model represents an easy to understand and crisp definition of the resource to the customer and should be opinionated aka in this case it makes sense to separate masterprofile.
> 

[I was in agreement here](https://github.com/Azure/acs-engine/pull/3556#pullrequestreview-140695855) but @jim-minter and @kargakis made a good argument that there is no difference between a separate `MasterProfile` struct with repeated (or embedded) fields that are reused in the `AgentPoolProfile` vs an `AgentPoolProfile` strut with a `{role}Config` struct if we need specialized configuration.  

This is pretty similar to a [k8s volume source](https://github.com/kubernetes/api/blob/183f3326a9353bd6d41430fc80f96259331d029c/core/v1/types.go#L47)

I think it's a wash but did note the role based validation issue though it is isolated only to role/shared data pairs that need validation since config structs isolate the other fields.

> 3) Additionally, recommend adding NetworkProfile section to the public API model for supporting custom VNET. Documentation for AKS custom VNET: https://docs.microsoft.com/en-us/azure/aks/networking-overview
> 
> type NetworkProfile struct {
> 	NetworkPlugin    NetworkPlugin `json:"networkPlugin,omitempty"`
> 	NetworkPolicy    NetworkPolicy `json:"networkPolicy,omitempty"`
> 	PodCidr          string        `json:"podCidr,omitempty"`
> 	ServiceCidr      string        `json:"serviceCidr,omitempty"`
> 	DNSServiceIP     string        `json:"dnsServiceIP,omitempty"`
> 	DockerBridgeCidr string        `json:"dockerBridgeCidr,omitempty"`
> }
> NetworkPlugin can default to kubenet. And Azure CNI can be added later.

I don't predict allowing the user to choose this.  We will use the OpenShift tested and approved SDN plugin [redhat-ovs-subnet](https://github.com/openshift/openshift-azure/blob/51070db75b1d02946ba33c644b911976d0734f3d/pkg/addons/data/ConfigMap/openshift-node/node-config-master.yaml#L47).  I know the network team has been looking at Azure CNI too but right now it isn't a choice the user can make.

> 
> Kubernetes Pod CIDR (sometimes cluster-cidr): Address range managed by a Kubernetes cluster used to assign IP addresses to customer Pods.
> When an overlay network, for example, Kubenet, is used, this address range is given by customer. The range does not have to live within the VNET but it should not collide with the subnet used for cluster nodes to avoid traffic mis-routing.
> 
> Kubernetes Service CIDR: Address range used to allocate IP addresses for Kubernetes cluster Services. This range does not need to live within the containing VNET. Validation is also required to make sure there is no collision with address ranges defined in node and pod CIDR. It also is not usually directly routable by VMs that are not participating in the Kubernetes cluster.
> 
> Docker Bridge: Address range used inside the docker bridge interfaces. This range defaults to 172.17.0.0/16 and need only be changed if the customer is using an overlapping/conflicting subnet within their larger VNET.

I think these are all worthy additions in the post private preview world. Thanks for pointing them out.

**Comment by amanohar** [comment]
@pweil- thanks for the reply. Regarding:

> I was in agreement here but @jim-minter and @kargakis made a good argument that there is no difference between a separate MasterProfile struct with repeated (or embedded) fields that are reused in the AgentPoolProfile vs an AgentPoolProfile strut with a {role}Config struct if we need specialized configuration.

Repeated fields can be eliminated by using composition. 

However, it's valuable to represent master and agent nodes separately from cluster definition standpoint because they are different with fields potentially diverging over time (+other reasons listed in my comment above). 

Additionally, its easier to understand, define, and read cluster definition if master and agent pool profiles are separated vs. reading through a list of agentpoolprofiles to find master definition.

**Comment by pweil-** [comment]
We've discussed and addressed most of the items here.  The remaining piece is the recommendation of new configuration items for CIDRs.  With that I'm going to change this to a feature vs cleanup.

**Comment by kargakis** [comment]
Can we close this issue and open a new one just for that? Should be cleaner than continuing to track here.

**Comment by pweil-** [comment]
https://github.com/openshift/openshift-azure/issues/204
