### ISSUE TITLE
createStatefulApp templateinstance failed

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1481]
```
• Failure [99.752 seconds]
Openshift on Azure end user e2e tests [EndUser][Fake]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:12
  should create and validate test apps [EndUser][Fake][Apps] [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:13

  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "createStatefulApp",
              Err: {
                  s: "templateinstance e2e-test-qqp1q/e2e-test-qqp1q failed",
              },
          },
      ]
  to be empty

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:17
```

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1479/pull-ci-openshift-openshift-azure-master-e2e-azure/3481/build-log.txt

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1479/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/425/build-log.txt

**Comment by asalkeld** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1479/pull-ci-openshift-openshift-azure-master-e2e-azure/3481/artifacts/internal-e2e/events

```
e2e-test-qqp1q                      9m          9m           1         django-psql-persistent-1.1593e73ebdcf2f9f                      Build                                                                  Normal    BuildFailed               build-controller                           Build e2e-test-qqp1q/django-psql-persistent-1 failed
```

**Comment by jim-minter** [comment]
@asalkeld please can you work this issue

**Comment by asalkeld** [comment]
They both have a BuildFailed event but there seems to be 2 different reasons for it.

1. e2e test
```
E0409 20:07:41.152242       1 buildconfig_controller.go:141] gave up on Build for BuildConfig e2e-test-qqp1q/django-psql-persistent (0) due to fatal error: the LastVersion(1) on build config e2e-test-qqp1q/django-psql-persistent does not match the build request LastVersion(0)
I0409 20:07:41.152322       1 buildconfig_controller.go:245] Will not retry fatal error for key e2e-test-qqp1q/django-psql-persistent: fatal: the LastVersion(1) on build config e2e-test-qqp1q/django-psql-persistent does not match the build request LastVersion(0)
I0409 20:07:41.210309       1 deploymentconfig_controller.go:500] Error syncing deployment config e2e-test-qqp1q/postgresql: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "postgresql": the object has been modified; please apply your changes to the latest version and try again
```
Our logs do seem to be full of these "LastVersion" errors.

2. upgrade
This log is missing 
```
1 build_controller.go:242] Starting build controller
1 buildconfig_controller.go:193] Starting buildconfig controller
```
(and so no logs at all from these controllers)
How could this just not start?

**Comment by asalkeld** [comment]
Actually the LastVersion errors were a red herring, the successful upgrade tests have them too.

**Comment by asalkeld** [comment]
So here is a build log error:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1552/upgrade-v3.2/26/artifacts/build-e2e-test-vtx18-django-psql-persistent-1.log

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1552/upgrade-v3.2/26/artifacts/

**Comment by asalkeld** [comment]
this seems to be some kind of network error as pypi was up at this time : https://status.python.org/#month

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1723/pull-ci-azure-master-e2e-create/467/build-log.txt #1723

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1805/pull-ci-azure-release-v6-e2e-create/5/build-log.txt #1805

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1815/pull-ci-azure-master-upgrade-v5.2/289/build-log.txt in #1815

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1813/pull-ci-azure-master-upgrade-v5.1/484/build-log.txt in #1813

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1842/pull-ci-azure-master-e2e-create/807/build-log.txt #1842

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1957/pull-ci-azure-master-e2e-create/1154/build-log.txt in #1957 

This one seems to have been caused by inability to pull from the redhat registry. See [build-django-psql-persistent-1.log](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1957/pull-ci-azure-master-e2e-create/1154/artifacts/createStatefulApp/build-django-psql-persistent-1.log) for this build.

```
pulling image error : unknown: unable to pull manifest from registry.redhat.io/rhscl/python-36-rhel7:latest: Get https://registry.redhat.io/v2/rhscl/python-36-rhel7/manifests/sha256:18d9d020626b44ac3687ebda3919633c76527c896162f1c88f73f64c8d17b4a9: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1950/pull-ci-azure-master-upgrade-v7.1/82/build-log.txt in #1950

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1998/pull-ci-azure-master-upgrade-v9.0/123

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2154/pull-ci-azure-master-e2e-create-20191027-private/272/build-log.txt #2154

**Comment by ehashman** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2240/pull-ci-azure-master-e2e-create-20191027-private/833
