### ISSUE TITLE
azProfile in internal datamodel

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#150]
`azProfile` doesn't need to be in `Properties` of internal data model:https://github.com/openshift/openshift-azure/blob/master/pkg/api/types.go#L38 as the RP already has this metadata and can be passed separately to the OSA plugin.

**Comment by pweil-** [comment]
noted in other conversations but metioning here: need to settle on *how* this data will be passed asap.  We can have it in the internal model if the RP will set them as part of the enrichment process or we could have it as method args.  I think I lean towards having them in the data model so they are available for support operations when reviewing the config.

**Comment by kargakis** [comment]
I am fine with storing elsewhere, assuming it's going to be encrypted in storage, but we definitely need a way for support to know these values.

**Comment by pweil-** [comment]
@sozercan @amanohar @shrutir25 - any other guidance here, are you suggesting a plugin signature change?  It seems easiest to leave this in the enrichment portion of the data model so that it's available when someone is looking at the persisted config.

**Comment by jim-minter** [comment]
as discussed today we're removing the duplication of azProfile (#413) but keeping azProfile.  It's handy to have this stuff persisted into the config blob so it beats the context route for passing this into the plugin.  Hence closing this issue, feel free to re-open if needed.
