### ISSUE TITLE
flake: ExtHandler Fetch failed

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1504]
Deploy fails with the following WA Agent log:

Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.533114 WARNING ExtHandler Fetch failed from [http://168.63.129.16:32526/extensionArtifact]: [HTTP Failed] [400: Bad Request]

**Comment by jim-minter** [comment]
https://github.com/Azure/WALinuxAgent/issues/1505 opened upstream

**Comment by ehashman** [comment]
Upstream fix has been merged, I think this can be closed now.

/close
