### ISSUE TITLE
AAD App auth issues

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#151]
https://github.com/openshift/openshift-azure/blob/master/pkg/addons/data/Deployment.apps/default/docker-registry.yaml#L72

We should use Azure SDK (or ARM) instead of using CLI for creating/getting azure resources. This will create issues with managed apps since we'll have to grant additional authorization for AAD ID/SPN.

You can list using arm:
https://github.com/Azure/azure-quickstart-templates/blob/b1e5b3407fbfe5d98c99355f3373bf8693110571/201-aci-wordpress/azuredeploy.json#L220
and then pass it in for example:
https://github.com/Azure/acs-engine/blob/4bee179947cd1a2a1d3965c46bb22f808b4bfc79/parts/k8s/kubernetesmastervars.t#L266

**Comment by kargakis** [comment]
I am importing the azure sdk in https://github.com/openshift/openshift-azure/pull/138

We could definitely clean this up afterwards and rewrite bash to go. @kwoodson @pweil- do you think this is a blocker for PP? Doesn't look like to me.

/kind cleanup

**Comment by pweil-** [comment]
only blocks if we cannot get this working with MSI.  @kwoodson  was investigating.

**Comment by pweil-** [comment]
This has been discussed and agreed to continue using SP for now. https://github.com/openshift/openshift-azure/pull/188#discussion_r210094350
