### ISSUE TITLE
checkCanDeployRedhatIoImages e2e test fails

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#1515]
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1514/pull-ci-openshift-openshift-azure-master-upgrade-v4.2/148/

/kind flake-test

**Comment by jim-minter** [comment]
thanks @asalkeld, please can you triage to see what went wrong?

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1511/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/593

**Comment by asalkeld** [comment]
I'll close, can always reopen if we get more.
/close

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1997/pull-ci-azure-release-v10-e2e-scaleupdown-v9.0/1/build-log.txt #1997

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2055/pull-ci-azure-release-v11-e2e-scaleupdown-v9.0/1

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2055/pull-ci-azure-release-v11-e2e-scaleupdown-v7.1/1
