### ISSUE TITLE
The entity was not found in this Azure location

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1540]
```
time="2019-04-17T16:39:09Z" level=debug msg="400 Bad Request: Failed to apply request: UpdateMasterAgentPoolUpdateVMs: compute.VirtualMachineScaleSetsClient#UpdateInstances: Failure sending request: StatusCode=404 -- Original Error: Code=\"NotFound\" Message=\"The entity was not found in this Azure location.\"" func="github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest" file="/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:11"
```

**Comment by jim-minter** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1538/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/634/build-log.txt

**Comment by ehashman** [comment]
My guess for what's going wrong here is that a location is being assumed and a mismatch is happening, resulting in this error. See e.g. https://stackoverflow.com/questions/42121829/azure-automation-onboarding-dsc-node-vmname-the-entity-was-not-found
