### ISSUE TITLE
Should kubeconfigs be part of the internal model

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-azure#157]
See https://github.com/openshift/openshift-azure/pull/153#discussion_r207622067 for discussion

cc @amanohar

**Comment by amanohar** [comment]
This is mostly in the context of resource provider (RP)/service kubeconfig(s) to be used by operations team for access to OSA cluster and not the kubeconfigs used by components of OSA cluster.

The operations team kubeconfig can be part of `Config` and also be saved separately (implementation detail). It would be good to avoid duplication of data but not a blocker.

**Comment by pweil-** [comment]
@sozercan @amanohar @shrutir25 - looking for guidance here and if there will be a plugin signature change.  Otherwise we can close.
