### ISSUE TITLE
periodic VMImage build notifier

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1570]
We need periodic job which:
1. Builds VMImage periodically and captures RPMS delta. This is not yet clear how we should record old RPMS/packages.
2. If there is a delta, it should raise/update an issue with notifying that we need to publish new VM image.

**Comment by ehashman** [comment]
This is covered by Mikalai's work in [AZURE-326](https://jira.coreos.com/browse/AZURE-326) I think.
