### ISSUE TITLE
etcd and controller manager don't use readinessProbes

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#161]
Investigate whether we can set them up in order to take advantage of pod readiness when healthchecking them during an install/upgrade.

@openshift/sig-azure

**Comment by kargakis** [comment]
This may be intentional since these are not fronted by a service?

**Comment by mjudeikis** [comment]
I was under impression readinessProbles are on Pod level? 
If the pod is not ready, remove it from the "Service Pool" ? So they should not depend on the existence of service?

**Comment by kargakis** [comment]
Services support adding unready pods into their pool but this issue is not about advocating the use of a service but rather try to figure out whether pod readiness is going to be useful in general.

**Comment by mjudeikis** [comment]
In general, I think having probes on all pods would make checking unified.

**Comment by pweil-** [comment]
https://github.com/openshift/origin/blob/94e032a6b5bbd12cedf4543c3cb82c58923c2143/install/openshift-controller-manager/install.yaml#L61-L65

(the kube controller manager seems to only have a liveness probe though)
