### ISSUE TITLE
checkCanUseAzureFile timed out

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#1616]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1613/pull-ci-azure-master-upgrade-v4.3/19

/kind test-flake

**Comment by thekad** [comment]
Another one: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1764/pull-ci-azure-master-vmimage/3

**Comment by charlesakalugwu** [comment]
This is the error signature

```
• Failure [780.500 seconds]
Openshift on Azure end user e2e tests [EndUser][Fake][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:12
  should validate the cluster [EndUser][Fake][Cluster] [It]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:28

  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "checkCanUseAzureFile",
              Err: {
                  s: "timed out waiting for the condition",
              },
          },
      ]
  to be empty

  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:30
```

Caught another one here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1764/pull-ci-azure-master-vmimage/4/build-log.txt

**Comment by thekad** [comment]
Haven't seen this in over a month, will close and reopen if we see it again but I suspect this surfaced as a network exception
/close
