### ISSUE TITLE
Follow-up after https://github.com/openshift/origin/pull/22742

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1620]
Follow-up after https://github.com/openshift/origin/pull/22742:

* When the DisableOutboundSNAT setting becomes available in OCP, start using it.  Check the upgrade behaviour.

* Investigate if `Microsoft.Storage/storageAccounts/read` can be removed from master and worker RBAC.

@mjudeikis @ingvagabund fyi

**Comment by asalkeld** [comment]
@mjudeikis close this?
