### ISSUE TITLE
Timed out waiting to ensure resource group is created

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1628]
We found a test flake where a time out occurred while waiting to ensure that a resource group existed/was created.

```
time="2019-05-09T14:01:49Z" level=info msg="using region northeurope"
time="2019-05-09T14:01:49Z" level=info msg="ensuring resource group ci-1625-e2e-upgrade-xghagv"
time="2019-05-09T14:02:53Z" level=fatal msg="timed out waiting for the condition"
exit status 1
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1625/pull-ci-azure-master-upgrade-v5.0/38/build-log.txt

/kind test-flake

**Comment by charlesakalugwu** [comment]
I believe the issue outlined here is the cause of #1617. Furthermore it seems all the examples of this issue occur in the `northeurope` region

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1621/pull-ci-azure-master-upgrade-v5.0/42/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1679/pull-ci-azure-master-upgrade-v5.1/245/build-log.txt

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1782/pull-ci-azure-master-upgrade-v5.1/321/build-log.txt in #1782

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-upgrade-v5.2/140/build-log.txt in #1781

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1801/pull-ci-azure-master-upgrade-v5.1/420/build-log.txt in #1801 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1801/pull-ci-azure-master-upgrade-v5.2/240/build-log.txt in #1801

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1821/pull-ci-azure-master-upgrade-v5.1/581/build-log.txt in #1821

**Comment by m1kola** [comment]
Another one in #1821 

https://prow.svc.ci.openshift.org/log?id=403&job=pull-ci-azure-master-upgrade-v5.2

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1880/pull-ci-azure-master-upgrade-v6.0/98/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1880/pull-ci-azure-master-upgrade-v7.0/94/build-log.txt
#1880

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1947/pull-ci-azure-master-upgrade-v7.1/31/build-log.txt in #1947

**Comment by charlesakalugwu** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1957/pull-ci-azure-master-upgrade-v7.1/72 in #1957 

Here I was able to verify locally that the resource group in question `ci-1957-e2e-upgrade-hdybmx` exists and is successfully provisioned.
```
[charles@akalugwu openshift-azure]$  az group show --name  ci-1957-e2e-upgrade-hdybmx
{
  "id": "/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1957-e2e-upgrade-hdybmx",
  "location": "westeurope",
  "managedBy": null,
  "name": "ci-1957-e2e-upgrade-hdybmx",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "now": "1569147483",
    "ttl": "4h"
  },
  "type": null
}
```

It might be worth adding a check in `fakerp.EnsureResourceGroup` to ensure that the group's `properties.ProvisioningState` is equal to `Succeeded` before considering the group as created and ready for use

**Comment by ehashman** [comment]
Just saw this again: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2031/pull-ci-azure-master-upgrade-v7.1/329/build-log.txt

I don't think this is fully fixed.

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2001/pull-ci-azure-master-upgrade-v7.1/330

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2122/pull-ci-azure-master-upgrade-v7.1/542/build-log.txt #2122

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2101/pull-ci-azure-master-upgrade-v7.1/587/build-log.txt in https://github.com/openshift/openshift-azure/pull/2101
