### ISSUE TITLE
Timeout waiting to validate stateful test app in e2e runs

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1643]
Found a flake with the following error signature:

```

• Failure [162.252 seconds]
Openshift on Azure end user e2e tests [EndUser][Fake][EveryPR]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:12
  should create and validate test apps [EndUser][Fake][Apps] [It]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:13

  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "validateStatefulApp",
              Err: {
                  s: "timed out waiting for the condition",
              },
          },
      ]
  to be empty

  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:25
```

/kind test-flake

**Comment by charlesakalugwu** [comment]
#1642 e2e-create

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-e2e-create/192/build-log.txt

**Comment by charlesakalugwu** [comment]
#1633 e2e-create
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1633/pull-ci-azure-master-e2e-create/193/build-log.txt

**Comment by ehashman** [comment]
#1664 e2e-create https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1664/pull-ci-azure-master-e2e-create/230/build-log.txt

**Comment by Makdaam** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1675/pull-ci-azure-master-e2e-create/270 in #1675

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1776/pull-ci-azure-master-e2e-create/504/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1787/pull-ci-azure-master-upgrade-v5.2/199/build-log.txt in #1787

**Comment by ehashman** [comment]
/reopen
/remove-lifecycle rotten

Seen in #2240.
