### ISSUE TITLE
Timeout in e2e sanity check - checkCanCreateLB

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1695]
Caught a flake with the following signature

```
• Failure [1374.652 seconds]
Scale Up/Down E2E tests [ScaleUpDown][Fake][EveryPR][LongRunning]
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/scaleupdown.go:27
  should be possible to maintain a healthy cluster after scaling it out and in [It]
  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/scaleupdown.go:84

  Expected
      <[]*standard.TestError | len:1, cap:1>: [
          {
              Bucket: "checkCanCreateLB",
              Err: {
                  s: "timed out waiting for the condition",
              },
          },
      ]
  to be empty

  /home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/scaleupdown.go:81
```

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1694/pull-ci-azure-master-e2e-create/305/build-log.txt

/kind test-flake

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-e2e-create/510/build-log.txt in #1781

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1806/pull-ci-azure-master-upgrade-v5.1/454/build-log.txt #1806

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1810/pull-ci-azure-master-upgrade-v5.1/453/build-log.txt #1810
