### ISSUE TITLE
server misbehaving error during e2e tests

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1696]
Caught a flake with the following signature:

```
400 Bad Request: Failed to apply request: UpdateMasterAgentPoolWaitForReady: Get https://gnyasnyqgwdioaeedkks.westeurope.cloudapp.azure.com/api/v1/nodes/master-000002: dial tcp: lookup gnyasnyqgwdioaeedkks.westeurope.cloudapp.azure.com on 10.142.0.11:53: server misbehaving
```

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1682/pull-ci-azure-master-upgrade-v5.1/131/build-log.txt

/kind test-flake

**Comment by charlesakalugwu** [comment]
This also occured in the issue https://github.com/openshift/openshift-azure/issues/1544

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1491/pull-ci-openshift-openshift-azure-master-upgrade-v3.2/647

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2019/pull-ci-azure-release-v10-e2e-scaleupdown-v7.1/7/build-log.txt #2019

/remove-lifecycle rotten

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2123/pull-ci-azure-master-e2e-create-20191027-public/280/build-log.txt #2123
