### ISSUE TITLE
Verify Azure Disk fix in 3.11

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1702]
We need to verify if https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/azuredisk-issues.md#14-azure-disk-attachdetach-failure-mount-issue-io-error was backported into 3.11 and which release. If no - we need to engage appropriate teams for this to happen.

**Comment by kwoodson** [comment]
These were the PRs that were mentioned that addressed the azure disk issues:
https://github.com/kubernetes/kubernetes/pull/70568
https://github.com/kubernetes/kubernetes/pull/71377
https://github.com/kubernetes/kubernetes/pull/71495

As per our scrum discussion on 6/10/19, we should backport the cloud provider code to 3.11 which is being done here:

https://github.com/openshift/origin/pull/22742

**Comment by mjudeikis** [comment]
should be released with next errata
/close
