### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out[...]"

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#1710]
Getting the title error message when the e2e test is run some times, example:

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1709/pull-ci-azure-master-e2e-create/333/build-log.txt

/kind test-flake

**Comment by thekad** [comment]
Found openshift/release#378 but that wasn't helpful

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1876/pull-ci-azure-master-e2e-create/884

**Comment by asalkeld** [comment]
https://giedrius.blog/2018/10/25/gos-http-transport-and-408-response-code-whats-the-relationship/

**Comment by asalkeld** [comment]
I see we don't use the RoundTripper (which disables keepalives) in the sync pod. I'll post a PR that enables it.
