### ISSUE TITLE
Review imports and pin them in glide.yaml

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#173]
We import a bunch of libraries that we do not pin in glide.yaml. Use `go list -f '{{join .Imports "\n"}}' ./pkg/*` to figure them out and add them in glide.yaml.

@openshift/sig-azure

**Comment by kargakis** [comment]
So far we miss
```
github.com/ghodss/yaml
github.com/go-test/deep
github.com/satori/uuid
golang.org/x/crypto/bcrypt
golang.org/x/crypto/ssh
```

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/pull/184

**Comment by mjudeikis** [comment]
I think we can close as per the agreement that we do less with all this and try to be more flexible :)
