### ISSUE TITLE
newly created cluster is failing unit tests (run via make unit)

### ISSUE THREAD

**Issue by mgahagan73** [openshift/openshift-azure#1748]
github.com/openshift/openshift-azure/pkg/arm/v6 === RUN   TestDerivedMasterLBCNamePrefix
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestDerivedMasterLBCNamePrefix (0.00s)
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestDerivedMasterLBCNamePrefix (0.00s)
github.com/openshift/openshift-azure/pkg/arm/v6 PASS
github.com/openshift/openshift-azure/pkg/arm/v6 coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/arm/v6 ok      github.com/openshift/openshift-azure/pkg/arm/v6 0.068s  coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/arm/v6 ok      github.com/openshift/openshift-azure/pkg/arm/v6 0.068s  coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/arm/v6 ok      github.com/openshift/openshift-azure/pkg/arm/v6 0.068s  coverage: 50.8% of statements
2019/06/25 14:15:12 invalid character 'F' looking for beginning of value
make: *** [Makefile:76: unit] Error 1

Created using fakerp (make create) latest commit is 83ffede8e1bc

**Comment by ehashman** [comment]
Hmm, I just tested this against latest HEAD and can't reproduce.

```
ehashman@red-dot:~/go/src/github.com/openshift/openshift-azure$ make unit
...
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestHash (0.04s)
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestHash (0.04s)
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestHash (0.04s)
github.com/openshift/openshift-azure/pkg/arm/v6 === RUN   TestDerivedMasterLBCNamePrefix
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestDerivedMasterLBCNamePrefix (0.00s)
github.com/openshift/openshift-azure/pkg/arm/v6 --- PASS: TestDerivedMasterLBCNamePrefix (0.00s)
github.com/openshift/openshift-azure/pkg/arm/v6 PASS
github.com/openshift/openshift-azure/pkg/arm/v6 coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/arm/v6 ok  	github.com/openshift/openshift-azure/pkg/arm/v6	0.088s	coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/arm/v6 ok  	github.com/openshift/openshift-azure/pkg/arm/v6	0.088s	coverage: 50.8% of statements
github.com/openshift/openshift-azure/pkg/config ok  	github.com/openshift/openshift-azure/pkg/arm/v6	0.088s	coverage: 50.8% of statements
...
ehashman@red-dot:~/go/src/github.com/openshift/openshift-azure$ echo $?
0
ehashman@red-dot:~/go/src/github.com/openshift/openshift-azure$ git show --oneline 
bc7e427dc (HEAD -> master, upstream/master, upstream/HEAD, origin/master) Merge pull request #1671 from kwoodson/scap
```

Do you have any local unstaged changes that might involve the accidental insertion of an "F"? :)

**Comment by asalkeld** [comment]
Just a note: "make unit" is purely unit tests, they don't run against a cluster. If you want to run tests against the cluster then run "make e2e". The unit tests really have to work otherwise our CI would be broken and we couldn't merge anything... So this must be something local to you.

I just did
```
git checkout -f 83ffede
make unit
```
and that worked for me.

/close

@mgahagan73 if you still have trouble with this can you ask in slack #aos-azure?
