### ISSUE TITLE
move to internal FQDN for sync kubeconfig

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#175]
I think it would be more resilient to move to internal FQDN Loadbalancer for sync kubeconfig
https://github.com/openshift/openshift-azure/blob/master/pkg/config/generate.go#L406-L414

It gets created almost immediately, and in arm we already have this dependency form SS: 
` "[resourceId('Microsoft.Network/loadBalancers', 'lb-apiserver')]", `
In addition, if for some reason master0001 gets slower startup, it will impact the sync process. Never seen this for master1, but few times for master3 when it gets "late start to join cluster".

If we rotate master or take one out because of the "issues", sync process will get impacted too. So if we need to sync something meantime, we can't do it.

**Comment by kargakis** [comment]
How exactly is the sync process impacted if it runs in a deployment? An upgrade is going to roll masters first, then infra and compute nodes, then kick the sync process, or maybe move compute node upgrade in the end.

**Comment by mjudeikis** [comment]
Let's say MS has an issue with their infra, and master1 goes offline for few seconds/minutes. Or node gets not ready due to some storage issues. We cant run sync at this point.

**Comment by mjudeikis** [comment]
closed via sync running in pod
