### ISSUE TITLE
scale up/down timed out waiting for the condition

### ISSUE THREAD

**Issue by gburges** [openshift/openshift-azure#1775]
Looks like a new unhandled error

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1723/pull-ci-azure-master-e2e-create/465

/kind test-flake

**Comment by asalkeld** [comment]
scaling ss-infra-1569551297 capacity up from 2 to 3

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1977/pull-ci-azure-master-upgrade-v7.1/124

**Comment by Makdaam** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2128/pull-ci-azure-master-e2e-create-20191027-private/218
