### ISSUE TITLE
Sync e2e fails with unexpected log output

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#1778]
Caught a flake where the sync pod e2e test failed due to an expected entry not being found in the 
sync reconciliation logs.

artifacts: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1760/pull-ci-azure-master-e2e-create/479/build-log.txt

/kind test-flake

**Comment by charlesakalugwu** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1838/pull-ci-azure-master-e2e-create/767 in #1838

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-e2e-create/772/build-log.txt in #1836

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1863/pull-ci-azure-master-e2e-create/870/build-log.txt in #1863

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1871/pull-ci-azure-master-e2e-create/876/build-log.txt in #1871

**Comment by asalkeld** [comment]
All the errored clusters have 
```
time=\"2019-07-03T08:29:45Z\" level=debug msg=\"Service catalog api is aggregated\"
time=\"2019-07-03T08:29:45Z\" level=debug msg=\"applying sc resources\"
time=\"2019-07-03T08:29:45Z\" level=info msg=\"sync error: couldn't find kind ClusterServiceBroker\"
time=\"2019-07-03T08:31:58Z\" level=info msg=\"starting sync
```
sync then runs again and completes

**Comment by asalkeld** [comment]
So update on what is happening with this:

It always has updates in it, but the test only fails when there is an error as then there is one sync run.

This code below only works when the sync pod has done one run
https://github.com/openshift/openshift-azure/blob/master/test/e2e/specs/fakerp/sync.go#L27

If I change it to the below, it correctly fails all the time. (it can be seen by looking at the output that there are quite a lot of updates)
```go
		for _, run := range runs {
			Expect(run).To(Not(ContainSubstring("Update")))
		}
```

some examples of Updates

1. there are existing objects that get "owned-by-sync-pod" set first time.
```log
 msg="Update ClusterRole.rbac.authorization.k8s.io/system:controller:node-controller"
 msg="  unstructured.Unstructured{\n  \tObject: map[string]interface{}{\n  \t\t\"apiVersion\": 
bla bla
+ \"azure.openshift.io/owned-by-sync-pod\": string(\"true\"),
```
2. there are existing objects that get their values changed
```log
msg="Update ConfigMap/kube-system/extension-apiserver-authentication"
msg="  unstructured.Unstructured{\n  \tObject: map[string]interface{}{\n  \t\t\"apiVersion\": string(\"v1\"),\n  \t\t\"data\": map[string]interface{}{
- \"client-ca-file\": <stuff>,
+ \"client-ca-file\": <new stuff> 
```
other examples of this are rbac roles  like ClusterRole.rbac.authorization.k8s.io/admin

@jim-minter May I suggest that a better test would be to check that:
1. there are no errors
2. wait until there has been more than sync run and make sure that the second run onwards don't have updates.

**Comment by asalkeld** [comment]
also note if you check a cluster that has been running for a bit you will see this periodically:
```
  unstructured.Unstructured{
   Object: map[string]interface{}{
    ... // 6 identical entries
    "allowPrivilegedContainer": bool(true),
    "allowedCapabilities":      []interface{}{string("*")},
+   "allowedUnsafeSysctls":     []interface{}{string("*")},
    "apiVersion":               string("security.openshift.io/v1"),
    "defaultAddCapabilities":   nil,
    ... // 9 identical entries
    "seccompProfiles":    []interface{}{string("*")},
    "supplementalGroups": map[string]interface{}{"type": string("RunAsAny")},
    "users": []interface{}{
     ... // 2 identical elements
     string("system:serviceaccount:openshift-etcd:etcd-backup"),
     string("system:serviceaccount:openshift-azure-logging:log-analytics-agent"),
-    string("system:serviceaccount:kube-system:sync"),
    },
    "volumes": []interface{}{string("*")},
   },
  }
```

**Comment by asalkeld** [comment]
The above Update can be seen here:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1890/pull-ci-azure-master-e2e-create/928

**Comment by asalkeld** [comment]
so this is one place it is getting changed:
https://github.com/openshift/openshift-azure/blob/master/pkg/cluster/kubeclient/syncpod.go#L41

**Comment by asalkeld** [comment]
also this type https://github.com/openshift/openshift-azure/blob/master/vendor/github.com/openshift/api/security/v1/types.go#L23-L99 does not have UnsafeSyscalls so when the secrurity context is updated here https://github.com/openshift/openshift-azure/blob/master/pkg/cluster/kubeclient/syncpod.go#L32 it gets removed.

I might look if we need to update the vendored openshift to get that type.

**Comment by asalkeld** [comment]
I am having an awesome conversation with myself here..

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1963/pull-ci-azure-master-e2e-create/1156/build-log.txt in #1963 

Here, a configmap had to be updated
```
time="2019-09-22T13:36:58Z" level=info msg="Update ConfigMap/kube-system/extension-apiserver-authentication"
```

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1950/pull-ci-azure-master-e2e-create/1164/build-log.txt in #1963 

another update of `extension-apiserver-authentication`

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1998/pull-ci-azure-master-e2e-create-20190930/19

"Update ConfigMap/kube-system/extension-apiserver-authentication"
"Update ClusterRole.rbac.authorization.k8s.io/system:registry"

**Comment by ehashman** [comment]
Seeing        time="2019-11-27T19:49:05Z" level=info msg="Update ConfigMap/kube-system/extension-apiserver-authentication"  again

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2109/pull-ci-azure-master-e2e-create-20190430/236/build-log.txt #2109 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2107/pull-ci-azure-master-e2e-create-20191027-public/227/build-log.txt #2107

**Comment by olga-mir** [comment]
```
     time="2019-12-10T05:36:51Z" level=info msg="  unstructured.Unstructured{\n  \tObject: map[string]interface{}{\n  \t\t... // 20 identical entries\n  \t\t\"seccompProfiles\":    []interface{}{string(\"*\")},\n  \t\t\"supplementalGroups\": map[string]interface{}{\"type\": string(\"RunAsAny\")},\n  \t\t\"users\": []interface{}{\n  \t\t\t... // 3 identical elements\n  \t\t\tstring(\"system:serviceaccount:openshift-azure-logging:log-analytics-agent\"),\n  \t\t\tstring(\"system:serviceaccount:kube-system:sync\"),\n- \t\t\tstring(\"system:serviceaccount:e2e-test-e0r5s:default\"),\n  \t\t},\n  \t\t\"volumes\": []interface{}{string(\"*\")},\n  \t},\n  }\n"
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2129/pull-ci-azure-master-e2e-create-20191027-public/276/build-log.txt

**Comment by kwoodson** [comment]
Seeing this on #2235 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2235/pull-ci-azure-master-e2e-create-20191027-public/839/build-log.txt

```
 pod tests [EveryPR] [It] should not continuously update objects 
/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/sync.go:38

      time="2020-02-25T16:20:32Z" level=info msg="Update ConfigMap/kube-system/extension-apiserver-authentication"

```

**Comment by kwoodson** [comment]
Has happened multiple times here:
```
      time="2020-02-25T18:24:18Z" level=info msg="Update ConfigMap/kube-system/extension-apiserver-authentication"

      time="2020-02-25T18:24:24Z" level=info msg="Update ClusterRole.rbac.authorization.k8s.io/system:registry"

      time="2020-02-25T18:24:24Z" level=info msg="Update Role.rbac.authorization.k8s.io/kube-system/extension-apiserver-authentication-reader"
```

**Comment by ehashman** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2263/pull-ci-azure-master-e2e-create-20190430/656#1:build-log.txt%3A454 #2263 

When I see this flake, it's usually because there are still some updates on the first run. I wonder if we should allow failures on both the 0th and 1st run...

**Comment by ehashman** [comment]
Seen in #2272
