### ISSUE TITLE
API Whitelisting Implementation

### ISSUE THREAD

**Issue by julienstroheker** [openshift/openshift-azure#1808]
Currently, the ARO API server is an FQDN backed by a public IP address. Customers have no way to limit network access to that server. We need to offer the ability to lock down the API server endpoint to a list of network ranges specified by the customer. 

The main idea is to customize the NSG applied against the master nodes. 
3 New rules need to be set : 

|Name|Priority|Source|
|-|-|-|
|Internal_Services|1000|RP+BBM+etc..|
|Cluster_Services|2000|ip_outbound+any internal cluster ips...|
|Customer_Services|3000|CIDRs passed by the customer|

> Name is important to be discussed here since this could be used by external services to update some of them.

Here are the changes needed to enable this feature : 

### Network profile struct : 

An `AuthorizedCIDRs` field will be added : 

```
// NetworkProfile contains configuration for OpenShift networking.
type NetworkProfile struct {
	VnetCIDR *string `json:"vnetCidr,omitempty"`
	VnetID *string `json:"vnetId,omitempty"`
	PeerVnetID *string `json:"peerVnetId,omitempty"`
...
	// AuthorizedCIDRs (in, optional): Customer CIDRs used to reach the API Server
	AuthorizedCIDRs *[]string `json:"authorizedCIDRs,omitempty"`
}
```

### [Network profile struct](https://github.com/openshift/openshift-azure/blob/decb8388c33e4aa4f2f6e33d81d6588ebe96ba6b/pkg/api/types.go#L101)

Adding an `AuthorizedCIDRs` field

```
// NetworkProfile contains configuration for OpenShift networking.
type NetworkProfile struct {
	VnetCIDR string `json:"vnetCidr,omitempty"`
	VnetID string `json:"vnetId,omitempty"`
	PeerVnetID *string `json:"peerVnetId,omitempty"`
...
	// AuthorizedCIDRs (in, optional): Customer CIDRs used to reach the API Server
	AuthorizedCIDRs *[]string `json:"authorizedCIDRs,omitempty"`
}
```

### [Config Struct](https://github.com/openshift/openshift-azure/blob/decb8388c33e4aa4f2f6e33d81d6588ebe96ba6b/pkg/api/config.go#L12)

Adding an `InternalServicesCIDRs` field

```
// Config holds the cluster config structure
type Config struct {
	// SecurityPatchPackages defines a list of rpm packages that fix security issues
	SecurityPatchPackages []string `json:"securityPatchPackages,omitempty"`
...
	// SSH to system nodes allowed IP ranges
	SSHSourceAddressPrefixes []string `json:"sshSourceAddressPrefixes,omitempty"`
	// InternalServicesCIDRs defines allowed internal CIDRs to talk to API server such as BBM, RP, etc...
	InternalServicesCIDRs []string `json:"internalServicesCIDRs,omitempty"`
```

> I'll let you define how the cluster service rule will be applied since this logic can be handled by the plugin at 100%. 

cc @jim-minter @ehashman @amanohar

**Comment by ehashman** [comment]
I think I commented on this previously, but wanted to draw attention to this on here as well. This section is inconsistent:

```
	// SSH to system nodes allowed IP ranges
	SSHSourceAddressPrefixes []string `json:"sshSourceAddressPrefixes,omitempty"`
	// InternalServicesCIDRs defines allowed internal CIDRs to talk to API server such as BBM, RP, etc...
	InternalServicesCIDRs []string `json:"internalServicesCIDRs,omitempty"`
```

I believe that the `SSHSourceAddressPrefixes` uses CIDRs and not just prefixes as well? For consistency, can we call the new field `APIServiceSourceAddressPrefixes` or something similar and better document the permitted values?

**Comment by tonche** [comment]
From logical side, it is not a big deal to change the name to APIServiceSourceAddressPrefixes or other suitable names. However, as this name has already been used by current product from the code, It would be at least two steps to be compatible and safer with the deployed clusters. 
In first step, plugin add the new field name parallel to the existing SSHSourceAddressPrefixes, and ARO API set the same string set to both old and new fields. 
After all old clusters get updated with the new field name and work well, then we can submit a new PR to remove the existing SSHSourceAddressPrefixes field from ARO API and plugin code in order.

**Comment by mjudeikis** [comment]
@ehashman considering we changing the direction, can we close?

**Comment by ehashman** [comment]
Yes, as we are no longer pursuing IP whitelisting as a stop gap for private clusters, I will close.
