### ISSUE TITLE
Plugin scripts/VM CSE should return error number or code instead of generic strings for better bucketization

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#1823]
CSE scripts can fail for a variety of reason outside of script's control regardless of retries. Some examples: network connectivity, download error etc. 

One specific e.g.:  https://github.com/openshift/openshift-azure/pull/1787/files#diff-434fc6ac2244ae6f5e84f69aa26eb0ceR49-R53 where a generic error string is being returned ` ARO security updates installation failed` .

In addition to error string plugin should return error code (int) that can then be used by the RP to convert to specific error code for better visibility into why the script failed and thus the operation failed. E.g. message from the script can include in the error string: `exit status=([0-9]+)` and RP can parse it with: 
`errorMessageRegex = regexp.MustCompile(([0-9]+))` and convert to an error code for better visibility into what cause the failure instead of digging into CSE logs that are typically only on the VM.

Edit below on August 11 summarizing email conversation with Mikalai to set more context on requirements:
Live site investigations are accelerated if CSE returns error codes for granular error bucketization to the extent possible so that engineers don't have to dig through logs of each operation to understand why/where something failed. Plus it helps them understand what is potentially the biggest root cause of failing CSE scripts e.g. one week it could be failing to download docker bits and another week it could be an Azure network issue. 

- To start with CSE can return specific exit codes at various potential failure points.
- Overall it makes sense to have internal timeouts on all sub steps and fail them with specific error code instead of VMSS time outing a CSE run that is then forced to exit without any detail on what step was taking a long time. Without this investigation become significantly harder.

**Comment by asalkeld** [comment]
also see https://github.com/openshift/openshift-azure/pull/1875

**Comment by ehashman** [comment]
@amanohar given that this issue is 3.11-specific and we're basically done with feature dev for 3.x, should we close this?
