### ISSUE TITLE
can't update latched PackageRepository key/cert

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1828]
Scenario: a v6 cluster is created.  During the process, pkg/api/plugin.ToInternal() is called to initialise the configured PackageRepository key/cert in the internal cluster model.  Subsequently that cert expires.  There's currently no way to update the key/cert in the internal cluster model.

I think that originally we had planned for a Geneva Action to handle this use case, along with rotation of Geneva Logging/Metrics client certificates.  At the moment that action does not exist and creating it is somewhat heavyweight.

A simpler mechanism would be to hook the already existing mechanism by which we administratively upgrade clusters, i.e. by PUTting `config.pluginVersion: latest` in the admin API, and cause that to re-read the keys/certs.  I think this boils down to adding `|| setVersionFields` to each of the if statements in https://github.com/openshift/openshift-azure/blob/83d6b27a6e8fa5fb8ae4760322169c2a88f4181c/pkg/api/plugin/convertertointernal.go#L95-L112 .

This trick should only be necessary for configuration items not exposed by the admin API, i.e. keys/certs and secrets.  As such it is also worth considering the if statements in https://github.com/openshift/openshift-azure/blob/83d6b27a6e8fa5fb8ae4760322169c2a88f4181c/pkg/api/plugin/convertertointernal.go#L140-L145 .

Comments in the code + unit test also needed.

As all of this is part of the internal admin specification, it can always be changed later.

cc @ehashman

**Comment by asalkeld** [comment]
I'll get on this today
