### ISSUE TITLE
InvalidApiVersionParameter on fakeRP cluster create

### ISSUE THREAD

**Issue by gburges** [openshift/openshift-azure#1832]
```
FATA[2019-08-06T16:22:29+02:00] containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: "400 Bad Request: Failed to apply request: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"InvalidApiVersionParameter\" Message=\"The api-version '2015-07-01' is invalid. The supported versions are '2019-07-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-" error: json: cannot unmarshal number into Go value of type azure.RequestError 
exit status 1
signal: terminated
```

**Comment by gburges** [comment]
full log

./hack/create.sh $RESOURCEGROUP
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
INFO[2019-08-06T16:22:09+02:00] using region westeurope                      
INFO[2019-08-06T16:22:09+02:00] ensuring resource group gabortest            
INFO[2019-08-06T16:22:11+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/cmd/fakerp/main.go:20 main.main() starting the fake resource provider          
INFO[2019-08-06T16:22:11+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/plugin/plugin.go:86 github.com/openshift/openshift-azure/pkg/plugin.(*plugin).ValidatePluginTemplate() validating external plugin api data models   
INFO[2019-08-06T16:22:11+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/server.go:69 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).Run() starting server on localhost:8080            
INFO[2019-08-06T16:22:12+02:00] creating/updating cluster                    
DEBU[2019-08-06T16:22:12+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:15 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1() starting: PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/gabortest/providers/Microsoft.ContainerService/openShiftManagedClusters/gabortest?api-version=2019-04-30 
INFO[2019-08-06T16:22:12+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/customer_handlers.go:73 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handlePut() read request and convert to internal         
INFO[2019-08-06T16:22:12+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:129 github.com/openshift/openshift-azure/pkg/fakerp.createOrUpdateWrapper() enrich                                       
INFO[2019-08-06T16:22:12+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:140 github.com/openshift/openshift-azure/pkg/fakerp.createOrUpdateWrapper() setting up service principals                
DEBU[2019-08-06T16:22:12+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/aad.go:66 github.com/openshift/openshift-azure/pkg/fakerp.(*aadManager).ensureApp() create aad app auto-1565101332-gabortest-master 
DEBU[2019-08-06T16:22:29+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/util.go:24 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).badRequest() 400 Bad Request: Failed to apply request: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2015-07-01' is invalid. The supported versions are '2019-07-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." 
DEBU[2019-08-06T16:22:29+02:00]/home/gburges/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:17 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1() ending:   PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/gabortest/providers/Microsoft.ContainerService/openShiftManagedClusters/gabortest?api-version=2019-04-30 
FATA[2019-08-06T16:22:29+02:00] containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: error response cannot be parsed: "400 Bad Request: Failed to apply request: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"InvalidApiVersionParameter\" Message=\"The api-version '2015-07-01' is invalid. The supported versions are '2019-07-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-" error: json: cannot unmarshal number into Go value of type azure.RequestError 
exit status 1
signal: terminated

**Comment by ehashman** [comment]
I am not able to reproduce; might be a REST API rollout issue.

```
ehashman@red-dot:~/go/src/github.com/openshift/openshift-azure$ make create
./hack/create.sh ehashman-test
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
bindata.go
INFO[2019-08-06T08:20:42-07:00] using region westeurope                      
INFO[2019-08-06T08:20:42-07:00] ensuring resource group ehashman-test        
INFO[2019-08-06T08:20:44-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/cmd/fakerp/main.go:20 main.main() starting the fake resource provider          
INFO[2019-08-06T08:20:44-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/plugin/plugin.go:86 github.com/openshift/openshift-azure/pkg/plugin.(*plugin).ValidatePluginTemplate() validating external plugin api data models   
INFO[2019-08-06T08:20:44-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/server.go:69 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).Run() starting server on localhost:8080            
INFO[2019-08-06T08:21:15-07:00] creating/updating cluster                    
DEBU[2019-08-06T08:21:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/middleware.go:15 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).logger.func1() starting: PUT /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ehashman-test/providers/Microsoft.ContainerService/openShiftManagedClusters/ehashman-test?api-version=2019-04-30 
INFO[2019-08-06T08:21:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/customer_handlers.go:73 github.com/openshift/openshift-azure/pkg/fakerp.(*Server).handlePut() read request and convert to internal         
INFO[2019-08-06T08:21:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:129 github.com/openshift/openshift-azure/pkg/fakerp.createOrUpdateWrapper() enrich                                       
INFO[2019-08-06T08:21:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:140 github.com/openshift/openshift-azure/pkg/fakerp.createOrUpdateWrapper() setting up service principals                
DEBU[2019-08-06T08:21:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/aad.go:66 github.com/openshift/openshift-azure/pkg/fakerp.(*aadManager).ensureApp() create aad app auto-1565104875-ehashman-test-master 
DEBU[2019-08-06T08:22:15-07:00]/home/ehashman/go/src/github.com/openshift/openshift-azure/pkg/fakerp/aad.go:66 github.com/openshift/openshift-azure/pkg/fakerp.(*aadManager).ensureApp() create aad app auto-1565104875-ehashman-test-worker 
```

/kind bug

**Comment by mjudeikis** [comment]
reopen if needed
