### ISSUE TITLE
sync pod test "should not continuously update objects" fails

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#1839]
Hadn't seen this error before, not sure if transient in #1838 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1838/pull-ci-azure-master-e2e-create/767

**Comment by m1kola** [comment]
Seen it in #1836 

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1836/pull-ci-azure-master-e2e-create/772/build-log.txt

**Comment by charlesakalugwu** [comment]
this is a duplicate of #1778 
/close
