### ISSUE TITLE
update the azure monitoring agent

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#2025]
There is a new version of the agent https://github.com/microsoft/OMS-docker/blob/ci_feature_prod/Kubernetes/omsagent.yaml.

/assign
/cc @ehashman

**Comment by olga-mir** [comment]
/assign

we have upgraded to version `ciprod10182019`, but a newer `ciprod11012019` is available and we should upgrade

**Comment by olga-mir** [comment]
This is delivered now. 
https://github.com/openshift/openshift-azure/pull/2052
https://github.com/openshift/openshift-azure/pull/2077

/close
