### ISSUE TITLE
Can't access *real* private RH registry images

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#2039]
There is an E2E test that pulls an image from registry.redhat.io and spins up a deployment. This succeeds but this (redis) image can apparently be downloaded without any authentication (like quite a few of the images in the registry). Trying an image that does not support unauthenticated pulling (e.g. rocket chat) fails.
Need to a) make the e2e point to a real private image and b) fix it to pull the private image

**Comment by thekad** [comment]
The documentation https://docs.openshift.com/aro/architecture/infrastructure_components/image_registry.html#authentication seems to be a copy-paste from openshift dedicated, the docs do not match our setup.
Additionally, @jim-minter I believe the goal in ARO was to avoid the setup described in those docs and let clusters be able to transparently pull _any_ image from the RH registry, is my recollection correct?

**Comment by jim-minter** [comment]
@thekad please paste the full docker link to the image

**Comment by thekad** [comment]
https://access.redhat.com/containers/?tab=images#/registry.connect.redhat.com/rocketchat/rocketchat-apb

**Comment by jim-minter** [comment]
registry.connect.redhat.com is a registry I have never heard of - we will not have creds for this baked into the VM

**Comment by jim-minter** [comment]
don't know if we should or not

**Comment by thekad** [comment]
oh! I mistook it for an alias for registry.redhat.io then. Interestingly, *most* of the images there match the namespaces in registry.redhat.io so that just added to the confusion (I could e.g. `docker pull registry.redhat.io/ansible-tower-34/ansible-tower` which appears in that same registry)
