### ISSUE TITLE
Allow configuration of CIDRs

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-azure#204]
port from https://github.com/openshift/openshift-azure/issues/148 

Additionally, recommend adding `NetworkProfile` section to the public API model for supporting custom VNET. Documentation for AKS custom VNET: https://docs.microsoft.com/en-us/azure/aks/networking-overview

```
type NetworkProfile struct {
	NetworkPlugin    NetworkPlugin `json:"networkPlugin,omitempty"`
	NetworkPolicy    NetworkPolicy `json:"networkPolicy,omitempty"`
	PodCidr          string        `json:"podCidr,omitempty"`
	ServiceCidr      string        `json:"serviceCidr,omitempty"`
	DNSServiceIP     string        `json:"dnsServiceIP,omitempty"`
	DockerBridgeCidr string        `json:"dockerBridgeCidr,omitempty"`
}
```

`NetworkPlugin` can default to `kubenet`. And Azure CNI can be added later.

**Kubernetes Pod CIDR** (sometimes cluster-cidr): Address range managed by a Kubernetes cluster used to assign IP addresses to customer Pods. 
When an overlay network, for example, Kubenet, is used, this address range is given by customer. The range does not have to live within the VNET but it should not collide with the subnet used for cluster nodes to avoid traffic mis-routing.

**Kubernetes Service CIDR:** Address range used to allocate IP addresses for Kubernetes cluster Services. This range does not need to live within the containing VNET. Validation is also required to make sure there is no collision with address ranges defined in node and pod CIDR. It also is not usually directly routable by VMs that are not participating in the Kubernetes cluster. 

**Docker Bridge**: Address range used inside the docker bridge interfaces. This range defaults to 172.17.0.0/16 and need only be changed if the customer is using an overlapping/conflicting subnet within their larger VNET. 

cc: @qike-ms @pweil-  @jim-minter 

/kind feature

**Comment by mjudeikis** [comment]
@pweil- @jim-minter whats priority on this one?

**Comment by kargakis** [comment]
Closing in favor of https://jira.coreos.com/browse/AZURE-215
