### ISSUE TITLE
remove dep https://github.com/go-test/deep

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#206]
`k8s.io/apimachinery/pkg/equality.Semantic.DeepEqual` and `k8s.io/apimachinery/pkg/util/diff.ObjectGoPrintDiff` should be used instead of https://github.com/go-test/deep

**Comment by kargakis** [comment]
More like cleanup

**Comment by mjudeikis** [comment]
close in favor of AZURE-151
