### ISSUE TITLE
Can `GetPrivateAPIServerIPAddress` be run part as the GenerateConfig plugin function ?

### ISSUE THREAD

**Issue by julienstroheker** [openshift/openshift-azure#2086]
Today `GetPrivateAPIServerIPAddress` is a helper function that needs to be called from the RP.

Since the IP is set during the ARM template generation by the plugin and not really needed in the RP, this can be called automatically as part of the `GenerateConfig` function.

Thanks

**Comment by asalkeld** [comment]
Hi @julienstroheker 

Can you look at this: https://github.com/openshift/openshift-azure/blob/master/pkg/fakerp/fakerp.go#L204-L287
In the above the order is :
Validate()
stuff...
Validate()
GenerateConfig()
If we move this to GenerateConfig() it will never get validated. That *might* be ok as we are generating the IP, but I think it is sub-optimal. wdt @jim-minter ?

**Comment by jim-minter** [comment]
@asalkeld Just spoken to Julien -
The IP won't be used on the front end.
On the backend, validate(false) is called, then generateconfig().
Looking at your PR now.
