### ISSUE TITLE
Validation on external datamodel expects OpenShift Config params

### ISSUE THREAD

**Issue by shrutir25** [openshift/openshift-azure#209]
The Validate function at https://github.com/openshift/openshift-azure/blob/master/cmd/createorupdate/createorupdate.go#L58 expects OpenShift Config params such as FQDN, DNS (as part of Router Config) to be present. These params get filled up only in the backend async operation, so this function then will error out when used to validate the input external data model in the front-end operation.

**Comment by pweil-** [comment]
PTAL at https://github.com/openshift/openshift-azure/pull/210.  Let me know if there is anything else causing trouble :smile:
