### ISSUE TITLE
PUT Admin UTs failing in RP when RefreshCluster=false

### ISSUE THREAD

**Issue by julienstroheker** [openshift/openshift-azure#2092]
Running ValidateAdmin in our Unit test with `RefreshCluster=false` is failing with `azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request...`

Looks like `checkIfClusterWillRefresh` function is running `GetNameserversFromVnet` using authorizer passed via context.

https://github.com/openshift/openshift-azure/blob/4a9c38ea84b37c7762981653cdecae3b81a62c33/pkg/plugin/plugin.go#L268

```golang
clusterUpgrader, err := p.upgraderFactory(ctx, p.log, cs, false, true, p.testConfig)
	if err != nil {
		return err
	}
	ns, err := clusterUpgrader.GetNameserversFromVnet(ctx, p.log, cs.Properties.AzProfile.SubscriptionID, cs.Properties.AzProfile.ResourceGroup)
	if err != nil {
		return err
	}
```

What will be the best way for us to fake/mock `clusterUpgrader` ? 
I also tried using a `NewPlugin` with :

```golang
TestConfig{
		RunningUnderTest: true,
}
```

But same issue.
Thanks

**Comment by asalkeld** [comment]
Hi @julienstroheker 

It depends what you are trying to test. We do this in 2 places:
In plugin_test.go look at https://github.com/openshift/openshift-azure/blob/master/pkg/plugin/plugin_test.go#L402-L546
in the above we are using the mock updater.
Hard to know how to help without seeing your code, but that would if you are testing validation.
