### ISSUE TITLE
Move log-analytics deployment from infra to compute

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#2119]
https://github.com/openshift/openshift-azure/blob/master/pkg/sync/v14/data/Deployment.apps/openshift-azure-logging/log-analytics-cluster-agent.yaml#L90

/assign @olga-mir 

This is so that the node agent can monitor the cluster-agent

**Comment by olga-mir** [comment]
I've passed on a cluster for validation, once confirmed that it achieves the goal I'll put the PR up.

**Comment by olga-mir** [comment]
PR has been merged
/close
