### ISSUE TITLE
Bring config bundles back

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#212]
The master script size is getting out of hand when processed (eg. see https://github.com/openshift/openshift-azure/pull/189#issuecomment-413471035). One solution is to bring the config bundles back, tar containerservice.yaml, templatize, untar inside the template, use.

@openshift/sig-azure

**Comment by jim-minter** [comment]
we've now got the central storage account in place - having a new container which runs on the nodes to sync config correctly may be an alternative next step worth considering.  Having careful reliability here may be key for speeding up our upgrade times.

**Comment by kargakis** [comment]
Not sure this is an issue anymore, please reopen if you think so.
