### ISSUE TITLE
"failed to wait for default service account: timed out waiting for the condition" flake

### ISSUE THREAD

**Issue by ehashman** [openshift/openshift-azure#2136]
```
 time="2019-12-11T13:31:03Z" level=error msg="failed to wait for default service account: timed out waiting for the condition" func="github.com/openshift/openshift-azure/test/e2e/standard.(*SanityChecker).ValidateCluster" file="/home/prow/go/src/github.com/openshift/openshift-azure/test/e2e/standard/sanitychecker.go:168" 
```

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2128/pull-ci-azure-master-e2e-create-20191027-private/234/build-log.txt #2128 
/kind test-flake

**Comment by olga-mir** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2133/pull-ci-azure-master-upgrade-v7.1/630/build-log.txt
