### ISSUE TITLE
Potential DNS mismatch between agent nodes

### ISSUE THREAD

**Issue by JackQuincy** [openshift/openshift-azure#2144]
After a DNS settings update on the vnet. The vms need to be restarted to take the update. A user can scale the cluster with out using refresh cluster. The new vm will have the new dns settings while the rest of the cluster will have the old settings. Creating potential for inconsistent behavior in apps depending on which node they land on. If the dns settings have changed. All scale operations should be blocked until a refresh cluster has gone through.

**Comment by asalkeld** [comment]
The reason for this is that this condition https://github.com/openshift/openshift-azure/blob/master/pkg/plugin/plugin.go#L81 is only hitting for admin updates and not user updates
```
if !externalOnly && old != nil {
		if err := p.checkIfClusterWillRefresh(ctx, new); err != nil {
			errs = append(errs, err)
		}
	}
```

The first validate 
https://github.com/openshift/openshift-azure/blob/master/pkg/fakerp/fakerp.go#L204
The second validate
https://github.com/openshift/openshift-azure/blob/master/pkg/fakerp/fakerp.go#L273

I think we need to remove the check for externalOnly as it's more important to know that it is an update.
wdyt @jim-minter
