### ISSUE TITLE
Is it possible to build/test this as a non-AOS contributor?

### ISSUE THREAD

**Issue by lee0c** [openshift/openshift-azure#2174]
I'm attempting to test out the new metric server feature added by @olga-mir (thank you!) to check that it will meet a customer use case. Is it possible to use the scripts provided to test the current master branch? I'm running into issues and questions around the contents of secrets that are gained from the CI, and what some of the values in the env file that are normally set by the CI are.

If there's just no way to test this without CI server access, that's ok - I just want to confirm since it's hard to be sure if there is a workaround or not quickly.

**Comment by olga-mir** [comment]
Hi @lee0c, there is no way to bypass the CI server access. 
Is there a specific concern or question that I can help you with? Otherwise we would have to wait until the release.

**Comment by lee0c** [comment]
Hi @olga-mir, I was hoping to work with it early just to ensure that our team working with the customer would not run into any snags and could get going fast. We will just wait until release :) I'll close this issue.
