### ISSUE TITLE
New AAD Applications failing validation due to not propagating yet

### ISSUE THREAD

**Issue by JackQuincy** [openshift/openshift-azure#2211]
New AAD Applications, like ones generated by our cli for the customer, are failing validation with errors like, 
{
  "code": "BadRequest",​
  "message": "An error has occurred in subscription <sub-id>, resourceGroup:<rg> request: [invalid properties.authProfile.identityProviders[\"Azure AD\"]: could not authenticate: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier '<app-id>' was not found in the directory '<tenant-id>'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\\r\\nTrace ID: <trace-id>\\r\\nCorrelation ID: <correlation-id>\\r\\nTimestamp: 2020-02-06 12:15:19Z\",\"error_codes\":[700016],\"timestamp\":\"2020-02-06 12:15:19Z\",\"trace_id\":\"<trace-id>\",\"correlation_id\":\"<correlation-id>\",\"error_uri\":\"https://login.microsoftonline.com/error?code=700016\"}]."​
 }
Feels like we could retry this error to allow time for the app to propagate.

**Comment by asalkeld** [comment]
is this something that needs to be in the plugin validation, RP or the cli?
cc @ehashman @jim-minter

**Comment by Shuanglu** [comment]
may I know if there is any ETA about this ?

**Comment by ehashman** [comment]
Error source: https://github.com/openshift/openshift-azure/blob/f7d86b7f6c93fdda1751bf87dd44ad85ea1cf040/pkg/api/validate/api.go#L111-L113

Looks like this comes from... https://github.com/openshift/openshift-azure/blob/f71ae622d49d02b30e320026802b2e8dcf13307c/pkg/api/validate/serviceprincipal.go#L27-L51

I'll crib off how we do the retries in v4, like so https://github.com/Azure/ARO-RP/blob/0af036fcd242c116a15bfd3dc2f4ac01b9f64534/pkg/api/validate/openshiftcluster_validatedynamic.go#L95-L108
