### ISSUE TITLE
ACR Secret rotation errors in CI and fakeRP deployment - unauthorized: authentication required

### ISSUE THREAD

**Issue by grantomation** [openshift/openshift-azure#2245]
Get https://osarpint.azurecr.io/v2/openshift-on-azure/azure/manifests/v15.0: unauthorized: authentication required

Example: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2244/pull-ci-azure-master-upgrade-v15.0/10/build-log.txt

This is also affecting dev (fakeRP) deployments using release branches.
- "make secrets" has already been run.

**Comment by ehashman** [comment]
Here's another one in CI on #2246:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2246/pull-ci-azure-master-upgrade-v15.0/11

**Comment by ehashman** [comment]
@mjudeikis can we sync about this? This is blocking all upgrade tests in CI for 3.11.

/kind test-flake

**Comment by thekad** [comment]
I have reproduced this locally, and after another quick glance @ehashman discovered the user/appid encoded in the secret was mis-pasted and is missing 1 character. Just need to update the acr-docker-pull-secret secret object in the azure-private namespace

**Comment by ehashman** [comment]
Excellent, this is now working again as evidenced by the upgrade-v14.1 test on #2244. Closing.
