### ISSUE TITLE
Public IP limit of 20 frequently reached per region

### ISSUE THREAD

**Issue by ehashman** [openshift/openshift-azure#2252]
/kind test-flake

e.g. 
```
time="2020-03-10T16:57:57Z" level=warning msg="deployment failed: &azure.ServiceError{Code:\"DeploymentFailed\", Message:\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\", Target:(*string)(nil), Details:[]map[string]interface {}{map[string]interface {}{\"code\":\"BadRequest\", \"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"PublicIPCountLimitReached\\\",\\r\\n    \\\"message\\\": \\\"Cannot create more than 20 public IP addresses for this subscription in this region.\\\",\\r\\n    \\\"details\\\": []\\r\\n  }\\r\\n}\"}, map[string]interface {}{\"code\":\"BadRequest\", \"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"PublicIPCountLimitReached\\\",\\r\\n    \\\"message\\\": \\\"Cannot create more than 20 public IP addresses for this subscription in this region.\\\",\\r\\n    \\\"details\\\": []\\r\\n  }\\r\\n}\"}}, InnerError:map[string]interface {}(nil), AdditionalInfo:[]map[string]interface {}(nil)}" func="pkg/fakerp.GetDeployer.func1()" file="pkg/fakerp/fakerp.go:104"
```

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2246/pull-ci-azure-master-upgrade-v14.1/214/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2246/pull-ci-azure-master-upgrade-v15.0/25/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2246/pull-ci-azure-master-e2e-create-20191027-public/870/build-log.txt

**Comment by ehashman** [comment]
Above: #2246 

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2244/pull-ci-azure-master-e2e-create-20190430/631#1:build-log.txt%3A49

#2244

**Comment by ehashman** [comment]
/assign @Makdaam 

Leszek to request quota increase in australiasoutheast, eastus, eastus2, westeurope.

**Comment by Makdaam** [comment]
requests open in Azure Portal support.

**Comment by Makdaam** [comment]
Quotas for eastus, eastus2, australiasoutheast, westeurope to 100 publicIPs.

**Comment by ehashman** [comment]
Flakes seem to have gone away, closing. Thanks @Makdaam!
