### ISSUE TITLE
aro-admission-controller fails when running for a long time.

### ISSUE THREAD

**Issue by Makdaam** [openshift/openshift-azure#2287]
The following error messages show up in the log of aro-admission-controller (api server above get's Internal Server Error from aro-admission-controller). The issue occurs after the process is running for 3-4 weeks on a relatively busy cluster.

"error fetching namespace X required to preallocate values for restricted: Get https://clusterurl.region.cloudapp.azure.com/api/v1/namespaces/X: http2: no cached connection was available"

At first glance it seems to be a problem with the outbound connections not being released properly back into the pool.

This issue is to track progress on the investigation.

**Comment by Makdaam** [comment]
cc @jim-minter

**Comment by Makdaam** [comment]
Notes:
The http error comes from a securitycontextconstraints.CreateProviderFromConstraint call.
https://github.com/openshift/openshift-azure/blob/master/pkg/entrypoint/admissioncontroller/podwhitelist.go#L76
which gets the namespace via
https://github.com/openshift/openshift-azure/blob/master/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/namespace.go#L63
which uses client-go to request a resource
https://github.com/openshift/openshift-azure/blob/master/vendor/k8s.io/client-go/rest/request.go#L633

So https://github.com/openshift/openshift-azure/blob/master/vendor/k8s.io/client-go/rest/request.go#L720 should close the HTTP response Body every time.

I couldn't find any leaks by analysing the code. I'll generate load on it and look at golang perf analysis.

**Comment by ehashman** [comment]
I suspect this is an instance of https://github.com/golang/go/issues/22091.
