### ISSUE TITLE
uuid package revision

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#230]
Looks like we use an older version of `satori/go.uuid` internally (before the breaking api change for `err`). Which is giving this error:
```
vendor/github.com/openshift/openshift-azure/pkg/config/generate.go:479:37: assignment mismatch: 2 variables but 1 values
```

Would it be possible to use `f58768cc1a7a7e77a3bd49e98cdd21419399b6a3` revision of  `satori/go.uuid`? 

I believe only place this is used is when generating service catalog cluster id: https://github.com/openshift/openshift-azure/blob/master/pkg/config/generate.go#L479 

cc @mjudeikis

**Comment by mjudeikis** [comment]
@sozercan nice one :) 
Added it to this https://github.com/openshift/openshift-azure/pull/184
We gonna discuss it today and I hope to merge it soon.
