### ISSUE TITLE
Multiple upgrade failures 

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#2312]
We are seeing multiple upgrade failures, where in the SDK "looses" the VM.

Flow:
1. Cluster is created (any version).
2. Upgrade is initiated.
3. Deallocation of master0 succeeds
![Screenshot from 2020-06-25 10-08-29](https://user-images.githubusercontent.com/3225744/85691628-935ab380-b6cc-11ea-8e18-e1fd61cd7f0d.png)
4. SDK/Coded loses the VM and fail[1].
```
time="2020-06-25T09:07:28Z" level=fatal msg="400: 400 Bad Request: Failed to apply request: UpdateMasterAgentPoolReimage: compute.VirtualMachineScaleSetVMsClient#Reimage: Failure sending request: StatusCode=400 -- Original Error: Code=\"BadRequest\" Message=\"The VM Instance 0 in Virtual Machine Scale Set ss-master cannot be found.\"\n"
exit status 1
```

We end-up in state where master-0 is powered down and not responsive. 

1. https://gist.github.com/mjudeikis/d7ecde3f6692b9a5cceb5fd5f4fa5b22

**Comment by ehashman** [comment]
Microsoft has confirmed this was a regression in certain regions and is rolling out a hotfix.
