### ISSUE TITLE
migrate to dep

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#239]
acs-engine and RP use `dep` as dependency management. Should we move too? 

dep can update individual packages/dep and has more flexibility too.

**Comment by kargakis** [comment]
Or wait for go modules in 1.11?

https://github.com/golang/go/wiki/Modules

**Comment by mjudeikis** [comment]
@kargakis turn off the phone!

**Comment by charlesakalugwu** [comment]
+1 I use virtualgo for isolated golang workspaces and its got great integration with dep but unfortunately not glide.

**Comment by mjudeikis** [comment]
Close in favor of AZURE-150
