### ISSUE TITLE
potential flake: healthcheck: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#241]
+ go run cmd/createorupdate/createorupdate.go cmd/createorupdate/deploy.go cmd/createorupdate/update.go -loglevel=debug
time="2018-08-22T13:03:57Z" level=info msg="convert to internal" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:03:57Z" level=info msg=enrich resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:03:57Z" level=info msg="validating internal data models" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:03:57Z" level=info msg="generating configs" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:04:03Z" level=info msg="persist config" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:04:03Z" level=info msg="generating arm templates" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:04:03Z" level=info msg="write helpers" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:04:03Z" level=info msg="creating/updating deployment" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:04:06Z" level=info msg="waiting for deployment" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:05:05Z" level=info msg="saving cluster state to storage account" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:05:05Z" level=info msg="initializing cluster" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:05:06Z" level=info msg="starting health check" resourceGroup=ci-op-7z5xsflz-6cb1c
time="2018-08-22T13:05:07Z" level=fatal msg="Get https://ci-op-7z5xsflz-6cb1c.eastus.cloudapp.azure.com/healthz: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"openshift-signer\")"
exit status 1

**Comment by jim-minter** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/238/pull-ci-openshift-azure/385/

**Comment by mjudeikis** [comment]
This looks like certificate got regenerated in the process. Or this only one case?

**Comment by jim-minter** [comment]
no, it was on creation.  I don't understand why it happened - waiting to see if it happens again before trying to reason about it.

**Comment by mjudeikis** [comment]
I have seen similar flake where my storage account names in the config were different than sync plugin expected (old one).

**Comment by jim-minter** [comment]
Think that issue was fixde by #263?

**Comment by kargakis** [comment]
reopen if seen again
