### ISSUE TITLE
ci-operator lacks permissions

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#247]
When we merge AAD PR we need to bump our CI-operator RBAC to able to create SP:
```
+ set +x
ERROR: Directory permission is needed for the current user to register the application. For how to configure, please refer 'https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal'. Original error: Insufficient privileges to complete the operation.
ERROR: az ad sp create: error: argument --id: expected one argument
usage: az ad sp create [-h] [--verbose] [--debug]
                       [--output {tsv,table,json,jsonc,yaml}]
                       [--query JMESPATH] [--subscription _SUBSCRIPTION] --id
                       IDENTIFIER
+ cat
```
related to:
https://github.com/openshift/openshift-azure/pull/225/files

**Comment by mjudeikis** [comment]
on teardown: 
```
+ hack/dns.sh zone-delete mjudeikis-test5-ef260
+ hack/aad.sh app-delete openshift.mjudeikis-test5-ef260.osadev.cloud
ERROR: Insufficient privileges to complete the operation
```

**Comment by mjudeikis** [comment]
/assign jim-minter 
I dont have right to do anything
`ci-operator-jobs` - WebApp

**Comment by jim-minter** [comment]
I don't know if service principals can create service principals?  @sozercan can you help here?

**Comment by sozercan** [comment]
I believe we tested this scenario, SPNs can create other SPNs only if they have the proper AD role (we tested `Global Administrator` so far successfully, testing to find what is the least privileged role we can assign).

It is a little tricky to assign this:
send a `POST` to `https://graph.microsoft.com/beta/directoryroles/<role id>/members/$ref`
with body:
`{"@odata.id":"https://graph.microsoft.com/beta/servicePrincipals/<id of your spn>"}`

**Comment by jim-minter** [comment]
There's no way I'm giving Global Administrator to a SP.  If you find something more minimal, let me know ;-)

**Comment by mjudeikis** [comment]
This impacts our CI. We might need to discuss how we want to approach it...
