### ISSUE TITLE
use generated sync pod when testing cluster

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#250]
atm in our PR tests we don't appear to be using the sync pod generated by the codebase.  If #238 merges it provides for setting a SYNC_IMAGE env var to drive this.  If it doesn't, that functionality needs to be added.

Then the ci-operator config needs to be updated to set SYNC_IMAGE correctly

@mjudeikis or @kargakis please can you handle this?

**Comment by mjudeikis** [comment]
https://github.com/openshift/release/pull/1275
