### ISSUE TITLE
auto-specify number of infra nodes dependent on workload

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#253]
maybe also master vm size?

@pweil- I still feel doubtful about what should be specifiable in the external api representation wrt infra node counts - wdyt?

**Comment by pweil-** [comment]
I'm hesitant not to allow scaling of those nodes by the customer just because a lot of the infra service load are based on what is running on the cluster.  If we set up HA registry and they need more based on their use case how do they scale?

**Comment by pweil-** [comment]
(not saying we need to expose anything now, but need to think about that use case)

**Comment by mjudeikis** [comment]
We need to know "What is a big workload, and when to scale" first. No metrics no fun...

**Comment by jim-minter** [comment]
Need to decide how many infra nodes we deploy on a GA cluster

**Comment by mjudeikis** [comment]
I say 3. Which gives nice update pattern, aligns with most of ref architectures and gives as spare capacity/HA in case we fail on first node.

**Comment by mjudeikis** [comment]
@jim-minter are u looking into this?

**Comment by jim-minter** [comment]
set to 3, need to document this as part of the service limits/limitations - work with @patrickstrick
