### ISSUE TITLE
service catalog apiserver restarting

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#266]
SC apiserver, SC controllermanager and prometheus restarting regularly on master-built cluster

strace shows apiserver wilfully exits(0)
controller manager exits(1) - looks like because the apiserver connection went away
not sure about prometheus yet

**Comment by jim-minter** [comment]
I think the sync pod keeps editing the deployments, triggering a redeploy

**Comment by jim-minter** [comment]
the secret checksums are not stable across multiple invocations of sync, causing unwanted redeployments.

hack: added this to syncWorkloadsConfig:
```
```

**Comment by kargakis** [comment]
Looking

**Comment by kargakis** [comment]
Seems like an issue with the serving certs getting regenerated on every sync. For some reason, all services are updated on every sync and that seems to trigger regeneration of the serving certs which subsequently triggers redeployments of all services using serving certs (service catalog, prometheus).

**Comment by kwoodson** [comment]
I'm a bit naive on the situation here but according to @kargakis comments it appears that we are not completely idempotent when running the sync.  The sync process can/should be run often but only change when items are updated/modified in the manifests.  This will ensure less churn and we can guarantee our changes only happen when our data changes.

**Comment by kargakis** [comment]
We do not persist hashes for serving certs so there is a different issue that needs to be identified.

**Comment by kargakis** [comment]
We will need to sort keys in configmaps/secrets before we hash them.
