### ISSUE TITLE
sync process does not handle updates to config mounted on init containers

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#270]
/kind bug
/assign

@openshift/sig-azure

**Comment by kargakis** [comment]
Our docker registry mounts the registry config in its init container

**Comment by kwoodson** [comment]
Should we go back to fetching the storage account key inside of the sync.go process? Something similar to what I attempted here: https://github.com/openshift/openshift-azure/pull/170

**Comment by jim-minter** [comment]
Also saves having to worry about using an Azure az image - sounds well worth considering.

**Comment by kargakis** [comment]
This is not an issue after all since the sync process is using volumes to hash content which are shared between containers and initContainers. Also we removed the registry init container in #300.

/close
