### ISSUE TITLE
bootstrap autoapprover should run on master

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-azure#271]
This pod is considered infrastructure and I believe should run on our infrastructure nodes..

Suggested fix:

Add a node selector:
```
      nodeSelector:
        region: infra
```

**Comment by kargakis** [comment]
I think we need to run it on master nodes since you have a chicken-egg problem when you try to start it on an infra node (infra/compute nodes depend on the bootstrap autoapprover to run in order to check in)

**Comment by kwoodson** [comment]
I agree that it must run somewhere initially.  This was seen running on compute resource:
```
openshift-infra                     bootstrap-autoapprover-77d949775b-br2p2   1/1       Running   0          17m       10.128.4.4    compute-000000
```

**Comment by kargakis** [comment]
Yeap, needs to be constrained to run only on master nodes.
