### ISSUE TITLE
scale infra scale set to 2 nodes, scale core infra services to 2

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#286]
/assign @kwoodson 

@openshift/sig-azure 

"core services" here being the web console, router, and potentially the registry. Thoughts?

**Comment by kargakis** [comment]
Maybe we don't want to disable PDBs (https://github.com/openshift/openshift-azure/issues/284) because of this.

**Comment by kargakis** [comment]
> Maybe we don't want to disable PDBs (#284) because of this.

Though I think the fact that we are going to update nodes one by one will probably be enough.

**Comment by jim-minter** [comment]
+1

**Comment by kwoodson** [comment]
I'll take a look.
