### ISSUE TITLE
can't currently deploy OSA to subscriptions with old loganalytics pricing model

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#292]
sku pergb2018 is hard coded in arm template.  No easy way to autodetect.

https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-usage-and-estimated-costs

known limitation for PP.  Post-PP need to look at resolving this - RP could detect subscription type and fix out SKU, or could do a retry loop with different SKUs until success.

**Comment by jim-minter** [comment]
@amanohar @sozercan fyi

**Comment by sozercan** [comment]
@jimzim

**Comment by kargakis** [comment]
Loganalytics is no more part of openshift-azure so I assume this is not an issue anymore.
