### ISSUE TITLE
add azure disk for persistent components

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#303]
Registry, Prometheus, alert manager (and maybe few more of the components) are running with `emptyDir`:

```
     - emptyDir: {}
        name: registry-storage
      - emptyDir: {}
        name: shared-config
      - emptyDir: {}
        name: empty-dir
```

Need to move to PVC using azure disk where possible (RWM vs RWO)

**Comment by kargakis** [comment]
The registry is backed by Azure blob storage already

**Comment by mjudeikis** [comment]
Forgot we do direct integration...
Prometheus, alertmanager, nop :/

**Comment by kargakis** [comment]
Prometheus is a statefulset so in principle we can start using its PVC template.

**Comment by jim-minter** [comment]
docker-registry yaml needs tidying up (think both emptyDirs can just be removed?)
prometheus data definitely should be persisted

**Comment by kargakis** [comment]
Opened https://github.com/openshift/openshift-azure/pull/325 for cleaning up the registry empty directories. @legionus confirmed to me that we don't need to mount anything in `/registry` when cloud storage is used.
