### ISSUE TITLE
Web console uses 100% maxUnavailable

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#305]
Means during an upgrade of the deployment, we tolerate unavailability of the console.

@openshift/sig-azure any ideas why?

**Comment by pweil-** [comment]
https://github.com/openshift/openshift-ansible/pull/8694

**Comment by kargakis** [comment]
> Mismatched JS can cause errors because we don't have sticky sessions. (This is a non-issue in converged console next release since we have a route instead of a master proxy.)

To avoid this at all times we will have to set maxSurge to 0.

**Comment by kargakis** [comment]
Not sure how I managed to close this.

**Comment by kargakis** [comment]
Probably not something we care about a lot
