### ISSUE TITLE
x509: certificate signed by unknown authority in sync pod

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#307]
in the sync pod, @sozercan saw:

```
time="2018-08-30T06:14:21Z" level=info msg="Sync process started"
time="2018-08-30T06:14:22Z" level=info msg="found account fnr5uugfvzt6vyxwjsff0ebb"
time="2018-08-30T06:14:23Z" level=info msg="Error while syncing: cannot sync cluster config: Get https://sertacosatest29.eastus.cloudapp.azure.com/healthz: x509: certificate signed by unknown authority"
```

**Comment by jim-minter** [comment]
This happens because Properties.FQDN == Properties.PublicHostname == "sertacosatest29.eastus.cloudapp.azure.com".
Then the API server is configured to serve a special self-signed "console" certificate for the PublicHostname, and that is also served to internal clients who do API requests via the FQDN.  And that causes the sync pod to die in a heap.

**Comment by jim-minter** [comment]
@mjudeikis please can you pick this up as a priority first thing Friday morning?

**Comment by mjudeikis** [comment]
https://docs.openshift.com/container-platform/3.10/install_config/certificate_customization.html#configuring-custom-certificates documentation about expected behavior of named_certificates
