### ISSUE TITLE
Generate htpasswd when AAD is enabled

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#319]
Or at the very least, generate the password instead of hardcoding to `demo`.

@openshift/sig-azure thoughts?

**Comment by mjudeikis** [comment]
I think we agreed we need to generate one for now with intention we gonna remove it in the close future

**Comment by jim-minter** [comment]
+1 on generate

**Comment by mjudeikis** [comment]
@jim-minter if we generate it randomly. Its get stored in htpasswd format. Question is how we will know it? :D 
```
[mjudeiki@redhat openshift-azure]$ ./hack/config.sh get-config mjudeikis xxxxxxxxxxxx .config.HtPasswd
ZGVtbzokMmEkMTAkNEJxxxxxxxxxxxxxxxxxxxxxxxxxxSXV3NlBZSUpsQzlTUmp2NWNxbFc=
```
