### ISSUE TITLE
Need to tie RP vendoring to sync pod version

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#327]
This is critical to avoid mismatches in testing, and then in production
Longer term there will be a sync pod image per supported OSA release (e.g. at least sync-3.10, sync-3.11; maybe even sync-3.10.0, sync-3.10.1, ...). In the short term for PP we'll just start with one.

Proposal for now is:
1) on each commit, CI should build and push the sync pod tagged with the short commit ID.  Also tag :latest or :v310 or whatever.
2) plugin should accept a configurable indicating the short commit ID that should be used to pull. MSFT will set this up in the RP, based on the commit ID that they vendor at.
3) our fake RP/scaffolding can just default the configurable to :latest so that our CI works as expected

**Comment by jim-minter** [comment]
@openshift/sig-azure @amanohar FYI
@kargakis if I don't get to this today please could you look at this urgently on Wednesday?

**Comment by kargakis** [comment]
Pushing commits in their own tags in quay is going to be challenging. Today, we have two processes that comprise our sync image publishing process[1]: 

1. the [ci-operator postsubmit](https://github.com/openshift/release/blob/ba151f8f4a10aa0831d69a69eaa3e3c251f1e2f7/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-postsubmits.yaml#L16) which runs on every openshift-azure merged commit pushes the built image in an [imagestreamtag inside the CI cluster](https://github.com/openshift/release/blob/ba151f8f4a10aa0831d69a69eaa3e3c251f1e2f7/ci-operator/config/openshift/openshift-azure/master.json#L29).
2. a cronjob mirrors the imagestreamtag to [a set of static tags in quay](https://github.com/openshift/release/blob/ba151f8f4a10aa0831d69a69eaa3e3c251f1e2f7/projects/azure/image-mirror/image-mirror.yaml#L12) (atm `latest` and `v3.10`) on an hourly basis.

We could potentially mount quay credentials in the ci-operator job and try to shoehorn publishing to quay there but not sure how hacky it's going to be (cc @stevekuznetsov). It would be much easier to pin a certain commit that is vendored by the RP in a stable tag and publish that tag as an one-off but I believe we need an automated process for doing that whenever we want to. Thoughts?

[1] this mirrors how we publish images to quay and dockerhub elsewhere

**Comment by kargakis** [comment]
> plugin should accept a configurable indicating the short commit ID that should be used to pull. MSFT will set this up in the RP, based on the commit ID that they vendor at.

We already have `SYNC_IMAGE` to configure the sync image in the plugin. Is it something we can get rid of with this plugin function?

**Comment by kargakis** [comment]
> our fake RP/scaffolding can just default the configurable to :latest so that our CI works as expected

Our CI already uses `SYNC_IMAGE` to pull the correct version of the sync pod. We need to configure the whole pullspec to pull from the namespace that contains all PR artifacts.

**Comment by kargakis** [comment]
Instead of configuring to set the tag in the plugin API we may want to configure the whole pullspec and  get rid of `SYNC_IMAGE`.

**Comment by kargakis** [comment]
Or MSFT can `os.SetEnv("SYNC_IMAGE", "quay.io/openshift-on-azure:git_commit")` in the RP and call it a day :) We still need to fix publishing.

**Comment by kargakis** [comment]
> Instead of configuring the tag in the plugin API we may want to configure the whole pullspec and get rid of SYNC_IMAGE.

Opened https://github.com/openshift/openshift-azure/pull/339

**Comment by kargakis** [comment]
Opened https://github.com/openshift/openshift-azure/pull/343 as a stopgap solution until we figure out how to automate pushing images that use commit ids.
