### ISSUE TITLE
Make networking pods static pods, not daemonsets

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#331]
We already believe that doing this will improve startup performance.  Another key consideration is during major version upgrade: on upgrade from 3.10->3.11, a 3.11 node image would be spun up using 3.10 daemonset pods until the sync pod was re-enabled and ran.  This is possibly undesirable.

**Comment by jim-minter** [comment]
@openshift/sig-azure opinions on whether we should try to fix this pre-private preview?

**Comment by jim-minter** [comment]
(tagging private preview for now, might cancel that)

**Comment by kargakis** [comment]
We could avoid scheduling old daemonset pods on new images by adding the Openshift version as a node label and use the node selector in the daemonset but I also believe moving to static pods is probably better (should allow us to move the sync pod to run as a normal pod, thus avoid pinning it in master-00000 as it currently is).

**Comment by kargakis** [comment]
Also, a nice to have before PP.

**Comment by jim-minter** [comment]
A third reason for doing this is that it helps enable running the sync pod as a Deployment - cf #333

**Comment by pweil-** [comment]
status?

**Comment by jim-minter** [comment]
detagging from private preview, too risky now
