### ISSUE TITLE
Add basic configuration to plugin

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#332]
MSFT want to be able to change at least the VM image the plugin chooses to use without revendoring the plugin.  Need a mechanism to allow this to be specified, either via the plugin reading a config file, or by accepting configuration at plugin instantiation time.

**Comment by jim-minter** [comment]
@openshift/sig-azure

**Comment by charlesakalugwu** [comment]
@jim-minter @kargakis @mjudeikis  are we open to using something like viper here? This will allow us actually easily provide configurability for most options https://github.com/spf13/viper

**Comment by jim-minter** [comment]
Dependent on https://github.com/openshift/openshift-azure/pull/554

**Comment by kargakis** [comment]
@jim-minter @charlesakalugwu status on this issue?

**Comment by charlesakalugwu** [comment]
I'd like to deal with this after my current testing work.

**Comment by jim-minter** [comment]
As part of this work, need to fix the hack in https://github.com/openshift/openshift-azure/pull/837/commits/577e3977352e96104131e241317999e46a5a26f9 .

**Comment by jim-minter** [comment]
@mjudeikis as part of this work, also need to move EtcdBackupImage and 	AzureControllersImage out of TestConfig.  MSFT *MUST* set these to the commit version like they do the sync pod.  MetricsBridge must be tied as well (currently at least that is not in TestConfig).
