### ISSUE TITLE
should remove servicePrincipalProfile from external API

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#335]
the RP will create the master service principal (not the AAD one) on our behalf and will enrich it into the internal representation.  Therefore the external API servicePrincipalProfile and validation can be removed.

**Comment by jim-minter** [comment]
@openshift/sig-azure

**Comment by jim-minter** [comment]
@sozercan fyi

**Comment by mjudeikis** [comment]
@jim-minter @sozercan  validation happens after data is enriched and before conversion. I think we should keep the validation, no? Or now `enrich` function change its place?

**Comment by mjudeikis** [comment]
https://github.com/openshift/openshift-azure/pull/340

**Comment by jim-minter** [comment]
You should keep the validation but it should only validate when externalOnly is false.
@shrutir25 fyi
