### ISSUE TITLE
allow basic defaulting of some external api items

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#336]
At the moment, validation requires a routerprofile to be provided as input on cluster creation:
```
"routerProfiles": [
  {
    "name": "default"
  }
]
```

If the user is not providing a publicSubdomain it is a bit pointless to have to provide such a routerProfile - we could default that value appropriately.

**Comment by jim-minter** [comment]
@openshift/sig-azure

**Comment by jim-minter** [comment]
@sozercan thanks for raising!

**Comment by jim-minter** [comment]
we may want to delay this post private preview so that we look at adding appropriate defaulting logic across the board

**Comment by jim-minter** [comment]
another item that could be considered for defaulting is osType == Linux in agentpoolprofiles

**Comment by jim-minter** [comment]
another one is name == "infra" for the infra agentpoolprofile

**Comment by ehashman** [comment]
This PR should allow us to remove this defaulting code from the fakeRP:
https://github.com/openshift/openshift-azure/blob/5ee2f80b351e3f8c6b1e7549b7ed3de26c1dd70d/pkg/fakerp/fakerp.go#L275-L281
