### ISSUE TITLE
etcd backup would be nice

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#352]
ideally for PP ...

**Comment by kargakis** [comment]
Maybe we can use just the backup+restore operators.

**Comment by jim-minter** [comment]
@pweil- @amanohar if we can find an interim position quickly which adds protection for PP day 1, and given that this is a RH internal task, I'd be inclined to let this break the "feature freeze date" by a day or two.

@mjudeikis AKS uses the etcd operator to back up etcd to an Azure storage blob - might we for example be able to reuse that component in a freestanding way here in the short term?

**Comment by pweil-** [comment]
> I'd be inclined to let this break the "feature freeze date" by a day or two.

I would suggest here that backup on day 1 is not a strong enough requirement to break freeze.  We have already stated that customers should expect to delete their clusters.  I would make this a second iteration deployment if it doesn't fit.
