### ISSUE TITLE
add limits on master nodes

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#357]
see #258. @mjudeikis @kwoodson what's your opinion?

**Comment by kwoodson** [comment]
@mjudeikis @jim-minter,

We don't set kube-reserved on masters but we do set system-reserved:
```
 cpu=1000m,memory=1Gi
```

**Comment by mjudeikis** [comment]
This was my expectation too. Sound familiar what we use to do too

**Comment by mjudeikis** [comment]
@jim-minter can re refactor/rename this one to add limits on master nodeS?
