### ISSUE TITLE
GenerateARM signature should not include oldCs

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#367]
instead of passing oldCs, can we pass something like `isUpdate bool`?

**Comment by jim-minter** [comment]
@amanohar fyi

**Comment by pweil-** [comment]
@jim-minter @kargakis I don't really see the reasoning behind why it shouldn't include the oldCs.  Maybe I'm future proofing here but the work is already done and if we ever want to make decisions based on content of the oldCs during generation we'll have to change it.  

Is it difficult to make the oldCs available during this call?  Is there some other reason it *shouldn't* include it?

**Comment by kargakis** [comment]
> Is it difficult to make the oldCs available during this call? Is there some other reason it shouldn't include it?

/shrug

**Comment by jim-minter** [comment]
MSFT specifically want to avoid passing in more data than is needed, and want to avoid proliferating making edge-triggered decisions based on oldCs.  I understand it's bitten them in the past.

**Comment by pweil-** [comment]
done in 373 :smile:

**Comment by jim-minter** [comment]
thanks - didn't see it for looking
