### ISSUE TITLE
set locale for azure client (additional header)

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#372]
example: https://github.com/Azure/acs-engine/blob/849e5fd1a26e1dda2e8532afb58123e6049e4638/pkg/armhelpers/azureclient.go#L429

**Comment by asalkeld** [comment]
@jim-minter I have the code to set the client, my question is do we have to change the plugin api to pass this info through? So does MSFT have this info when calling the plugin?

**Comment by jim-minter** [comment]
@amanohar @sozercan where would you like to pass in "Accept-Language" into the plugin? Two ideas off the top of my head: do you initialize the plugin per end-user request, in which case `plugin.NewPlugin()` might do, or alternatively as a new api.ContextKey type (stash it in the context)?

**Comment by amanohar** [comment]
The plugin is initialized in a per end user request context basically one `plugin.NewPlugin()` per customer CRUD operation. So it makes sense to pass the language header during plugin init.

**Comment by jim-minter** [comment]
@asalkeld there's your answer - can you fix up NewPlugin so it takes a pointer to a plugin configuration struct, which will need to be newly defined and placed in pkg/api/plugin.go ?  That struct should contain the existing `syncImage string` as well as your new field.

**Comment by asalkeld** [comment]
@jim-minter thanks will do
