### ISSUE TITLE
Standardize our Load Balancers to be Standard Class, as opposed to Basic

### ISSUE THREAD

**Issue by thanasisk** [openshift/openshift-azure#376]
https://azure.microsoft.com/en-us/support/legal/sla/summary/

Basic LBs have NO SLA
In order to maintain consistency in our SLO/SLA calculations, we should switch to Standard Load Balancers that come with an SLA guarantee

**Comment by kargakis** [comment]
https://azure.microsoft.com/en-us/support/legal/sla/load-balancer/v1_0/

good catch @thanasisk ! Mind opening a PR?

cc @pweil- @jim-minter

**Comment by jim-minter** [comment]
standard load balancer support begins in k8s 1.11 https://github.com/kubernetes/kubernetes/pull/62707

**Comment by jim-minter** [comment]
it does not appear to be in openshift 3.10.

**Comment by jim-minter** [comment]
Closed for AZURE-136

**Comment by jim-minter** [comment]
@mjudeikis don't think this can be considered closed until `loadBalancerSku: standard` appears in our cloud provider conf? ;-)

**Comment by mjudeikis** [comment]
Done. Was not fully aware of that option :)
