### ISSUE TITLE
make ci project teardown better

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#381]
Some of the flakes now come from the issue that project in Azure is not terminate and when `ci-operator` reruns jobs it uses the same cluster, which already exists.

fix:
1. make create.sh properly execute teardown
2. make ci-projects very short-lived (2-3 hours).
3. refactor purge to accommodate it (if needed) 
4. make purge run each hour.

**Comment by kargakis** [comment]
Re 1., instead of fixing create.sh, we can also fix the ci-operator container that calls create.sh to wait or execute teardown properly?

**Comment by mjudeikis** [comment]
I suspect if failure is in `create.sh` post that there is one more command and the overall script is not getting "trapped" properly. It should wait for teardown, but does not.

```
trap 'rc=$?; if [[ $rc -ne 0 ]]; then 
# on failure we copy details for clean-up
cp -r /go/src/github.com/openshift/openshift-azure/_data /tmp/shared/ &>/dev/null
touch /tmp/shared/exit; fi; exit $rc' EXIT
trap 'kill $(jobs -p); exit 0' TERM
```

**Comment by mjudeikis** [comment]
as expected teardown is not getting triggered:
```
FATA[2018-09-10T08:56:49+01:00] Get https://mjudeikis.eastus.cloudapp.azure.com/healthz: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "openshift-signer") 
exit status 1
Test
exit code 0
```

**Comment by mjudeikis** [comment]
pending tests from closure
