### ISSUE TITLE
unit tests for pkg/cluster

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#382]
We need to be unit-testing our upgrade code. 

Requirements:
- move initialization of scale set, virtual machine, and kubernetes clients in `NewSimpleUpgrader`
- create interfaces for the scale set and VM clients, create fake implementations for those interfaces (from a brief look I had in the azure sdk [I couldnt find any fake clients](https://github.com/Azure/azure-sdk-for-go/issues/409)), use [k8s fake clientset](https://github.com/openshift/openshift-azure/tree/master/vendor/k8s.io/client-go/kubernetes/fake), use all interfaces in simpleUpgrader
- write those unit tests

I'd suggest tackling each of the aforementioned steps in separate PRs.

@openshift/sig-azure

**Comment by mjudeikis** [comment]
sgtm

**Comment by kargakis** [comment]
Unit tests missing for:
- [ ] pkg/cluster/drain.go#drain
- [ ] pkg/cluster/healthcheck#HealthCheck
- [ ] pkg/cluster/ready.go#WaitForInfraServices
- [ ] pkg/cluster/update.go#Update (and/or maybe  `waitForNewNodes`, `updateInPlace`, and `updatePlusOne`)

**Comment by asalkeld** [comment]
go tool cover -func=coverage.out | grep "pkg/cluster" | sort -n -k 3 -r
github.com/openshift/openshift-azure/pkg/cluster/updateblob/types.go:24:						NewUpdateBlob						100.0%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/marshal.go:11:						MarshalJSON						100.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:93:							Scale							100.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:81:							updateCache						100.0%
github.com/openshift/openshift-azure/pkg/cluster/ready.go:12:								WaitForNodesInAgentPoolProfile				100.0%
github.com/openshift/openshift-azure/pkg/cluster/names/names.go:59:							GetAgentRole						100.0%
github.com/openshift/openshift-azure/pkg/cluster/names/names.go:39:							GetScaleSetNameAndInstanceID				100.0%
github.com/openshift/openshift-azure/pkg/cluster/names/names.go:32:							GetHostname						100.0%
github.com/openshift/openshift-azure/pkg/cluster/names/names.go:24:							GetHostnamePrefix					100.0%
github.com/openshift/openshift-azure/pkg/cluster/names/names.go:15:							GetScalesetName						100.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:44:						setUnschedulable					100.0%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/blobservice.go:45:						Read							92.9%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/ready.go:17:						masterIsReady						90.0%
github.com/openshift/openshift-azure/pkg/cluster/update_worker.go:20:							findScaleSets						86.7%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/marshal.go:64:						UnmarshalJSON						85.7%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/marshal.go:29:						UnmarshalJSON						85.7%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/status.go:11:						GetControlPlanePods					81.8%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/blobservice.go:35:						Write							80.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:67:							initializeCache						80.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/status.go:29:						IsControlPlaneNamespace					80.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:17:						DrainAndDeleteWorker					77.8%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:106:							scaleUp							76.9%
github.com/openshift/openshift-azure/pkg/cluster/update_worker.go:151:							deleteWorkerScaleSet					75.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:159:							scaleDown						75.0%
github.com/openshift/openshift-azure/pkg/cluster/update_master.go:16:							UpdateMasterAgentPool					73.2%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:73:						deletePods						71.9%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:66:						max							66.7%
github.com/openshift/openshift-azure/pkg/cluster/hash.go:36:								HashScaleSet						66.7%
github.com/openshift/openshift-azure/pkg/cluster/update_worker.go:61:							UpdateWorkerAgentPool					59.3%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:57:						getControllerRef					50.0%
github.com/openshift/openshift-azure/pkg/cluster/update_worker.go:121:							createWorkerScaleSet					0.0%
github.com/openshift/openshift-azure/pkg/cluster/update_syncpod.go:8:							CreateOrUpdateSyncPod					0.0%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/marshal.go:46:						MarshalJSON						0.0%
github.com/openshift/openshift-azure/pkg/cluster/updateblob/blobservice.go:31:						NewBlobService						0.0%
github.com/openshift/openshift-azure/pkg/cluster/types.go:81:								NewSimpleUpgrader					0.0%
github.com/openshift/openshift-azure/pkg/cluster/types.go:140:								GenerateARM						0.0%
github.com/openshift/openshift-azure/pkg/cluster/types.go:136:								EnrichStorageAccountKeys				0.0%
github.com/openshift/openshift-azure/pkg/cluster/types.go:132:								EnrichCertificatesFromVault				0.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:61:							New							0.0%
github.com/openshift/openshift-azure/pkg/cluster/scaler/scaler.go:31:							NewFactory						0.0%
github.com/openshift/openshift-azure/pkg/cluster/ready.go:34:								SortedAgentPoolProfilesForRole				0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/syncpod.go:16:						EnsureSyncPod						0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:68:						RoundTrip						0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/roundtrip.go:132:						NewKubeclient						0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/ready.go:40:						WaitForReadySyncPod					0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/ready.go:36:						WaitForReadyWorker					0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/ready.go:13:						WaitForReadyMaster					0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/drain.go:36:						DeleteMaster						0.0%
github.com/openshift/openshift-azure/pkg/cluster/kubeclient/backup.go:16:						BackupCluster						0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:53:							WriteStartupBlobs					0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:40:							writeBlob						0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:17:							initializeStorageClients				0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:176:							ResetUpdateBlob						0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:154:							InitializeUpdateBlob					0.0%
github.com/openshift/openshift-azure/pkg/cluster/initialize.go:103:							CreateOrUpdateConfigStorageAccount			0.0%
github.com/openshift/openshift-azure/pkg/cluster/healthcheck.go:23:							WaitForHealthzStatusOk					0.0%
github.com/openshift/openshift-azure/pkg/cluster/healthcheck.go:12:							HealthCheck						0.0%
github.com/openshift/openshift-azure/pkg/cluster/hash.go:111:								HashSyncPod						0.0%
github.com/openshift/openshift-azure/pkg/cluster/etcdrestore.go:35:							EtcdRestoreDeleteMasterScaleSetHashes			0.0%
github.com/openshift/openshift-azure/pkg/cluster/etcdrestore.go:26:							EtcdRestoreDeleteMasterScaleSet				0.0%
github.com/openshift/openshift-azure/pkg/cluster/etcdrestore.go:12:							EtcdBlobExists						0.0%
github.com/openshift/openshift-azure/pkg/cluster/admin_actions.go:36:							RunCommand						0.0%
github.com/openshift/openshift-azure/pkg/cluster/admin_actions.go:15:							ListVMHostnames						0.0%
github.com/openshift/openshift-azure/pkg/cluster/admin_actions.go:11:							Reimage							0.0%

**Comment by jim-minter** [comment]
@asalkeld I'm prepared to call this done - are you?

**Comment by asalkeld** [comment]
agree
/close
