### ISSUE TITLE
collapse some packages

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#383]
Not sure how others feel about it but I think we should collapse `pkg/checks` in `pkg/healthcheck` and `pkg/validate` in `pkg/api`. Thoughts?

@openshift/sig-azure

**Comment by mjudeikis** [comment]
I agree with `check` and `healthcheck`.

Not sure about `api` and `validate`. I think we need to add "code to default values". And validate is good place to for it (https://github.com/openshift/openshift-azure/issues/336) . So it might grow little bit...

**Comment by pweil-** [comment]
I am +1 to combining these as suggested.  I also agree that defaulting and validation are part of the api side if we're following upstream patterns.

**Comment by jim-minter** [comment]
I agree too.  I'm somewhat paranoid about import dependencies in pkg/api, rolling validate in won't hurt that but we should keep it that way :)

**Comment by jim-minter** [comment]
Pulling in pkg/api from some project and getting huge bloat sucks.  We risk going there with all our SRE tooling, if we can avoid it so much the better.

(I don't love the fact that we import the kubernetes API on our internal API for kubeconfigs - cf #414)

**Comment by asalkeld** [comment]
I can do this.
