### ISSUE TITLE
add `json` tags to Config struct members

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#386]
We serialise the Config struct into the config SA.  At the moment we don't use `json:"foo"` tags on it.  I think it'd make sense to add these before PP starts and have them conform to the lowerCase style we use elsewhere. @kargakis @pweil- @mjudeikis thoughts?

**Comment by pweil-** [comment]
sgtm

**Comment by thanasisk** [comment]
lgtm however
/cc kargakis mjudeikis

**Comment by pweil-** [comment]
from #401 - This is staying open for the unit test implementation.

**Comment by charlesakalugwu** [comment]
Here's a summary of the testing strategy discussed with @jim-minter 

- [ ] create toLowerCamelCase function which converts a string to its lower camel case representation
- [ ] create test cases for toLowerCamelCase
- [ ] create two test cases for the config struct json tag conformance check
     - [ ] create first test case which walks through the config struct and for each field compares the toLowerCamelCase(field) with the json tag for that field. If list of errors at the end is empty then test succeeded else test failed
     - [ ]  create second test case which marshalls the struct and then checks that the marshalled json keys correspond with toLowerCamelCase(field) for a given field

**Comment by jim-minter** [comment]
> create test cases for toLowerCamelCase

I don't think that's essential

> create second test case which marshalls the struct and then checks that the marshalled json keys correspond with toLowerCamelCase(field) for a given field

I'm not sure how easy that will be, but some test that ensures the marshalled struct is sane is necessary.

**Comment by jim-minter** [comment]
this is waiting on:
* opening a PR for https://github.com/jim-minter/openshift-azure/commit/5e33112af2ce50c6ca0d7958655f2648f52622a5
* refactoring to put testJSONTags() in a shared package to avoid defining it twice
* adding an additional unit test which dynamically populates an entire api struct using reflect, then ensures it marshals/unmarshals against a manually curated yaml text - test in the internal and external package.
