### ISSUE TITLE
consider extending readiness checks to ensure all expected static pods are running

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#391]
I'm not sure if we need/want this or not.

**Comment by mjudeikis** [comment]
I saw cases when one master static pod was not starting due the wrong config in the master script (master-000000) due master.sh logic, error. I messed it once, somebody else will do it too. +1 for static pod checking.

**Comment by kargakis** [comment]
During upgrades we already check the readiness of static pods as part of deeming master nodes as ready so checking a second time in the healthcheck seems redundant but may not hurt.

**Comment by kargakis** [comment]
/kind feature

tempted to close

**Comment by mjudeikis** [comment]
I think close and reopen if needed
