### ISSUE TITLE
consolidate clients into pkg

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#400]
we starting to reuse the same client code base in a few places.  Without this our `e2e` tests will start duplicating client code in one more place

Suggestion: *Consolidate all clients under package `clients`* 
```
//reads local file config for testing and fake RP
clients.ReadConfig(path) (*api.OpenShiftManagedCluster, error)

//helps to coverts config file into context for testing fake RP
clients.ConfigToContext (cs *api.OpenShiftManagedCluster) (context.Context, error)

//returns kubeClient set for fake rp and testing and healthcheck, upgrade
clients.KubeClientsetFromConfig(cs *api.OpenShiftManagedCluster) (*kubernetes.Clientset, error) 

// azure storage clients for testing and initialization of the cluster. In the future etcd restore automation (?) 
clients.AzureStorageClientset(ctx context.Context, cs *api.OpenShiftManagedCluster) (*azureStorageClient, error)

// possible future azure clients extentions 
clients.AzureNetoworkClientset(ctx context.Context, cs *api.OpenShiftManagedCluster) (*azureNetworkClient, error) 

// for test and healthcheck. This might even be removed and replaces by one of the methods above
clients.KubeGetConfigFromV1Config(kc *v1.Config) (clientcmd.ClientConfig, error) 
```

WDYT @openshift/sig-azure  ?

**Comment by kargakis** [comment]
I don't feel strong about creating a generic clients package that is basically a wrapper for the azure sdk and client-go. I am in favor of using the clients directly. client-go exposes interfaces and has fake implementations, that's the only issue with the azure sdk so for that we will need to create our own interfaces and fake implementations for unit-testability.

**Comment by mjudeikis** [comment]
So maybe just for azure?

**Comment by mjudeikis** [comment]
for future extensibility: https://github.com/Azure/azure-sdk-for-go/issues/409 
https://github.com/kubernetes/kubernetes/blob/34001d8c6a0ed4edf02d91c5b45920a2676418f9/pkg/cloudprovider/providers/azure/azure_client.go

**Comment by mjudeikis** [comment]
close in favor of:  AZURE-148 - Consolidate clients pkg
