### ISSUE TITLE
/var gets filled

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#403]
`/var/log` filled - probably trim journald.conf to <8G 
and deal with all the other files that were growing without bounds,
/var/log/messages (which was rotated)

```
[root@master-000000 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        10G  1.9G  8.2G  19% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  1.4M  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
>>>>>>>  /dev/sda2        22G   22G  507M  98% /var   <<<<<<<<<<<<<<
/dev/sdb1        16G  2.4G   14G  15% /var/lib/docker
/dev/sdc         32G  410M   32G   2% /var/lib/etcd
tmpfs           797M     0  797M   0% /run/user/1000
```

```
19225060        /var
16293448        /var/log
8391980 /var/log/journal/455b4464db3464ed662d670c76a55034
8391980 /var/log/journal
5793332 /var/log/messages-20180909
```

/kind bug

**Comment by thekad** [comment]
@mjudeikis do you think just avoiding writing these files at all (i.e. turning off rsyslogd) will work?
Pros: decrease i/o in the nodes, won't need to rotate logs that don't exist, we already log everything through the journal
Cons: there may be an unknown edge case relying on rsyslogd

What do you think? That way we can keep the current max size of 8G in the journald too...
