### ISSUE TITLE
postsubmits are broken circa 4 days

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#412]
```
2018/09/12 14:00:12 Copying artifacts from release-latest into /logs/artifacts/release-latest
info: Using registry public hostname registry.svc.ci.openshift.org
Error: unknown flag: --max-per-registry
```
https://storage.googleapis.com/origin-ci-test/logs/branch-ci-openshift-openshift-azure/8/build-log.txt

@openshift/sig-azure

**Comment by kargakis** [comment]
@bbguimaraes @petr-muller @stevekuznetsov this happens only in postsubmits where the only difference is the promotion step. Does it ring a bell?

**Comment by petr-muller** [comment]
https://github.com/openshift/ci-operator/pull/126/ maybe?

**Comment by kargakis** [comment]
Opened https://github.com/openshift/ci-operator/issues/140
