### ISSUE TITLE
hack/ssh.sh does not work with a resourceGroup and a number as args

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#425]
"@" is redundant in the ssh command

/kind bug
@openshift/sig-azure

**Comment by kargakis** [comment]
@jim-minter fixed?

**Comment by jim-minter** [comment]
@kargakis does #442 solve this?  If not, I don't understand the issue.  Intended usage:

`hack/ssh.sh`: ssh into master-000000 of provisioned cluster
`hack/ssh.sh otherresourcegroup` ssh into master-000000 in otherresourcegroup
`hack/ssh.sh -n X` ssh into master-00000X of provisioned cluster
`hack/ssh.sh otherresourcegroup -n X` ssh into master-00000X in otherresourcegroup

**Comment by kargakis** [comment]
Seems `hack/ssh.sh otherresourcegroup -n X` is still not working for me.

**Comment by jim-minter** [comment]
I was trying to be clever, and I failed.  Sorry.  See #453.

**Comment by jim-minter** [comment]
Turns out the `-n X` has to come first in `hack/ssh.sh -n X otherresourcegroup`
