### ISSUE TITLE
need check if published image is development or release

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#429]
When publishing images we need to make sure we test if those images is build in "release" mode or "development" mode. Images should point to `registry.redhat.com` and not development aws registry

**Comment by jim-minter** [comment]
e2e check should ensure that no reg-aws images are running on box

**Comment by jim-minter** [comment]
also that centos boxes are running origin images, and rhel OCP images

**Comment by mjudeikis** [comment]
Closed in favor of Azure-153 @kwoodson already assigned to you :)
