### ISSUE TITLE
add validate to tests/overrides

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#435]
Add validation to `tests/overrides` so we control it never gets committed with content

**Comment by mjudeikis** [comment]
/kind feature
This might need to be closed. depending what we will do with conformance tests in our repo

**Comment by kargakis** [comment]
I think we should run conformance in our repo regardless of whether we are going to run them in prod.

/area tests

**Comment by mjudeikis** [comment]
close in favor of AZURE-146 - Add validate for test overrides
