### ISSUE TITLE
Automate rebuilding openshift-azure image 

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#438]
https://github.com/openshift/release/pull/1501 adds a test image that includes the openshift-azure source code for the node build job to use. We should ensure that image gets updated on a regural cadence (either per commit push in master or rebuild it periodically).

**Comment by jim-minter** [comment]
is there a way to do it without an openshift-azure image? would moving to that be an alternative to this issue?

**Comment by kargakis** [comment]
The alternative is to clone the git repo in the test container either via ci-operator ([not supported currently](https://github.com/openshift/ci-operator/issues/142)) or do it ourselves using git directly but then we are back to the aos-cd-jobs madness. Do you have any concerns with the image approach?

**Comment by kargakis** [comment]
I have pushed https://github.com/openshift/release/pull/1530/commits/c0c3408be4a304bae3682bb0be0b0ca5648a0f53 which removes the use of the openshift-azure image in favor of clonning directly in the test container. The problem that I cannot think of how to workaround with a prebuilt image is that `hack/create.sh` needs to write the cluster data in `_data` but the filesystem is not writtable. I don't know how to make `/go/src/github.com/openshift/openshift-azure` writtable when building the image (`VOLUME path` does not work). The k8s way is to use an emptyDir but that is going to mask the actual content. The upside of clonning directly is that we don't have to maintain one more image. Thoughts? cc @mjudeikis

**Comment by kargakis** [comment]
The image is now removed. No strong feelings on makind the _data location configurable.
