### ISSUE TITLE
Enable reuse of the node build template

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#439]
We want to reuse the [node build template](https://github.com/openshift/release/pull/1502) for building {rhel,centos} x {$openshift_version} combinations of images.

**Comment by kargakis** [comment]
@kwoodson @mjudeikis for discussion

I think we can do this by (ab)using `--secrets-dir` in the ci-operator. That means we will need 4 different secrets in the ci namespace.

**Comment by kwoodson** [comment]
@kargakis, hmm.  Secrets would be much easier than managing the build scripts as they would be copy & paste of the same file.  Would like to see how this works.

I'd like to move the build base image job over as well.  This job will require the same structure and secrets for rhel/centos.

**Comment by mjudeikis** [comment]
@kargakis I was looking to how prow passes stuff to tests:
In the template we have:
https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e-openshift-ansible.yaml#L23
and it gets translated from prow here:
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-presubmits.yaml#L146 

I didn't see any logic to pass it to the downstream, and I expect there might be something under the hood to pass these from prow to template. If this works, we could have 4 prow jobs with variables.

**Comment by kargakis** [comment]
Part of the doc for the meeting with developer productivity

/close
