### ISSUE TITLE
pull all os.Getenvs() out of plugin code and centralise in a plugin config struct

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#466]
It's important that none of the plugin code that is vendored into the RP should call os.Getenv.  We don't want to make any expectations about the RP environment, especially undocumented expectations.  They could bite us horribly later.

At the moment we check the following environment variables in the plugin:
RUNNING_UNDER_TEST
IMAGE_{RESOURCEGROUP,RESOURCENAME,OFFER,VERSION}
DEPLOY_OS
OREG_URL

All of these variables are expected to be empty when the code is running in the RP.

For these environment variables, only, that are actually used in the plugin, we should add a mechanism to set them in the PluginConfig.  Maybe for example:

```
type PluginConfig struct {
	SyncImage       string
	AcceptLanguages []string
	TestConfig      *TestConfig
}

type TestConfig struct {
	ImageResourceGroup string
	...
}
```

We would insist that the RP runs with TestConfig set to nil.  We could populate it otherwise if we wanted.

No environment variables used outside the plugin in the Fake RP (i.e. cmd/createorupdate) (e.g. AUTOACCEPT_MARKETPLACE_AGREEMENT, AZURE_CLIENT_SECRET) should be anywhere near the plugin config.

**Comment by kargakis** [comment]
This is a prerequisite for sharing CreateOrUpdate properly between different processes/contexts, something needed in transforming our fake RP to an http server. @thekad let me know what I can do to help out. Happy to review once you have a PR out.

**Comment by thekad** [comment]
@jim-minter there is a problem specifically with 3 vars: `RUNNING_UNDER_TEST` and `IMAGE_RESOURCE{NAME,GROUP}`: these are read directly from the templates via `GenerateARM`, that means we either a) change the GenerateARM API interface to include a `PluginConfig | TestConfig` or b) embed a `PluginConfig | TestConfig` in the Context or OpenShiftManagedCluster objects so they can still be read from the template.
Thoughs? cc @kargakis

**Comment by thekad** [comment]
From our call this morning: It's fine to change the `api.plugin.GenerateARM` call.
