### ISSUE TITLE
Updatability of Properties used in Generate

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#469]
Every use of an item from Properties in our generate code base should done in a way which, if the property item changes, the corresponding Config is regenerated.

For example, currently if you were to change the FQDN, the relevant certificates would not be regenerated.

**Comment by mjudeikis** [comment]
@jim-minter any ideas on implementation details you have in mind? 
I was thinking underlines:
Pass old and new configs to `generate` and if values are diff, regenerate?

**Comment by mjudeikis** [comment]
/close 
done with regen pr
