### ISSUE TITLE
enable engineering in additional regions

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#486]
suggest westeurope and australiasoutheast (recommendations based on availability of loganalytics service)

- [x] publish images in additional regions - try australia, germany, uk
- [x] parameterise eastus in create.sh, allow westeurope and australiasoutheast

at this point should be able to use published images outside of eastus

- [ ] copy published internal disk images to additional regions
- [ ] update purge and publish code accordingly

at this point should be able to use internal images outside eastus as well

**Comment by jim-minter** [comment]
@asalkeld reopening this issue - only the first two items have been covered ;-)

**Comment by asalkeld** [comment]
@jim-minter could you fill in some more details about what those remaining issues are?

**Comment by jim-minter** [comment]
So, at the moment our image building process results in a) an Azure Image object which is tied to eastus in the images resource group, and b) a blob copy of the image in the openshiftimages storage account in the images resource group.

*If* we want to be able to deploy clusters from these unpublished Image objects in other regions, we need a process which replicates copies of those Image objects into selected other regions.  We'd need to be able to distinguish the replicated Images as well (e.g. "centos7-3.10-201809261525" becomes "eastus-centos7-3.10-201809261525", etc.

This has knock-on effects on our image building (we have to implement the replication), env file in openshift-azure, publishing and purge tools (because the names change).

I feel like we should only make the investment of effort if it really makes a significant workflow improvement for people a long way from eastus (@mjudeikis @kargakis @asalkeld opinions?) as it's moderately expensive to do.  I'm on the fence.  OTOH it's also a good learning opportunity.

**Comment by asalkeld** [comment]
Surely we will need this for our customers anyway? We can't have everyone on the globe using eastus right? So this is purely a prioritising issue?

I am also a little confused why we need more work, as we can already create clusters in other zones.
Or is this to automate what you did manually?

Also a bit confused why the images need different names, I would have thought you just ask for image x and azure by default would look in the local region for that image.

https://www.microsoft.com/developerblog/2018/02/15/copy-custom-vm-images-on-azure/

**Comment by mjudeikis** [comment]
> Surely we will need this for our customers anyway? We can't have everyone on the globe using eastus right? So this is purely a prioritising issue?

This is only for development. Users will use "properly published images", which is replicated by MSFT. We use our fake publishing in RG `images`

> I feel like we should only make the investment of effort if it really makes a significant workflow improvement 

I dont see any value in this personally. I, either way, jumping via VPNS all around the globe. I my page loads in 200ms ir 500ms, at this point I don't see the issue to use easus IF I work with `images` RG. If I need performance, I can use Published images in "proper way".  But maybe its just me dont feeling difference with "awesome uk internet"

**Comment by kargakis** [comment]
Yes, this is only for dev purposes. I don't think it is a *significant* improvement over what we have today.

**Comment by asalkeld** [comment]
I am happy to leave it ¯\_(ツ)_/¯, just curious how it works now without the above steps.

**Comment by mjudeikis** [comment]
Its just you can use:
```
#export IMAGE_RESOURCEGROUP=images
#export IMAGE_RESOURCENAME=$(az image list -g $IMAGE_RESOURCEGROUP -o json --query "[?starts_with(name, '${DEPLOY_OS:-rhel7}-${DEPLOY_VERSION//v}') && tags.valid=='true'].name | sort(@) | [-1]" | tr -d '"')
```
vars in eastus region. So if you need to develo VM images, its only place where you can do it. If you do code - you use published images and do stuff ontop.

**Comment by kargakis** [comment]
I think we can call this done.
