### ISSUE TITLE
Ensure VMSS placement groups are not restricted

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-azure#495]
As we start scale testing we need to ensure we are not restricting our node VMSS configuration to a single placement group.  By default a single placement group is used which limits the VMSS to 100 VMs.  By setting `singlePlacementGroup` to false we up that limit to 1k VMs.  

```
What makes a large scale set special is not the number of VMs, but the number of placement groups it contains. A placement group is a construct similar to an Azure availability set, with its own fault domains and upgrade domains. By default, a scale set consists of a single placement group with a maximum size of 100 VMs. If a scale set property called singlePlacementGroup is set to false, the scale set can be composed of multiple placement groups and has a range of 0-1,000 VMs. When set to the default value of true, a scale set is composed of a single placement group, and has a range of 0-100 VMs.
```

Ref: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-placement-groups

**Comment by asalkeld** [comment]
I made a quick go at this, looks like we also need to change the loadbalancer

this is the error when I just set that property to false

{ "error": { "details": [], "code": "VMScaleSetCannotReferenceLoadbalancerWhenLargeScaleOrCrossAZ", "message": "VM scale set cannot use a basic SKU load balancer when LargeScale property is enabled, or when the VMSS spans multiple availability zones. Please use standard SKU load balancer instead." } }

**Comment by kargakis** [comment]
> { "error": { "details": [], "code": "VMScaleSetCannotReferenceLoadbalancerWhenLargeScaleOrCrossAZ", "message": "VM scale set cannot use a basic SKU load balancer when LargeScale property is enabled, or when the VMSS spans multiple availability zones. Please use standard SKU load balancer instead." } }

We cannot use a standard LB yet, see https://github.com/openshift/openshift-azure/issues/376#issuecomment-419514857

**Comment by asalkeld** [comment]
OK, thanks @kargakis that saves me some time. I have parked my branch here:
https://github.com/asalkeld/openshift-azure/commit/d94bb00f553b3c8a7d1787462c775ff422249164
