### ISSUE TITLE
sync process logs changes to secrets

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#504]
The sync pod ensures that the actual state of OpenShift objects matches the desired state.
Any time when there is a mismatch and the sync pod updates an object, it logs the delta to stdout.
We should ensure that if the changed object is a Secret, that we do not log the secret contents to stdout.

===

And we gather sync logs in CI now. We will need to fix printing secret content in the logs before we do any testing with secret rotation.

/priority important-soon

**Comment by mjudeikis** [comment]
@kargakis we want secret changes to be logged but change content offuscated?

**Comment by kargakis** [comment]
@mjudeikis correct, obfuscated or just omitted.
