### ISSUE TITLE
Cluster health check should validate that router FQDN creation succeeded

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#523]
Router FQDN creation was failing due restriction that domain name label must start with a letter and not a number (randomly generated value). We made a fix to ensure that router FQDN always starts with a letter.

However, we also noticed that cluster health check was not failing due to this and create operation was succeeding. We discovered the issue by looking at controller manager logs when Jenkins app we created could not be reached. Health check should also validate that router FQDN is reachable.

```E0925 22:26:03.889803       1 azure_backoff.go:372] backoff: failure, will retry, HTTP response=400, err=network.PublicIPAddressesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDomainNameLabel" Message="The domain name label 7e37591a6e974a0f93af is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$." Details=[]```

**Comment by jim-minter** [comment]
Looks like MSFT is validating against RFC952, and we're validating against RFC1123

**Comment by jim-minter** [comment]
@amanohar I think the fix here is simply for us to validate all the hostnames against RFC952 since that's what Azure appears to do.  I don't think that there is a suitable health check that we should add here.
