### ISSUE TITLE
health check validation for fqdn tied to region

### ISSUE THREAD

**Issue by shrutir25** [openshift/openshift-azure#534]
I created a cluster where the input fqdn was `osatestshrcluster03-0928.eastus.cloudapp.azure.com` and location for cluster was `westcentralus`. This cluster creation failed in health check with error
`Health check failed. error: Get https://osatestshrcluster02-0928.eastus.cloudapp.azure.com/healthz: dial tcp: lookup osatestshrcluster02-0928.eastus.cloudapp.azure.com on 10.0.0.10:53: no such host`.

On looking closer, I could see that `https://osatestshr02cluster0928.westcentralus.cloudapp.azure.com/healthz` was up, even though the input was actually `osatestshrcluster03-0928.eastus.cloudapp.azure.com`

**Comment by jim-minter** [comment]
@shrutir25 your input was invalid and we didn't catch it.  We should not have accepted the input fqdn foo.eastus when we knew the cluster location was westcentralus.
