### ISSUE TITLE
networkProfile is not included in MergeConfig

### ISSUE THREAD

**Issue by sozercan** [openshift/openshift-azure#541]
`networkProfile` is not included in mergeConfig

https://github.com/openshift/openshift-azure/blob/master/pkg/plugin/plugin.go#L34

**Comment by sozercan** [comment]
looks like we can't do partial updates without `networkProfile`

getting this error:
```
errors from validation: [invalid properties.agentPoolProfiles.subnetCidr "": all subnetCidrs must match invalid properties.agentPoolProfiles["master"].subnetCidr ""]{
```

**Comment by jim-minter** [comment]
(the error in the second comment is not pertinent to this issue)
