### ISSUE TITLE
 replace azuredeploy []byte with template map[string]interface{} in all function signatures

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#547]
In reviewing https://github.com/openshift/openshift-azure/pull/521 @jim-minter suggested we change
all azuredeploy []byte to map[string]interface{} 

example:
	CreateOrUpdate(ctx context.Context, cs *OpenShiftManagedCluster, azuredeploy []byte, isUpdate bool, Deployer DeployFn) error

We have now changed the custom deploy function to the new parameter, but we should change all of them.

**Comment by mjudeikis** [comment]
For my own education, why this is needed? What is rational behind this?
