### ISSUE TITLE
WaitForCompletion: context has been cancelled  flake

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#552]
Valid test flake
```
time="2018-10-03T14:24:31Z" level=info msg="write helpers" resourceGroup=ci-op-d9wxcrm6-8474e
time="2018-10-03T14:24:31Z" level=info msg="applying arm template deployment" resourceGroup=ci-op-d9wxcrm6-8474e
time="2018-10-03T14:24:33Z" level=info msg="waiting for arm template deployment to complete" resourceGroup=ci-op-d9wxcrm6-8474e
time="2018-10-03T14:39:33Z" level=fatal msg="Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded"
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/387/pull-ci-openshift-openshift-azure-master-e2e-azure/152/build-log.txt
/kind test-flake

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/624/pull-ci-openshift-openshift-azure-master-e2e-azure/463?log#log

**Comment by kargakis** [comment]
We are seeing a lot of different timeouts

Latest
```
time="2018-11-20T12:57:21Z" level=info msg="waiting for arm template deployment to complete" resourceGroup=ci-op-5fy5djqy-8474e
time="2018-11-20T13:01:01Z" level=debug msg="400 Bad Request: Failed to apply request: Initialize: Put https://4paisvz0oxrjp2fpxcv6adek.blob.core.windows.net/etcd?restype=container: dial tcp 52.239.214.132:443: i/o timeout" resourceGroup=ci-op-5fy5djqy-8474e
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/758/pull-ci-openshift-openshift-azure-master-e2e-azure/835/build-log.txt

@amanohar

**Comment by kargakis** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/758/pull-ci-openshift-openshift-azure-master-e2e-azure/833/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/758/pull-ci-openshift-openshift-azure-master-e2e-azure/832/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/758/pull-ci-openshift-openshift-azure-master-e2e-azure/830/build-log.txt

**Comment by amanohar** [comment]
@kargakis ack. I will take a look.

**Comment by thekad** [comment]
@amanohar do you have any new findings here?

**Comment by mjudeikis** [comment]
re-open of still an issue. Dont remember seeing this one recently.

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1588/pull-ci-azure-master-upgrade-v3.2/116/build-log.txt

**Comment by asalkeld** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1589/pull-ci-azure-master-e2e-create/91

**Comment by charlesakalugwu** [comment]
#1642 
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1642/pull-ci-azure-master-upgrade-v3.2/213/build-log.txt

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1669/pull-ci-azure-master-upgrade-v3.2/254/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1682/pull-ci-azure-master-upgrade-v5.1/134/build-log.txt

**Comment by Makdaam** [comment]
Happens every time during realRP vnet test, when the cluster is deleted.
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/39/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/40/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/41/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/42/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/43/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/44/build-log.txt
https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-azure-e2e-prod-vnet/45/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1714/pull-ci-azure-master-upgrade-v4.4/151/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1721/pull-ci-azure-master-upgrade-v5.1/170/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1722/pull-ci-azure-master-e2e-create/352/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1714/pull-ci-azure-master-upgrade-v4.4/166/build-log.txt

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1722/pull-ci-azure-master-upgrade-v5.1/205/build-log.txt

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-upgrade-v5.2/137/build-log.txt in #1781

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1781/pull-ci-azure-master-e2e-create/511/build-log.txt in #1781

**Comment by kwoodson** [comment]
Tally one for West-Europe
```
time="2019-07-16T11:20:22Z" level=info msg="using region westeurope"
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1750/pull-ci-azure-master-upgrade-v5.1/388/build-log.txt
```
time="2019-07-16T11:52:29Z" level=warning msg="deployment failed: autorest.DetailedError{Original:context.deadlineExceededError{}, PackageType:\"Future\", Method:\"WaitForCompletion\", StatusCode:200, Message:\"context has been cancelled\", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00054c000)}" func=github.com/openshift/openshift-azure/pkg/fakerp.GetDeployer.func1 file="/tmp/tmp.oIMV85fOqU/src/github.com/openshift/openshift-azure/pkg/fakerp/fakerp.go:116"
```
PR:
https://github.com/openshift/openshift-azure/pull/1750

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1783/pull-ci-azure-master-upgrade-v5.2/228/build-log.txt #1783

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1812/pull-ci-azure-master-upgrade-v5.2/387/build-log.txt #1812

**Comment by m1kola** [comment]
Seems to be the same issue in #1821

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1821/pull-ci-azure-master-vmimage/48/build-log.txt

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1842/pull-ci-azure-master-upgrade-v5.2/438/build-log.txt #1842

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1856/pull-ci-azure-master-upgrade-v5.2/449/build-log.txt #1856

**Comment by amanohar** [comment]
From the logs I see this is a VM extension provisioning timeout. VM extension provisioning timeout is generic error that can happen for a variety of reasons because of what happened in a CSE run. Are there logs from CSE runs that show the stage at which the run got stuck resulting in CSE timeout?

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1863/pull-ci-azure-master-upgrade-v7.0/75/build-log.txt in #1863

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1877/pull-ci-azure-master-upgrade-v6.0/92/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1877/pull-ci-azure-master-upgrade-v7.0/90/build-log.txt
#1877

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1902/pull-ci-azure-master-vmimage/81/build-log.txt in #1902

**Comment by asalkeld** [comment]
So looking into these a bit more: ( @jim-minter )

1. master-00000 dns lookup issue
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1812/pull-ci-azure-master-upgrade-v5.2/387/artifacts/ and https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1856/pull-ci-azure-master-upgrade-v5.2/449/artifacts/

master-000000 could not get it's hostname https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1812/pull-ci-azure-master-upgrade-v5.2/387/artifacts/master-000000-waagent-stderr and the other masters couldn't connect to it either (etcd issues) https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1812/pull-ci-azure-master-upgrade-v5.2/387/artifacts/master-000002-early-journal ( dial tcp: lookup master-000000 on 168.63.129.16:53: no such host)
basic bug: master-000000 dns lookup issue?

2. openshift-node restarted a bunch of times then went into a failed state
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1783/pull-ci-azure-master-upgrade-v5.2/228/artifacts/
on 2 infra nodes openshift-node restarted a bunch of times then went into a failed state
see: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1783/pull-ci-azure-master-upgrade-v5.2/228/artifacts/infra-1563401064-000000-waagent-stderr and https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1783/pull-ci-azure-master-upgrade-v5.2/228/artifacts/infra-1563401064-000000-early-journal
```
Jul 17 22:29:31 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:31.978520   12135 server.go:536] Successfully initialized cloud provider: "azure" from the config file: "/etc/origin/cloudprovider/azure.conf"
Jul 17 22:29:31 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:31.978591   12135 server.go:782] cloud provider determined current node name to be infra-1563401064-000000
Jul 17 22:29:31 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:31.978628   12135 bootstrap.go:56] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Jul 17 22:29:31 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:31.981424   12135 bootstrap.go:86] No valid private key and/or certificate found, reusing existing private key or creating a new one
Jul 17 22:29:32 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:32.011977   12135 csr.go:105] csr for this node already exists, reusing
Jul 17 22:29:32 infra-1563401064-000000 atomic-openshift-node[12135]: I0717 22:29:32.016989   12135 csr.go:113] csr for this node is still valid
Jul 17 22:34:31 infra-1563401064-000000 systemd[1]: atomic-openshift-node.service start operation timed out. Terminating.
```
It's not totally clear to me why.

3. quay.io networking issue
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1842/pull-ci-azure-master-upgrade-v5.2/438/artifacts/ and https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1877/pull-ci-azure-master-upgrade-v6.0/92/artifacts/
this is a quay.io networking issue, heaps of these errors
```
+ docker pull quay.io/openshift-on-azure/azure:v5.2
Get https://quay.io/v1/_ping: dial tcp 54.243.152.199:443: i/o timeout
```

4.  storage account and nsg resource errors
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1863/pull-ci-azure-master-upgrade-v7.0/75/build-log.txt

```
msg="{\n  \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Resources/deployments/azuredeploy/operations/0FAED289C1D6DF2E\",\n  \"operationId\": \"0FAED289C1D6DF2E\",\n  \"properties\": {\n    \"provisioningState\": \"Running\",\n    \"timestamp\": \"2019-08-21T12:08:56.9118432Z\",\n    \"serviceRequestId\": \"fb6a378f-81ab-4db0-8bfe-5ec0f0340b01\",\n    \"statusCode\": \"Accepted\",\n    \"targetResource\": {\n      \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Storage/storageAccounts/safil0cb01qe8mog8emq231o\",\n      \"resourceName\": \"safil0cb01qe8mog8emq231o\",\n      \"resourceType\": \"Microsoft.Storage/storageAccounts\"\n    }\n  }\n}" 
 msg="{\n  \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Resources/deployments/azuredeploy/operations/7B4909E22B8F73AB\",\n  \"operationId\": \"7B4909E22B8F73AB\",\n  \"properties\": {\n    \"provisioningState\": \"Running\",\n    \"timestamp\": \"2019-08-21T12:05:42.3967691Z\",\n    \"serviceRequestId\": \"c080ba78-acdc-4f95-ab38-d4e1f24c24a7\",\n    \"statusCode\": \"InternalServerError\",\n    \"statusMessage\": {\n      \"error\": {\n        \"code\": \"MultipleErrorsOccurred\",\n        \"details\": [\n          {\n            \"code\": \"ServerTimeout\",\n            \"message\": \"The request timed out. Diagnostic information: timestamp '20190821T120541Z', subscription id '225e02bc-43d0-43d1-a01a-17e584a4ef69', tracking id '326d228a-e272-46c2-af86-8bf36d6dd82c', request correlation id '2098aac9-4e54-4e07-bb79-03276274b84e'.\"\n          },\n          {\n            \"code\": \"ServerTimeout\",\n            \"message\": \"The request timed out. Diagnostic information: timestamp '20190821T120541Z', subscription id '225e02bc-43d0-43d1-a01a-17e584a4ef69', tracking id '326d228a-e272-46c2-af86-8bf36d6dd82c', request correlation id '2098aac9-4e54-4e07-bb79-03276274b84e'.\"\n          }\n        ],\n        \"message\": \"Multiple error occurred: . Please see details.\"\n      }\n    },\n    \"targetResource\": {\n      \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Network/networkSecurityGroups/nsg-worker\",\n      \"resourceName\": \"nsg-worker\",\n      \"resourceType\": \"Microsoft.Network/networkSecurityGroups\"\n    }\n  }\n}" 
msg="{\n  \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Resources/deployments/azuredeploy/operations/4DD8C422C328E19E\",\n  \"operationId\": \"4DD8C422C328E19E\",\n  \"properties\": {\n    \"provisioningState\": \"Running\",\n    \"timestamp\": \"2019-08-21T12:08:40.1398512Z\",\n    \"serviceRequestId\": \"838cab2f-9b8d-4a72-94ad-ea37e9333f01\",\n    \"statusCode\": \"InternalServerError\",\n    \"statusMessage\": {\n      \"error\": {\n        \"code\": \"MultipleErrorsOccurred\",\n        \"details\": [\n          {\n            \"code\": \"ServerTimeout\",\n            \"message\": \"The request timed out. Diagnostic information: timestamp '20190821T120830Z', subscription id '225e02bc-43d0-43d1-a01a-17e584a4ef69', tracking id '46dadd23-c8ce-4b72-bbe2-ab4c0ac8158a', request correlation id '2098aac9-4e54-4e07-bb79-03276274b84e'.\"\n          },\n          {\n            \"code\": \"ServerTimeout\",\n            \"message\": \"The request timed out. Diagnostic information: timestamp '20190821T120830Z', subscription id '225e02bc-43d0-43d1-a01a-17e584a4ef69', tracking id '46dadd23-c8ce-4b72-bbe2-ab4c0ac8158a', request correlation id '2098aac9-4e54-4e07-bb79-03276274b84e'.\"\n          }\n        ],\n        \"message\": \"Multiple error occurred: . Please see details.\"\n      }\n    },\n    \"targetResource\": {\n      \"id\": \"/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-1863-e2e-upgrade-kriern/providers/Microsoft.Network/publicIPAddresses/ip-outbound\",\n      \"resourceName\": \"ip-outbound\",\n      \"resourceType\": \"Microsoft.Network/publicIPAddresses\"\n    }\n  }\n}" 
```
5. master-000002 did not start causing lots of networking issues
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1589/pull-ci-azure-master-e2e-create/91/artifacts/
note in the artifacts there are no master-000002 logs
lots of these errors: 
```
health check for peer 1af0a02c96724e92 could not connect: dial tcp: lookup master-000002 on 168.63.129.16:53: no such host
```
from a different node
```
health check for peer 1af0a02c96724e92 could not connect: dial tcp: lookup master-000002 on 168.63.129.16:53: dial udp 168.63.129.16:53: i/o timeout
```

**Comment by Makdaam** [comment]
Another flake, deadline exceeded when creating ss-compute.
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2005/pull-ci-azure-release-v10-e2e-scaleupdown-v7.1/2
