### ISSUE TITLE
rhel node image build is broken

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#562]
Our rhel vm node image build is currently broken due to the following error:
```
No service account file found at /usr/share/ansible/openshift-ansible/inventory/dynamic/injected/credentials, bypassing login
```

See logs:
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/logs/azure-build-node-image-rhel-310/55/
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/logs/azure-build-node-image-rhel-310/56/

**Comment by kargakis** [comment]
The latest node build seems failed because of the pdb flake and the previous one was successful. Also, the "No service account file" log is a red herring.

/close
