### ISSUE TITLE
Origin conformance test failure: missing docker excluder

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#566]
The `build node image` step of the `test_branch_openshift_ansible_extended_conformance_azure` job occasionally fails with error `No package matching 'origin-docker-excluder-3.11**` 

```
TASK [openshift_excluder : Install docker excluder - yum] **********************
Friday 05 October 2018  17:52:05 +0000 (0:00:00.056)       0:04:47.088 ******** 
FAILED - RETRYING: Install docker excluder - yum (3 retries left).
FAILED - RETRYING: Install docker excluder - yum (2 retries left).
FAILED - RETRYING: Install docker excluder - yum (1 retries left).
fatal: [137.135.92.151]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-docker-excluder-3.11**' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-docker-excluder-3.11**' found available, installed or updated"]}
```

**Comment by kargakis** [comment]
/shrug

@kwoodson

**Comment by kwoodson** [comment]
@charlesakalugwu,

This is due to the URL being passed.  That URL is what is used for the source install and it doesn't include the correct package set.

**Comment by mjudeikis** [comment]
Ou, its this time of year... new release is coming...

**Comment by kargakis** [comment]
We should disable these ansible Jenkins jobs since they seem broken for sometime and we have a jira issue for adding them back anyway.

**Comment by mjudeikis** [comment]
http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ excluder 3.11 is not yet synced to origin repos... again...

**Comment by kargakis** [comment]
@mjudeikis status on this issue?

**Comment by mjudeikis** [comment]
I think "time of the year" passed we can close
/close
