### ISSUE TITLE
Use secrets to populate env variables 

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#567]
We inline secrets inside some of our infra deployments (eg. [router](https://github.com/openshift/openshift-azure/blob/dd6e8c038a1b5d06d908bb6cab5876db548cd478/pkg/addons/data/Deployment.apps/default/router.yaml#L46)). This is problematic because every change in the deployment is logged inside the sync pod and we should avoid logging sensitive info as much as possible. Instead of inlining, we should create secrets and use them as `env.valueFrom.secretKeyRef` inside the containers.

/kind feature

**Comment by jim-minter** [comment]
@thekad bump - is this done?

**Comment by thekad** [comment]
Should be fixed by #1342

**Comment by thekad** [comment]
I seem unable to close this issue.
