### ISSUE TITLE
Re-expose functions in the plugin (make more granular functions)

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#575]
We have just cleaned up the plugin interface, but it seems like it is not going to work for MSFT.
see: https://github.com/openshift/openshift-azure/pull/521#discussion_r223584008

I think the main statement is
"
Most importantly, running create or update cannot be a black box function to the RP because each step in the process in unique & functionally different and putting it all in one function and returning it as a generic error reduces flexibility of the process overall & takes away visibility into how each error needs to be handled, logged, and reported from RP's side which is essential.
"
@amanohar does the below work for you? I have tried to make the API more library-like so you can control the flow and error reporting. Can you propose something else that you would prefer?

## For the create case:
(Plugin) GenerateARM

RP deploys template, handles errors

(Plugin) InitializeCluster
(Plugin) WaitForDeploy (was HealthCheck)

## For the update case:
(Plugin) GenerateARM
(Plugin) GetNodesBeforeUpdate() would do this: https://github.com/openshift/openshift-azure/blob/master/pkg/upgrade/update.go#L32-L51

RP deploys template, handles errors

(Plugin) InitializeCluster
(Plugin) WaitForUpdate() would do this: https://github.com/openshift/openshift-azure/blob/master/pkg/upgrade/update.go#L68-L85
(Plugin) UpdateInPlace() would do this https://github.com/openshift/openshift-azure/blob/master/pkg/upgrade/update.go#L87-L107

cc @jim-minter when you have time, please review. I'll work up a PR.

**Comment by jim-minter** [comment]
Can we talk about this before implementation?
It might be worth discussing quickly next week at the f2f.
I believe there's only one correct ordering of these pieces per flow and we want to rationalise and enforce it.  I also understand that we need to get the error handling right as well.

**Comment by asalkeld** [comment]
Of course @jim-minter

**Comment by asalkeld** [comment]
@jim-minter I couldn't resist, I have linked an idea for an API above.
