### ISSUE TITLE
htpasswd should have newline character at the end of osadmin line.

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-azure#589]
When adding users to htpasswd with this command:
```
htpasswd -bB /etc/origin/master/htpasswd test test
```

The /etc/origin/master/htpasswd file appends the new user to the end of the line with osadmin.
```
osadmin:<encrypted passwd>test:<encrypted passwd>
```

**Comment by vajravelu1** [comment]
Hi not sure if this is actually fixed but the new entries are still getting added to end of old entries instead of new line
in  from htpasswd binary from **httpd-tools-2.4.37-43.module+el8.5.0+13064+c4b14997.x86_64**
