### ISSUE TITLE
Rewrite hack/dns.sh in Go

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#595]
https://github.com/openshift/openshift-azure/pull/594 creates a new e2e suite for running against the RP (either our fake or the production RP). In the case of the real RP, all the DNS configuration should be handled by MSFT, in case of the fake RP we still need to setup the DNS zone and records by ourselves.

This means that we need to shell out to `hack/dns.sh` after the suite has installed a cluster which is not ideal.

**Comment by mjudeikis** [comment]
I would like try this one @kargakis if you ok with it? Do you imagine this as package in our utils folder which we can call from e2e fake RP?

**Comment by kargakis** [comment]
Go ahead @mjudeikis ! I started writting some code locally and had added it in `pkg/util/azureclient/dns` but never got a chance to push it forward.
```go
package dns

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/services/dns/mgmt/2017-10-01/dns"
)

func int64p(n int) *int64 {
	n64 := int64(n)
	return &n64
}

func CreateZone(ctx context.Context, subscriptionID, resourceGroup, dnsResourceGroup, dnsDomain string) error {
	zoneName := fmt.Sprintf("%s.%s", resourceGroup, dnsDomain)
	if _, err := dns.NewZonesClient(subscriptionID).CreateOrUpdate(ctx, dnsResourceGroup, zoneName, dns.Zone{}, "", ""); err != nil {
		return err
	}

	fqdn := fmt.Sprintf("%s.", zoneName)
	soa := dns.RecordSet{
		TTL:  int64p(3600),
		Fqdn: &fqdn,
		RecordSetProperties: &dns.RecordSetProperties{
			SoaRecord: &dns.SoaRecord{
				RefreshTime: int64p(60),
				RetryTime:   int64p(60),
				ExpireTime:  int64p(60),
				MinimumTTL:  int64p(60),
			},
		},
	}
	if _, err := dns.NewRecordSetsClient(subscriptionID).CreateOrUpdate(ctx, dnsResourceGroup, zoneName, "@", dns.SOA, soa, "", ""); err != nil {
		return err
	}

	ns := dns.RecordSet{
		TTL:  int64p(60),
		Fqdn: &fqdn,
	}
	_, err := dns.NewRecordSetsClient(subscriptionID).CreateOrUpdate(ctx, dnsResourceGroup, zoneName, "@", dns.NS, ns, "", "")
	return err
}
```

**Comment by kargakis** [comment]
@mjudeikis what's the progress on this issue? Since the artifacts PR got merged, I think this is the last blocker for enabling automated upgrade tests in a reusable way w/o needing to introduce a new openshift template in openshift/release.
