### ISSUE TITLE
Refactor azure client creation in func (u *simpleUpgrader) InitializeCluster

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#602]
`func (u *simpleUpgrader) InitializeCluster(` creates (a) an azure storage account client and (b) a storage client, inline.  It would be nice to pull the client creation out for a cleaner architecture, esp for unit testing.

At the moment, doing this for (a) is blocked by the fact that it uses the credentials stored in ctx, and we don't know if these can be made available in NewPlugin.

(b) is blocked by the fact that we need to discover the config storage account keys to create the storage client.  I don't have a clear idea about what we can do to make this cleaner but it'd be good to look into.

**Comment by jim-minter** [comment]
@pweil- @asalkeld @kargakis @amanohar @sozercan fyi

**Comment by asalkeld** [comment]
Thanks @jim-minter , I was also not a fan of creating the clients inline, but didn't see a way out of it immediately.

**Comment by kargakis** [comment]
We should try to do the same thing with the k8s client too.
