### ISSUE TITLE
VM 'ss-compute_0' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent and can establish outbound connections to Azure storage.

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#603]
==== 8< ====
I have issue with Azure instances where if I restart machines in an "vmss" they will not join again to OCP cluster.
vmss - virtual machine scale set

vmss will go into "failed" state with error message
```
VM 'ss-compute_0' has not reported status for VM agent or extensions. Please verify the VM has a running VM agent and can establish outbound connections to Azure storage
```
This is preventing to restart vmss / machines in cluster and do specific tunings and to get them again join cluster as expected.
==== 8< ====

**Comment by jim-minter** [comment]
@ekuric fyi

**Comment by jim-minter** [comment]
debug log -
couldn't ping compute-000000
in the portal, hitting restart on the instance failed
deallocate/start also didn't seem to resolve issue ("VM status blob is found but not yet populated.")
deallocate/reimage/start seems to have resolved the problem

@ekuric did you change any settings on the vm that could have prevented it coming up?

**Comment by ekuric** [comment]
@jim-minter @kargakis  prior to this problem I tried to enable accelerated networking 
```
$ az vmss deallocate -g  ekuricazurecluster --name ss-compute 
$ az vmss update --name ss-compute -g ekuricazurecluster --set virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].enableAcceleratedNetworking=true 
```
second command failed with this [error ](https://gist.githubusercontent.com/ekuric/57cc5d587d24be415742abf992914e2a/raw/a7d2d29299a691d1a8b3c8787cf66205da210537/gistfile1.txt)
what is expected - as machines does not support Accelerated networking. Not big deal I thought then, let's leave it as is, but when I wanted again to start machines in `vmss` with 

```
$ az vmss start -g  ekuricazurecluster --name ss-compute
``` 
it ended in state it is now where ```vmss``` is not active and machines in it are not joining OCP cluster.

**Comment by akrzos** [comment]
I have now also experienced this issue where rebooting a node and it does not return to the cluster.  I do not think we are changing the cluster in such a fashion that would prevent reboots so it is unclear to me why the machines do not return after a reboot.

**Comment by kargakis** [comment]
We don't support accelerated networking and we have a card about it in Jira now. Please open a new issue if you can reproduce this issue with our current setup.

**Comment by zffocussss** [comment]
> I have now also experienced this issue where rebooting a node and it does not return to the cluster. I do not think we are changing the cluster in such a fashion that would prevent reboots so it is unclear to me why the machines do not return after a reboot.

same here.my AKS nodes are running on vmss
