### ISSUE TITLE
Support more vm sizes

### ISSUE THREAD

**Issue by akrzos** [openshift/openshift-azure#614]
Currently only Standard_D2s_v3 and Standard_D4s_v3 are the only deploy-able vm sizes (without a workaround or modifying the code).

**Comment by akrzos** [comment]
Modify the code in these two places to allow other vm sizes:
https://github.com/openshift/openshift-azure/blob/master/pkg/api/types.go#L161
https://github.com/openshift/openshift-azure/blob/master/pkg/api/default.go#L4

**Comment by thekad** [comment]
This got fixed by @jim-minter's #701
