### ISSUE TITLE
Scaleup with hack/upgrade.sh seems to only work one compute node at a time

### ISSUE THREAD

**Issue by akrzos** [openshift/openshift-azure#615]
I am unsure if this a subscription limitation or if larger instances just take longer to provision but I was unable to scale up from a core cluster (3 masters, 2 infras, 2 computes) to a larger cluster (3 masters, 2 infras, 10 computes) without hitting `400 Bad Request: Failed to apply requestFuture#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded  resourceGroup=perftest15node-2`

Subsequently, I have been able to slowly scale up the cluster one compute at a time however we should be able to scale up in bulk.

**Comment by akrzos** [comment]
After the "large" scale up of 2 to 10 (Add 8 more compute nodes) failed, I attempted to scale up by 2 compute nodes and was still met with the same problem:

```
[akrzos@fedora28 openshift-azure]$ time ./hack/upgrade.sh 
...
+ go run cmd/createorupdate/createorupdate.go
INFO[2018-10-17T08:15:01-04:00] starting server on localhost:8080             resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] convert to internal                           resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] enrich                                        resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] read old config                               resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] merge old and new config                      resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] merging internal data models                  resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] validating internal data models               resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] generating configs                            resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] persist config                                resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] generating arm templates                      resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] write helpers                                 resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:01-04:00] starting update                               resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:02-04:00] applying arm template deployment              resourceGroup=perftest15node-2
INFO[2018-10-17T08:15:08-04:00] waiting for arm template deployment to complete  resourceGroup=perftest15node-2
DEBU[2018-10-17T08:30:08-04:00] 400 Bad Request: Failed to apply requestFuture#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded  resourceGroup=perftest15node-2
FATA[0906] unexpected status: 400 Bad Request           
exit status 1

real	15m12.851s
user	0m6.147s
sys	0m1.533s
```

**Comment by kargakis** [comment]
Probably the same issue as https://github.com/openshift/openshift-azure/issues/552

We are seeing slow responses from Azure.

cc @amanohar @sozercan @jim-minter 

Btw IIRC we only allow up to 5 compute nodes atm. Also, scale up is a single update to the scale set so it should create all new VMs in parallel vs one by one. We wait for each VM to turn ready serially but that should not really affect the parallelization of the update process.

**Comment by kargakis** [comment]
> Btw IIRC we only allow up to 5 compute nodes atm.

And this means that if you tried to scale up to 8 you should see a validation error. I just tried it
```console
$ ./hack/upgrade.sh 
+ set +x
+ [[ -z osadev.cloud ]]
+ [[ -z dns ]]
+ [[ ! -e _data/containerservice.yaml ]]
++ awk '/^    resourceGroup:/ { print $2 }'
+ export RESOURCEGROUP=mkargakiosa
+ RESOURCEGROUP=mkargakiosa
+ go generate ./...
bindata.go
bindata.go
+ go run cmd/createorupdate/createorupdate.go
INFO[2018-10-17T15:46:10+02:00] starting server on localhost:8080             resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] convert to internal                           resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] enrich                                        resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] read old config                               resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] merge old and new config                      resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] merging internal data models                  resourceGroup=mkargakiosa
INFO[2018-10-17T15:46:10+02:00] validating internal data models               resourceGroup=mkargakiosa
DEBU[2018-10-17T15:46:10+02:00] 400 Bad Request: Failed to apply requestinvalid properties.agentPoolProfiles["compute"].count 8  resourceGroup=mkargakiosa
FATA[0000] unexpected status: 400 Bad Request           
```

**Comment by akrzos** [comment]
> And this means that if you tried to scale up to 8 you should see a validation error. I just tried it

I avoided the validation issue by raising the limit to 30 in that piece of code (as well as to allow a larger vm size):

```
[akrzos@fedora28 openshift-azure]$ git diff pkg/api/validate.go
diff --git a/pkg/api/validate.go b/pkg/api/validate.go
index e7721332..d857563d 100644
--- a/pkg/api/validate.go
+++ b/pkg/api/validate.go
@@ -258,7 +258,7 @@ func validateAgentPoolProfile(app AgentPoolProfile, vnet *net.IPNet) (errs []err
                if !rxAgentPoolProfileName.MatchString(app.Name) {
                        errs = append(errs, fmt.Errorf("invalid properties.agentPoolProfiles[%q].name %q", app.Name, app.Name))
                }
-               if app.Count < 1 || app.Count > 5 {
+               if app.Count < 1 || app.Count > 30 {
                        errs = append(errs, fmt.Errorf("invalid properties.agentPoolProfiles[%q].count %d", app.Name, app.Count))
                }
 
@@ -276,9 +276,9 @@ func validateAgentPoolProfile(app AgentPoolProfile, vnet *net.IPNet) (errs []err
                }
        }
 
-       if _, found := DefaultVMSizeKubeArguments[app.VMSize][app.Role]; !found {
-               errs = append(errs, fmt.Errorf("invalid properties.agentPoolProfiles[%q].vmSize %q", app.Name, app.VMSize))
-       }
+       //if _, found := DefaultVMSizeKubeArguments[app.VMSize][app.Role]; !found {
+       //      errs = append(errs, fmt.Errorf("invalid properties.agentPoolProfiles[%q].vmSize %q", app.Name, app.VMSize))
+       //}
 
        if !isValidIPV4CIDR(app.SubnetCIDR) {
                errs = append(errs, fmt.Errorf("invalid properties.agentPoolProfiles[%q].subnetCidr %q", app.Name, app.SubnetCIDR))
```

Right now the issue I believe is mostly that deploying seems to be hit or miss with the azuredeploy template "timing out" and the chance for greater success seems to be with smaller node count.

**Comment by kargakis** [comment]
Closing since there is no concrete issue here to try to fix atm

**Comment by amanohar** [comment]
@kargakis @akrzos, error returned by ARM (and the RP) is BadRequest 400 and the following. The plugin should have received the following error response or can query ARM with deployment id to get error details:
```
{
  "statusCode": "BadRequest",
  "serviceRequestId": "...",
  "statusMessage": "{\"error\":{\"code\":\"InvalidParameter\",
   \"target\":\"dataDisk.managedDisk.storageAccountType\",
   \"message\":\"Storage account type 'StandardSSD_LRS' is 
      supported by Microsoft.Compute API version 2018-04-01 and above\"}}"
}
```

**Comment by kargakis** [comment]
@amanohar something along the lines of https://github.com/openshift/openshift-azure/pull/653? Unclear what kind of query to make to ARM to get more error details.

**Comment by amanohar** [comment]
@kargakis here is the reference to rest docs for API to query results of a deployment (most useful in case of long running ops):
https://docs.microsoft.com/en-us/rest/api/resources/deploymentoperations
Overall: https://docs.microsoft.com/en-us/rest/api/resources/

**Comment by kargakis** [comment]
Using the go sdk, [`deployments.CreateOrUpdate`](https://github.com/openshift/openshift-azure/blob/f9ddeff1ee3a55c661e580afa63ccab12318ef67/pkg/fakerp/fakerp.go#L115) returns a future out of which we can get a [DeploymentExtended](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources#DeploymentExtended) type. Is then [`DeploymentExtended.Properties.CorrelationID`](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources#DeploymentPropertiesExtended) the correct ID to be passing to the [`DeploymentOperations`](https://godoc.org/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources#DeploymentOperationsClient.Get) client?

**Comment by akrzos** [comment]
> @kargakis @akrzos, error returned by ARM (and the RP) is BadRequest 400 and the following. The plugin should have received the following error response or can query ARM with deployment id to get error details:
> 
> ```
> {
>   "statusCode": "BadRequest",
>   "serviceRequestId": "...",
>   "statusMessage": "{\"error\":{\"code\":\"InvalidParameter\",
>    \"target\":\"dataDisk.managedDisk.storageAccountType\",
>    \"message\":\"Storage account type 'StandardSSD_LRS' is 
>       supported by Microsoft.Compute API version 2018-04-01 and above\"}}"
> }
> ```

Hey everyone to follow up on this issue, I want to be clear that we did not modify the type of disks being requested thus I am not sure if this error message is the one that caused the failures I had mentioned above.  The failures seem related to the fact that if we add accelerated networking to the ARM template and use the appropriately sized vm (Standard_D4s_v3 or larger) we usually receive a timeout.  So much so that it was basically impossible to deploy a 15 node cluster.  I suspect the issue is with trying to request 15 instances with accelerated networking at once via an ARM template or potentially since the template uses VM scale sets.

On the flip side I believe it was asked why we are turning on accelerated networking, so to answer that question, we see a reduction of latency between 300-600 usec for TCP benchmarks and  100-350 usec for UDP benchmarks.

**Comment by kargakis** [comment]
Not sure about the scope of this issue anymore, please open a new one with any issue you are encountering.
