### ISSUE TITLE
Cosmetic issue: scale up/scale down compute node index

### ISSUE THREAD

**Issue by akrzos** [openshift/openshift-azure#617]
Potentially not an issue, however noted since node naming could become confusing in large enough environments.  Compute nodes increment in the azure portal as compute_0, compute_1, ... compute_9, compute_10 and so forth.  In openshift-azure as well as in the OpenShift cli on a cluster the compute nodes increment as compute-000000, compute-000001,..compute-000009, compute-00000a, compute-00000b rather than the same "index".  Eventually we will get to compute-000010 which will not be the same as compute_10, this increases the chance for a mistake on which node is which node operationally.

**Comment by kargakis** [comment]
Hrm, VM names (compute-000000, compute-000001, etc.) are set by scale sets. Not sure we can change them. `ss-compute-0` is confusing and I am not sure why they have it like that in the portal :)

**Comment by asalkeld** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids

**Comment by kargakis** [comment]
We can't change this, closing
