### ISSUE TITLE
Rewrite hack/aad.sh in Go

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#618]
Similar to https://github.com/openshift/openshift-azure/issues/595, the more of hack/create.sh we move out of bash into Go, the better it's going to be for our e2e framework. Once we rewrite hack/aad.sh (and hack/dns.sh) it should be very easy to get rid of hack/create.sh altogether.

/kind cleanup

**Comment by asalkeld** [comment]
@kargakis unless you have started on this, I can do it.

**Comment by mjudeikis** [comment]
@asalkeld I started #595 but got stuck. https://github.com/openshift/openshift-azure/pull/621 
Pushed so you know where I am :)
