### ISSUE TITLE
DNS wildcard not set up to point to a router instance.

### ISSUE THREAD

**Issue by jmencak** [openshift/openshift-azure#627]
I was handed off an azure OCP cluster to test the router performance installed by openshift/openshift-azure.

Routing was not set up after the install finished, and I had to manually add wildcard DNS entries to point to the first router instance (there were two routers installed, as we had two infra nodes).

Is there a way to point automatically to the first router?  Anything that we missed during the install?

/cc @akrzos

**Comment by mjudeikis** [comment]
did you used `create.sh` or normal azure api? if create.sh ran to the end `dns.sh` had to create it. By ancy change you have create.sh output?

**Comment by mjudeikis** [comment]
This might subscription issue. Can you send me details of what you use as credentials (sub, tenant)? 
ping me pm (m.j et redhat.com)

**Comment by kargakis** [comment]
Yes, this is a subscription issue.

**Comment by mjudeikis** [comment]
@akrzos I think this is a documentation issue. we should clearly state that code under this repo can be fully used only if you have pre-reqs in the subscription (golden images, DNS Rg, etc). 
And for any external usage, it should be used with azure api/sdk

**Comment by jim-minter** [comment]
@ehashman dumb documentation request - please can you make it clear in a polite way near the top of README.md that if you don't have access to our CI and Azure subscription, running openshift-azure is probably not for you.
