### ISSUE TITLE
CI is blocked

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#629]
Ci is blocked because test-base image build fails with `chmod -R xxx /go` 
To replicate locally:
https://gist.github.com/mjudeikis/32338908fae24e800e6676f12c3c5341 

/kind bug

**Comment by mjudeikis** [comment]
we see this in our Ci too :/
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/628/pull-ci-openshift-openshift-azure-master-verify/319

**Comment by kargakis** [comment]
Instead of letting CI blocked we should revert the dockerfile changes that were made to support conformance testing and move that into a separate image so we can try and fix out of bound.

**Comment by mjudeikis** [comment]
I tried this. This didnt helped. Its other issue with ocp tooling...
conformance change is nkt related to this

**Comment by kargakis** [comment]
Fixed by https://github.com/openshift/release/pull/1977
