### ISSUE TITLE
conformance tests for master are broken

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#635]
```
error: could not run steps: template e2e-azure-conformance has required parameter TEST_COMMAND which is not defined
```
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/branch-ci-openshift-openshift-azure-master-e2e-azure-conformance/
/assign mjudeikis 
/kind bug

**Comment by kargakis** [comment]
@mjudeikis fixed by https://github.com/openshift/release/pull/2034?

**Comment by mjudeikis** [comment]
/close
yes
