### ISSUE TITLE
rhel node image build job fails during disk revoke access

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#650]
The azure rhel node image build jobs are currently failing with the following error:

```
TASK [revoke disk sas url] *****************************************************
Tuesday 23 October 2018  22:27:47 +0000 (0:04:44.201)       0:18:56.342 ******* 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["az", "disk", "revoke-access", "--ids", "/subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/ci-op-j7y49vv7-c883c-201810232208/providers/Microsoft.Compute/disks/vm_disk1_b9e42e1a2fc640fa89b01b4703e0d2cf"], "delta": "0:00:33.100259", "end": "2018-10-23 22:28:21.247712", "msg": "non-zero return code", "rc": 1, "start": "2018-10-23 22:27:48.147453", "stderr": "ERROR: Deployment failed. Correlation ID: 110632e1-60a8-4ea8-84f1-175b07489564. The response from long running operation does not contain a body.", "stderr_lines": ["ERROR: Deployment failed. Correlation ID: 110632e1-60a8-4ea8-84f1-175b07489564. The response from long running operation does not contain a body."], "stdout": "", "stdout_lines": []}
```

This seems to be an issue [here](https://github.com/openshift/openshift-ansible/blob/ffdce7c6057fa5c07ee1e10d4eb1654736e66624/playbooks/azure/openshift-cluster/tasks/create_blob_from_vm.yml#L45) 

artifacts: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/azure-build-node-image-rhel-310/74/

**Comment by charlesakalugwu** [comment]
I had a look at this and this seems to be an issue from the disk revoke-access http endpoint which seems to suddenly starts sending back empty response bodies. If debug is turned on, one can see that the request actually succeeds with 200 OK but with an empty body. This affects versions `2.0.47` through `2.0.49` of the azure cli.

I have opened an issue to track this here: https://github.com/Azure/azure-cli/issues/7671

**Comment by kargakis** [comment]
@kwoodson fyi

**Comment by kargakis** [comment]
Shouldn't be an issue anymore?
