### ISSUE TITLE
centos node image build job fails with unable to retrieve existing template instance

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#652]
The azure centos node image build jobs are currently failing with the following error:

```
error: could not run steps: could not wait for template instance to be ready: unable to retrieve existing template instance: templateinstances.template.openshift.io "build-node-image" not found
```

artifacts: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/azure-build-node-image-centos-310/12/

**Comment by kargakis** [comment]
@bbguimaraes any idea what's going on here?

**Comment by kargakis** [comment]
Still an issue
