### ISSUE TITLE
Unknown network allocation error.

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#661]
```
time="2018-10-25T14:19:57Z" level=debug msg="400 Bad Request: Failed to apply requestCode=\"NetworkingInternalOperationError\" Message=\"Unknown network allocation error.\"" resourceGroup=ci-op-lb5vf50g-226a1
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/660/pull-ci-openshift-openshift-azure-master-e2e-azure-upgrade/5/build-log.txt

/kind test-flake
@amanohar @sozercan  any idea what's going on here?

**Comment by amanohar** [comment]
@kargakis I looked into and the error happening during VMSS and NRP communication. I am following up with the VMSS team (tracked via an incident) to understand the root cause.

**Comment by thekad** [comment]
@amanohar any updates on this?

**Comment by jim-minter** [comment]
haven't seen this recently, closing

**Comment by charlesakalugwu** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1802/pull-ci-azure-master-upgrade-v5.2/244/build-log.txt in #1802

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1853/pull-ci-azure-master-upgrade-v5.2/439/build-log.txt #1853

**Comment by ehashman** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1853/pull-ci-azure-master-upgrade-v7.0/1/build-log.txt also #1853

**Comment by m1kola** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1860/pull-ci-azure-master-upgrade-v7.0/49/build-log.txt in #1860

**Comment by asalkeld** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/2044/pull-ci-azure-master-upgrade-v7.1/313
