### ISSUE TITLE
dedicated admin should use TestConfig.RunningUnderTest

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#663]
Now #554 is merged, translate.go should use TestConfig.RunningUnderTest to gate statically adding users into customer-{admins,readers} groups, not `if cs.Config.CustomerReaderPasswd != ""`

**Comment by jim-minter** [comment]
Oh, I see the problem - TestConfig.RunningUnderTest isn't available in the context of the sync pod running.

**Comment by jim-minter** [comment]
Should we consider creating a RunningUnderTest field in the Config for this @kargakis?

**Comment by kargakis** [comment]
> Should we consider creating a RunningUnderTest field in the Config for this @kargakis?

Certainly preferrable than trying to keep the sync environment in sync.
