### ISSUE TITLE
Structured errors for plugin CreateOrUpdate workflow

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#672]
As an RP engineer I would like to better report at what point a long-running plugin CreateOrUpdate execution failed.  Adding structured wrapped errors with a limited number of different error codes would help here.

Create something like the following in pkg/api/plugin.go:

```
type PluginStep string

const (
	PluginStepFoo PluginStep = "foo"
	...
)

type PluginError struct {
	Err error
	Step PluginStep
}

var _ error := &PluginError{}

func (pe *PluginError) Error() string {
	return string(pe.Step)+": "+pe.Err.Error()
}
```

The intention in the above API is we will not nest PluginErrors, even though it is feasible in principle.

At least each of the following should probably be differentiated steps:
* Update (pre-deploy drain)
* Deploy
* InitializeCluster
* Update (post-deploy readiness)
* Update (master VM rotation)
* Update (infra VM rotation)
* Update (compute VM rotation)
* Health check (wait for healthz)
* Health check (wait for nodes)
* Health check (daemonsets)
* Health check (deployments)
* Health check (console)

Find a maintainable way to implement the above and implement.  Potentially, judicious changing of functions associated with "steps" such that their plugin-internal interfaces return `*PluginError` instead of `error` might be an option.

**Comment by jim-minter** [comment]
@amanohar broadly as discussed - does the above work for you?

**Comment by jim-minter** [comment]
@asalkeld if you can prioritise this jointly with your etcd work that would be grand

**Comment by asalkeld** [comment]
OK, @jim-minter , it shouldn't take long. I'll get a PR up soon.

**Comment by amanohar** [comment]
@jim-minter yes this works. Overall,  lgtm. 

Would be helpful get more granularity in Update (master, infra, compute VM rotation) steps. E.g. if the failure happened during the VM operations step (deallocate, delete, reimage) vs waiting for Ready step.

**Comment by asalkeld** [comment]
reopened because of https://github.com/openshift/openshift-azure/pull/674#discussion_r230645832

**Comment by asalkeld** [comment]
there is another issue, so closing this one.

/close
