### ISSUE TITLE
CreateOrUpdate should return type 'PluginError' instead of 'error'

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#694]
https://github.com/openshift/openshift-azure/blob/master/pkg/plugin/plugin.go#L103 should return type 'PluginError' instead of 'error'. This is needed so that RP/service: Can expect error to be in an opinionated format and custom passing will be done on `Err` field of 'PluginError' by the RP.

cc: @asalkeld @jim-minter

**Comment by amanohar** [comment]
Edit: I realize that ARM error can also be returned by callback function: `api.DeployFn`. So essentially 2 kinds of errors can be returned by `CreateOrUpdate`. The original intent of opening this issue was to ensure that only specific kinds of errors are returned by plugin.

Option are:
1) Plugin continues as if and RP parses the error and expected errors to be in certain formats only
2) Plugin always returns all error wrapped in 'PluginError'

**Comment by asalkeld** [comment]
Hi @amanohar `error` is the official interface for the PluginError struct. To get at the attributes do this:
```

	err = p.CreateOrUpdate(ctx, cs, azuretemplate, oldCs != nil, deployer)
	if err != nil {
		perr, ok := err.(*api.PluginError)
		if ok {
			log.Warn(perr.Step, perr.Err.Error())
		}
		return nil, err
	}

```

**Comment by amanohar** [comment]
Hi @asalkeld, I am aware of this method of casting (and using it as a work around for now) but the request as mentioned above is for plugin to return the error in an opinionated struct. This way the service is always ensured that error returned by the plugin contains the error and `step`.

**Comment by jim-minter** [comment]
@thekad can you pick this up please?

**Comment by thekad** [comment]
@jim-minter @asalkeld in case we do want that change, I opened #712 to deal with it
