### ISSUE TITLE
disable ability to use StandardD2sV3 except when running in test

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#707]
As a quality engineer I want to be able to run OSA using a tiny VM for test purposes or CI.
As an end user I don't want to be able to run OSA using a tiny VM because it almost certainly won't be powerful enough for me and I'll raise a support ticket because it breaks.

I think we should refuse to validate use of StandardD2sV3 except when running in test, but that implies making our validation code dependent on configuration, which might open a can of works.  @kargakis @pweil- what's your take?

**Comment by kargakis** [comment]
Is this just for cost-saving? I don't see any gain in it.

**Comment by pweil-** [comment]
This is the use case where a configurable would make this a little easier.   Is the cost savings big enough to justify it?  

Should we consider something like an `--insecure-skip-tls-verify` type of flag where it is `--ignore-validation-errors` and it is undocumented (or documented to never use it)?  If we have to go down this route I'd like to find a more generic way of doing it than putting special cases in different parts of the code.

**Comment by pweil-** [comment]
and 2 seconds later I already don't like the suggestion above since it will make life harder narrowing down real validation errors :-)

**Comment by thekad** [comment]
@kargakis I think it has less to do with cost-savings and more to do with the fact that clusters with StandardD2sV3 wouldn't be able to serve any real world workloads. It is really only useful for running our QA, are you saying we should just get rid of D2s altogether and run our tests on D4s?

**Comment by kargakis** [comment]
We should be running our tests on all supported sizes or at least a
representative subset, maybe with a lower frequency on higher sizes and
higher frequency on lower sizes.
