### ISSUE TITLE
Start using azure mocked client

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#725]
See https://github.com/Azure/azure-sdk-for-go/issues/409#issuecomment-438046820

Then we can stop generating our own fake client.

/area tests
/kind cleanup

**Comment by kargakis** [comment]
> It will ship in v23 of the SDK at the end of this month. Take a look at [#3282](https://github.com/Azure/azure-sdk-for-go/pull/3282) to see the changes, should merge into latest later today.

**Comment by kargakis** [comment]
our sdk got bumped to v24 with https://github.com/openshift/openshift-azure/pull/1064

**Comment by mjudeikis** [comment]
renaming to fit work left doing

**Comment by jim-minter** [comment]
what mocked client? :-(
looks like they just provide fat interfaces for you to implement...
