### ISSUE TITLE
Provide more detailed errors from cluster Update

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#729]
We currently see errors from pkg cluster's Update method which don't provide a lot of information.

```
Expected error:
      <*api.PluginError | 0xc420762940>: {
          Err: {Code: "", Message: "", Target: nil, Details: nil, InnerError: nil, AdditionalInfo: nil},
          Step: "UpdateComputeVMRotation",
      }
      UpdateComputeVMRotation: Code="" Message=""
  not to have occurred
```

We should probably provide more detailed errors out of those Update steps.

@kargakis

**Comment by kargakis** [comment]
@asalkeld @jim-minter 

/kind feature

**Comment by asalkeld** [comment]
that error should have something valid
```
		err = u.updatePlusOne(ctx, cs, api.AgentPoolProfileRoleCompute)
		if err != nil {
			return &api.PluginError{Err: err, Step: api.PluginStepUpdateComputeVMRotation}
		}
```

**Comment by thekad** [comment]
This is being handled on #714 I believe

**Comment by kargakis** [comment]
> that error should have something valid

Looks like a sdk issue. Also since #714 is a thing, I am closing this one.
