### ISSUE TITLE
Compute scale set CSE script is being re-executed on scale up

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#731]
We ran into an issue where it appeared that the node startup scripts were being reapplied to the vms upon update. 

We've been under the understanding that these scripts are run only once the first time a VM is created and never again.

We encountered this issue when developing key rotation e2e tests.

```
VM has reported a failure when processing extension 'cse'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1 [stdout] [stderr] + SERVICE_TYPE=origin + '[' -f /etc/sysconfig/atomic-openshift-node ']' + SERVICE_TYPE=atomic-openshift + unlink /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt unlink: cannot unlink '/etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt': No such file or directory ".
```

@jim-minter @kargakis

**Comment by kargakis** [comment]
This issue came up during @charlesakalugwu's [key rotation upgrade test](https://github.com/openshift/openshift-azure/pull/726). During the upgrade, when the compute scaleset is rotated for some reason this issue happens. All VMs seem to come up correctly (master, infra, even the new compute VM is joining the cluster).

**Comment by kargakis** [comment]
I don't think this question is an issue in openshift-azure and this issue tracker is probably the wrong venue. Maybe take this question in the openshiftazure slack?

**Comment by mjudeikis** [comment]
/open
This is repeatable and reproducible. let's reopen so we can track progress, and if we end up with non-azure issue, we can move. But now we don't know where the issue is. 

I was thinking this might be related to our update code but now think about this less and less.
1. Tried to change the order of upgrades (master, compute, infra) as was thinking something leaks to update blob - No luck.
2. Compute is being created with count=1. Changes to Count=2 to start with as was thinking about how we do "PlussOne" Updates - No luck. 
3. Checked logs on compute0 just to check if we can get confirmation about this - no luck. Logs does not show anything. I was expecting confirmation on a script running twice. - No luck

At this point, because compute and infra is theoretically the same I don't know what might be the issue.

@sozercan reported that logging stack somehow cant connect from compute0 to Geneva. All other nodes connect properly. This raises the question what is different about how we configure Compute nodes compared to infra nodes, and to be specific - first compute node we bootstrap. As if we scale and add compute1 - it works just fine. 

cc @charlesakalugwu @kargakis

**Comment by kargakis** [comment]
Adjusted the title to match closely the issue we are seeing

**Comment by mjudeikis** [comment]
Looks like script run on the last node for some reason.
Node still responds after running, but I can't ssh anymore into it.
And azure update ssh keys fails:
```
→ az vmss extension set \
>   --vmss-name ss-compute \
>   -g mjudeikis-t \
>   -n VMAccessForLinux \
>   --publisher Microsoft.OSTCExtensions \
>   --version 1.4 \
>   --protected-settings "{\"username\":\"cloud-user\", \"ssh_key\":\"$(cat ~/.ssh/aos-azure.pub)\"}"
'ascii' codec can't encode character u'\u2018' in position 370: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 345, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 330, in execute
    result = LongRunningOperation(self.cli_ctx, 'Starting {}'.format(cmd.name))(result)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 579, in __call__
    handle_long_running_operation_exception(client_exception)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/arm.py", line 126, in handle_long_running_operation_exception
    error_message = '{} {}'.format(error_message, message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 370: ordinal not in range(128)
```

**Comment by charlesakalugwu** [comment]
I think the problem here is broader than unlink (or the custom script extension's script) not being re-entrant. The main issue here is that custom script extensions are being re-executed on older vms when the compute scale set is scaled up. If the cse script isn't written to be idempotent then the re-execution causes a failure and leads to a scale set in a failed state. I'll update the title of this issue to reflect that

**Comment by mjudeikis** [comment]
yes, but the thing is that it does not run on all VMSS VMs (as per my current debugging, but I might be wrong), but only on the last one.

**Comment by mjudeikis** [comment]
If I "update" compute first (I didnt expect this to work) I dont get arm failure:
```
time="2018-12-07T15:41:09Z" level=info msg="write helpers"                                                                                                                                                                                                                        [5/1776]
time="2018-12-07T15:41:09Z" level=info msg="checking marketplace agreement"                                                                                                                                                                                                              
time="2018-12-07T15:41:10Z" level=info msg="starting update"                                                                                                                                                                                                                             
time="2018-12-07T15:41:11Z" level=info msg="applying arm template deployment"                                                                                                                                                                                                            
time="2018-12-07T15:41:22Z" level=info msg="waiting for arm template deployment to complete"                                                                                                                                                                                             
time="2018-12-07T15:41:50Z" level=info msg="setting ss-compute capacity to 3"                                                                                                                                                                                                            
time="2018-12-07T15:41:52Z" level=info msg="update fired"
time="2018-12-07T15:41:52Z" level=info msg=WaitForCompletionRef
time="2018-12-07T15:44:53Z" level=info msg=listVMs
time="2018-12-07T15:44:53Z" level=info msg=updatedList
time="2018-12-07T15:44:53Z" level=info msg="waiting for compute-000002 to be ready"
time="2018-12-07T15:45:27Z" level=info msg="draining compute-000000"
time="2018-12-07T15:45:27Z" level=info msg="deleting compute-000000"
time="2018-12-07T15:46:29Z" level=info msg="setting ss-compute capacity to 3"
time="2018-12-07T15:46:31Z" level=info msg="update fired"
time="2018-12-07T15:46:31Z" level=info msg=WaitForCompletionRef

• Failure [567.452 seconds]
Key Rotation E2E tests [KeyRotation] [Fake] [LongRunning]
/home/mjudeiki/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:23
  should be possible to maintain a healthy cluster after rotating all credentials [It]
  /home/mjudeiki/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:36

  Expected error:
      <*api.PluginError | 0xc0006ac700>: {                                                                                                                                                                                                                                               
          Err: {Code: "", Message: "", Target: nil, Details: nil, InnerError: nil, AdditionalInfo: nil},                                                                                                                                                                                 
          Step: "UpdatePlusOneWaitForReady",
      }
      UpdatePlusOneWaitForReady: Code="" Message=""                                                                                                                                                                                                                                      
  not to have occurred

  /home/mjudeiki/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:70                                                                                                                                                                                     
------------------------------
SSSSSSSSSSSSS                                                                                                                                                                                                                                                                            

Summarizing 1 Failure:                                                                                                                                                                                                                                                                   

[Fail] Key Rotation E2E tests [KeyRotation] [Fake] [LongRunning] [It] should be possible to maintain a healthy cluster after rotating all credentials                                                                                                                                    
/home/mjudeiki/go/src/github.com/openshift/openshift-azure/test/e2e/specs/fakerp/keyrotation.go:70

Ran 1 of 23 Specs in 567.453 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 22 Skipped
```
Now where might be an issue that we change something in UpdateBlob when updating master which triggers un-expected behavior in Compute nodes

**Comment by jim-minter** [comment]
Please can this be updated with clear instructions on how to recreate this issue?  I'm not seeing it.

**Comment by kargakis** [comment]
@jim-minter this is 100% reproducible when running the key rotation test.
`make e2e-keyrotation` in master.

**Comment by kargakis** [comment]
Note that the key rotation test will take some time. I think @charlesakalugwu said it's also reproducible in his scaleup test which should be faster than the key rotation test.

**Comment by jim-minter** [comment]
I don't believe this is reproducible in the scale up test, but it is in the key rotation test.
The ssh issues are because the key rotation changes the ssh key ;-).  I've sent @charlesakalugwu a patch which keeps the old key around on disk to ease debugging in that scenario.
I suspect/fear that the k8s cloud provider code is calling UpdateInstances behind our back, and that is causing a) the staged scaleset model change to be applied outside of our workflow, and b) the CSE to run a second time.  My theory as to why it only happens to ss-compute is because that's what's configured in the cloud provider configuration.  This is a serious issue and I've e-mailed MSFT about it.

**Comment by jim-minter** [comment]
fixed with the update rework
