### ISSUE TITLE
Validation for invalid router profile name does not fail fast

### ISSUE THREAD

**Issue by amanohar** [openshift/openshift-azure#745]
I mistakenly set the router profile to be:
```
"routerProfiles": [
      {
        "name": "router1"
      }
    ]
```

This should fail in the validation input data model from the caller aka in the front. However, it fails during internal data model validation only. Which means the RP creates a resource and then this validation happens in the backend and customer will need to delete the failed resource. 

This validation should happen in the versioned data model caller sends to the service.

**Comment by kargakis** [comment]
@amanohar @jim-minter how does this affect merging? I assume we should be merging the external type before validating it. Is there any value in merging and validating internally then? Requests passing external validation should not fail internal?

**Comment by kargakis** [comment]
@amanohar another question: isn't it possible for the RP to cleanup the resource if it fails internal validation?

**Comment by amanohar** [comment]
@kargakis If validation fails in the frontend then the resource is not saved. However, if validation fails in the backend then a resource is not implicitly deleted during a PUT call.

In this specific case since plugin expects the value to be `default` this validation can be done on the PUT request/aka version API model. HTH.

**Comment by jim-minter** [comment]
@Makdaam I *think* it's just the rp.FQDN check that needs to be guarded by `externalOnly` - @sozercan do you agree?

**Comment by Makdaam** [comment]
@jim-minter I'm not sure the condition on rp.FQDN is necessary, it will verify as valid if FQDN=="".
On the other hand the RPs don't have to be set on the frontend, and a nil RP should verfify as valid according to the unit tests.

A review of unit tests in #911 by @amanohar or @sozercan would be very welcome.
