### ISSUE TITLE
customer-admin-controller in ImagePullBackOff flake

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#767]
CI run failed because it couldn't pull the customer-admin-controller image
`openshift-infra                     customer-admin-controller-776f7fd8c5-wcgjq     0/1       ImagePullBackOff   0          24m       10.130.0.52   master-000000`
`openshift-infra                     23m         23m          2         customer-admin-controller-776f7fd8c5-wcgjq.1568f493c0f2f3e6     Pod                     spec.containers{customer-admin-controller}     Warning   Failed                    kubelet, master-000000               Failed to pull image "registry.svc.ci.openshift.org/ci-op-cvgtdl2q/stable:azure-controllers": rpc error: code = Unknown desc = Error: image ci-op-cvgtdl2q/stable:azure-controllers not found`

**Comment by jim-minter** [comment]
happened here as well:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/764/pull-ci-openshift-openshift-azure-master-e2e-azure/850

**Comment by kargakis** [comment]
This may also be an issue with the build actually failing to complete. Next time you encounter it, try to `oc get pods` in the test namespace.
