### ISSUE TITLE
Check if mdsd-customerdata-config.yaml is populated by naive substitution and avoid if possible

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#776]
We have stanzas like `<IdentityComponent name="SubscriptionId">_SUBSCRIPTIONID_</IdentityComponent>` in mdsd-customerdata-config.yaml - investigate how these are populated: if done by naive substitution, it would be preferable to template them in directly using an XML parser in the sync plugin.

@mjudeikis

**Comment by mjudeikis** [comment]
yes, its just XML with replacing done in bootstrap script on startup
https://github.com/Azure/moffet/blob/master/logging/images/mdsd/bootstrap.sh#L27

We could move all this logic into our code base if we want so

**Comment by mjudeikis** [comment]
These 2 looks like candidated for code reuse:
```
"gopkg.in/xmlpath.v2"
"encoding/xml"
```

Its getting more complicated as its "XML inside of JSON/YAML":
```
"ConfigMap/openshift-azure-logging/mdsd-customerdata-config": {
		{
			JsonPath:      jsonpath.MustCompile("$.data.'mdsd.xml'"),
			XMLNesterPath: xmlpath.MustCompile("/MonitoringManagement/Management/Identity/IdentityComponent[@name='RPSector']"),
			Template:      "{{ String (CertAsBytes .Config.Certificates.Ca.Cert) }}",
		},
```

TranslateXML:
```
var nestedObject interface{}
	err = xml.Unmarshal(nestedBytes, &nestedObject)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(nestedBytes))
	spew.Dump(nestedObject)
	return nil
```

And this part is where I got stuck. We need to `path.Set` implementation for `xmlplath` which challenge I lack the background to take on :/
