### ISSUE TITLE
make sure we can restore large etcd snapshots

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#785]
From a code review comment: https://github.com/openshift/openshift-azure/pull/779#discussion_r236485229

If you save the snapshot to the same disk, presumably it should work for dbs up to approx 1/2 of the disk size? Presumably any bigger will actually require a temporary restore disk or something? Suggest you implement the former and open a story for the latter.

**Comment by jim-minter** [comment]
closing, we're not going to hit this :)
