### ISSUE TITLE
clean prometheus config

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#79]
Prometheus currently has default config to scrape all components, including control plain. need to stip it down.
![screenshot from 2018-07-17 12-08-09](https://user-images.githubusercontent.com/3225744/42813837-2b017d28-89ba-11e8-90c1-5528fb196a46.png)

**Comment by kargakis** [comment]
Default prometheus is supposed to scrape the control plane. It seems we need to fix the endpoints to scrape the components correctly.

**Comment by mjudeikis** [comment]
yes :) was cleaning router scape config and this came up.
