### ISSUE TITLE
no gingko found

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#804]
```
2018/11/29 10:57:57 Container setup in pod e2e-azure completed successfully
Cluster created, starting tests
FOCUS="\[AzureClusterReader\]|\[CustomerAdmin\]|\[EndUser\]" ./hack/e2e.sh
FAIL	github.com/openshift/openshift-azure/test/e2e [setup failed]
# github.com/openshift/openshift-azure/test/e2e
test/e2e/e2e_test.go:10:2: cannot find package "github.com/onsi/ginkgo" in any of:
	/go/src/github.com/openshift/openshift-azure/vendor/github.com/onsi/ginkgo (vendor tree)
	/usr/local/go/src/github.com/onsi/ginkgo (from $GOROOT)
	/go/src/github.com/onsi/ginkgo (from $GOPATH)
```

Something is broken with $GOPATH or how we call test

/flake

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/773/pull-ci-openshift-openshift-azure-master-e2e-azure/1061

**Comment by mjudeikis** [comment]
I suspect this will be again some image caching magic

**Comment by mjudeikis** [comment]
again:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/806/pull-ci-openshift-openshift-azure-master-e2e-azure/1069

**Comment by kargakis** [comment]
Seeing different failure modes of this
```
package github.com/openshift/openshift-azure/test/e2e (test)
	imports github.com/openshift/openshift-azure/test/e2e/specs
	imports github.com/openshift/openshift-azure/test/clients/openshift
	imports k8s.io/api/authorization/v1: cannot find package "k8s.io/api/authorization/v1" in any of:
	/go/src/github.com/openshift/openshift-azure/vendor/k8s.io/api/authorization/v1 (vendor tree)
	/usr/local/go/src/k8s.io/api/authorization/v1 (from $GOROOT)
	/go/src/k8s.io/api/authorization/v1 (from $GOPATH)
FAIL	github.com/openshift/openshift-azure/test/e2e [setup failed]
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/805/pull-ci-openshift-openshift-azure-master-e2e-azure/1067/build-log.txt
@jim-minter started happening ever since your hack/e2e.sh refactor.

**Comment by mjudeikis** [comment]
Trying to catch this in action... One other option could be our trap is not doing its work and we dont see the result. In particual `cp` operation so test container does not have all required files 
```
trap 'rc=$?; if [[ $rc -ne 0 || -n "$TEST_IN_PRODUCTION" ]]; then
          touch /tmp/shared/exit;
        fi;
        cp -r /go/src/github.com/openshift/openshift-azure /tmp/shared &>/dev/null
        exit $rc' EXIT
        trap 'kill $(jobs -p); exit 0' TERM
```

**Comment by mjudeikis** [comment]
https://github.com/openshift/release/pull/2257

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/830/pull-ci-openshift-openshift-azure-master-e2e-azure/1157

**Comment by mjudeikis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/840/pull-ci-openshift-openshift-azure-master-e2e-azure/1226

**Comment by kargakis** [comment]
Merged https://github.com/openshift/release/pull/2325, hoping to fix this issue.

**Comment by kargakis** [comment]
Reopen if still an issue
