### ISSUE TITLE
Update UpdateOSACluster method after admin API lands

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/openshift-azure#807]
Once #794 is merged and the admin API lands, we need to remove the (*Client).UpdateOSACluster method in `test/clients/azure/osa.go`. The availability of the admin API will provide us with the ability to conduct admin-based updates to a cluster via the real RP.

Until then, only the Key rotation e2e tests and similar tests are allowed to use the aforementioned method

In addition, the `deleteSecrets` function in test/e2e/specs/fakerp/keyrotation.go should move into a newly created function inside the plugin, which would be listed in the external plugin interface, which would be responsible for resetting the config struct secret values and calling Update on the cluster.

/cc @jim-minter @kargakis

**Comment by kargakis** [comment]
UpdateOSACluster is not going to be removed, it should use the [admin client](https://github.com/openshift/openshift-azure/blob/77fbbf665c0f05263862c9f43dcda24021669257/pkg/api/admin/api/client.go#L84) to send update requests in the fake RP (and hopefully the prod RP in the future).

**Comment by kargakis** [comment]
> UpdateOSACluster is not going to be removed, it should use the [admin client](https://github.com/openshift/openshift-azure/blob/77fbbf665c0f05263862c9f43dcda24021669257/pkg/api/admin/api/client.go#L84) to send update requests in the fake RP (and hopefully the prod RP in the future).

Actually, it cannot use the admin client until https://github.com/openshift/openshift-azure/pull/821 gets merged. Initially, it can use the customer client.
