### ISSUE TITLE
fake rp writes partial manifest in the filesystem after successful update

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#828]
/kind bug

**Comment by Makdaam** [comment]
Already fixed by @kargakis. /close

**Comment by kargakis** [comment]
Yeah, this is fixed though there is a different tangential issue. Will open a separate issue.

@Makdaam fyi, in order to use the bot correctly, you need to put its commands in their own lines.

/close

**Comment by kargakis** [comment]
Opened https://github.com/openshift/openshift-azure/issues/908
