### ISSUE TITLE
move prometheus-forwarder out of the cluster healthcheck

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#851]
```
time="2018-12-06T05:46:09Z" level=info msg="checking statefulset openshift-azure-monitoring/prometheus-forwarder"
time="2018-12-06T06:08:53Z" level=fatal msg="containerservice.OpenShiftManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded"
```
Similar to the rest of the promehteus stack

/kind test-flake
@mjudeikis

**Comment by mjudeikis** [comment]
Do you have cluster or artifacts?

**Comment by kargakis** [comment]
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/813/pull-ci-openshift-openshift-azure-master-e2e-azure/1214/artifacts/e2e-azure/

**Comment by mjudeikis** [comment]
/close
old code in @asalkeld PR. forwarder as a component was removed in favor of metrics-bridge.

**Comment by kargakis** [comment]
yeah, saw that now, thanks
