### ISSUE TITLE
no Location header in response in e2e tests

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#852]
When running our CI job with RUNNING_UNDER_TEST unset
```
  Expected error:
      <*errors.errorString | 0xc000082b30>: {
          s: "http: no Location header in response",
      }
      http: no Location header in response
  not to have occurred
```
/kind bug
/area tests

**Comment by kargakis** [comment]
ah, the htpasswd users are created only during `RUNNING_UNDER_TEST=true` so we cannot really run our e2e tests in a cluster that has not been deployed with that variable set.

@jim-minter @kwoodson @mjudeikis @charlesakalugwu

**Comment by kargakis** [comment]
@asalkeld

**Comment by mjudeikis** [comment]
yes. We need AAD integration fully completed to make this work. Or return htpasswd user to production cluster (which we removed for PP2)

**Comment by kargakis** [comment]
Once this issue is fixed, we should switch [periodic-ci-azure-no-running-under-test](https://github.com/openshift/release/blob/f456d5809689f12ea0a205285ece998180582e3d/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml#L314) back to 24h.
