### ISSUE TITLE
RealRP tests should use Standard_D4s sizes

### ISSUE THREAD

**Issue by thekad** [openshift/openshift-azure#855]
Tests that use the RealRP should update their templates/configs to always use Standard D4s instances at a minimum, since we only support Standard D2s through the FakeRP and only if RUNNING_UNDER_TEST.

/kind test-flake
/area tests

**Comment by kargakis** [comment]
Should be fixed by https://github.com/openshift/openshift-azure/pull/846

**Comment by thekad** [comment]
@kargakis good to know!
