### ISSUE TITLE
pollingTrackerBase#baseCheckForErrors: missing status property in Azure-AsyncOperation

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#866]
@thekad latest issue we hit in the production job

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-azure-prod-e2e/18
/area tests
/kind bug

**Comment by thekad** [comment]
ack

**Comment by jim-minter** [comment]
closing as stale
