### ISSUE TITLE
Merge fakerp.Config with TestConfig

### ISSUE THREAD

**Issue by 0xmichalis** [openshift/openshift-azure#881]
We already access parts of [fakerp.Config](https://github.com/openshift/openshift-azure/blob/4c86ccca5d32d16e44861e57d53dd09b1e7010af/pkg/fakerp/config.go#L26) via environment variables in the fake RP. It seems we can collapse the two into a single place.

TestConfig can be viewed [here](https://github.com/openshift/openshift-azure/blob/4c86ccca5d32d16e44861e57d53dd09b1e7010af/pkg/api/plugin.go#L81).

/kind cleanup

@jim-minter @mjudeikis @charlesakalugwu thoughts?

**Comment by asalkeld** [comment]
I partially agree, there seems to be 2 different things
TestConfig
AZURE stuff for auth

can we : 
- place envconfig comments directly in TestConfig?
- move the auth stuff into a separate struct (with envconfig comments) into azureclient so that we can ask for context from env?

at least no overlap

**Comment by mjudeikis** [comment]
We need to rework plugin config overall. We have a story for this in the backlog. Which includes TestConfig collapsing/rewrite.
