### ISSUE TITLE
Azure Load Balancer for ingress pointed at compute nodes (Router Configuration)

### ISSUE THREAD

**Issue by akrzos** [openshift/openshift-azure#906]
The Azure load balancer (ALB) providing ingress into the OCP router is "backended" by the compute nodes in the OCP cluster rather than the infra nodes which hosts the OpenShift Router pods.

The current configuration is potentially sub-optimal in that traffic ingresses in the following pattern:

Customer <-> ALB <-> Compute node scale set <- (traffic proxied via service) -> InfraNode <-> router pod using loadbalancer service <-> endpoint/pod

Typically the router pod is exposed via hostnetwork and the load balancer in front of it uses the infra nodes as their backend in order to ingress traffic.

The typical pattern for this traffic is:

Customer <-> LB <-> InfraNode <-> router pod using hostnetwork <-> endpoint/pod

I believe the pattern deployed crosses the SDN unnecessarily and includes additional hops and will potentially hit scalability and performance issues.

@jmencak @eparis @dak1n1 please comment to make sure I am correct

**Comment by jim-minter** [comment]
Not going to implement this:
a) changing this adds too much management overhead when multiple routers/shards are considered
b) although we don't match the 3.11 model, we do match the 4.0 model
