### ISSUE TITLE
Split fake RP server into its own process

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#912]
We need to split the fake RP into its own process to ease e2e testing and avoid statically linking our plugins into the e2e tests.

cc @jim-minter @charlesakalugwu 

@kwoodson this is going to make custom vnet testing easier

/kind cleanup
/area tests
/assign

**Comment by kargakis** [comment]
Since the server is going to be a long running process versus a goroutine in the client, we need to make it exit somehow in order for the test pod to complete successfully. I am thinking of adding an `/exit` endpoint that the template can query after it finishes deleting the cluster.

**Comment by mjudeikis** [comment]
> Since the server is going to be a long running process versus a goroutine in the client, we need to make it exit somehow in order for the test pod to complete successfully. I am thinking of adding an /exit endpoint that the template can query after it finishes deleting the cluster.

Are we planning to run Server as a process in our CI cluster, as a separate pod or something like that? What is the architecture in your head for this?

**Comment by kargakis** [comment]
> Are we planning to run Server as a process in our CI cluster, as a separate pod or something like that? What is the architecture in your head for this?

No, because this is not enabled by our CI and the fake RP pod would need to be redeployed for every PR anyway. At best this this can be its own container, for now its simpler to run it as we are already used to (as part of every hack/{action}.sh script).

**Comment by kargakis** [comment]
> because this is not enabled by our CI

Actually we should be able to use two separate pods as part of the e2e template but I am not sure we want to go there.

**Comment by mjudeikis** [comment]
I was wondering, is it worth doing something like "hosting our own fakeRP" which would be redeployed when fakeRP code changes? Like running our own Azure frontend and backend?

**Comment by kargakis** [comment]
> I was wondering, is it worth doing something like "hosting our own fakeRP" which would be redeployed when fakeRP code changes? Like running our own Azure frontend and backend?

Each test for a PR, merged commit, or periodic run would have to deploy its own fake RP. Not sure it's worth it but that's a separate discussion, enabled but orthogonal to this PR.
