### ISSUE TITLE
should deploy a template and ensure a given text is in the contents 

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-azure#919]
```
Openshift on Azure end user e2e tests [EndUser][Fake] 
  should deploy a template and ensure a given text is in the contents
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:78
STEP: instantiating the template and getting the route (2018-12-17 11:23:18.945608688 +0000 UTC m=+689.489019541)
STEP: hitting the route and checking the contents (2018-12-17 11:24:21.532497235 +0000 UTC m=+752.075908132)

• Failure [115.529 seconds]
Openshift on Azure end user e2e tests [EndUser][Fake]
/go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:29
  should deploy a template and ensure a given text is in the contents [It]
  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:78

  Expected error:
      <*errors.errorString | 0xc0000858b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /go/src/github.com/openshift/openshift-azure/test/e2e/specs/end_user.go:96
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/917/pull-ci-openshift-openshift-azure-master-e2e-azure/1429

/kind test-flake

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/917/pull-ci-openshift-openshift-azure-master-e2e-azure/1435

**Comment by kargakis** [comment]
To reduce the flakiness of this test I would suggest deploying a standalone Deployment (no Builds, no Templates) that pulls nginx from our quay registry.

**Comment by kargakis** [comment]
Another one: https://github.com/openshift/openshift-azure/pull/940#issuecomment-449049384

build failure

we should really get rid of running builds as part of the OSA merge queue.

**Comment by kargakis** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/992/pull-ci-openshift-openshift-azure-master-e2e-azure/1748

**Comment by charlesakalugwu** [comment]
another one: https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1031/pull-ci-openshift-openshift-azure-master-e2e-azure/1951/

**Comment by mjudeikis** [comment]
reopen if needed
