### ISSUE TITLE
default tuned profile on ocp masters not set to be openshift-control-plane after cluster installation

### ISSUE THREAD

**Issue by ekuric** [openshift/openshift-azure#925]
After OCP cluster setup on azure , tuned profile for masters is ``` virtual-guest ```  and first after reboot it will be switched to ```openshift-control-plane``` Necessary to ensure proper profile is active immediately after cluster setup.

**Comment by ekuric** [comment]
@jim-minter @akrzos @jeremyeder

**Comment by jim-minter** [comment]
@Makdaam ptal

**Comment by Makdaam** [comment]
@jim-minter ok
