### ISSUE TITLE
kubernetes-dynamic-pvc-* volumes are not cleaned in Azure web interface. 

### ISSUE THREAD

**Issue by ekuric** [openshift/openshift-azure#944]
"azure" storageclass is used to allocated PVC dynamically in an OCP cluster running on Azure cloud. 
After ``` oc delete pods --all --wait=false``` and ``` oc delete pvc --all --wait=false``` is executed, pods  and PVCs are removed from Openshift side ( oc view ). 
However, in azure account, there will be many PVCs ( name as kubernetes-dynamic-pvc-xxxxxx ) which still hang there after days they are deleted from OCP side. 
If selected in azure web portal particular PVC ( eg. this one is still there kubernetes-dynamic-pvc-4d0491ad-01f9-11e9-8ea6-000d3a451fc6 ) one cannot delete it as "delete" field is not clickable
I believe this is not issue with OCP, but something in azure is not cleaning storage allocated dynamically for and OCP cluster.

**Comment by ekuric** [comment]
@akrzos @jim-minter @gnufied @kargakis please comment, to me this looks like azure thing.

**Comment by mjudeikis** [comment]
This looks like azure cloud provider is not cleaning those. Is this replicable somehow manually as its worth capturing master logs to check if it doing what it suppose to be doing.

**Comment by jim-minter** [comment]
have not been able to replicate and multiple storage issues fixed since this was filed, closing but can reopen if needed
