### ISSUE TITLE
PVC not attached to applications pods 

### ISSUE THREAD

**Issue by ekuric** [openshift/openshift-azure#945]
I want to create 50 projects with 50 mongodb pods ( each project one mongodb pod ) and each pod uses dynamically allocated PVC from ```azure``` storageclass. The issue I am seeing is that PVC fails to attach to MongoDB pod. error message is [here](https://gist.github.com/ekuric/80e6ada67477247a6af4fe1ec2934e3f) 
Interesting part is 
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Warning  FailedScheduling        9m (x2 over 9m)   default-scheduler        pod has unbound PersistentVolumeClaims (repeated 100 times)
  Normal   Scheduled               9m                default-scheduler        Successfully assigned storage-test-mongo-2/mongodb-1-t2cjh to compute-000025
  Normal   SuccessfulAttachVolume  9m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-e45950ef-0431-11e9-ae29-000d3a2bb4d5"
  Warning  FailedMount             9m (x7 over 9m)   kubelet, compute-000025  MountVolume.WaitForAttach failed for volume "pvc-e45950ef-0431-11e9-ae29-000d3a2bb4d5" : Cannot find Lun for disk kubernetes-dynamic-pvc-e45950ef-0431-11e9-ae29-000d3a2bb4d5
  Warning  FailedMount             8m                kubelet, compute-000025  MountVolume.WaitForAttach failed for volume "pvc-e45950ef-0431-11e9-ae29-000d3a2bb4d5" : azureDisk - WaitForAttach failed within timeout node (compute-000025) diskId:(kubernetes-dynamic-pvc-e45950ef-0431-11e9-ae29-000d3a2bb4d5) lun:(0)
Warning FailedMount 50s (x4 over 7m) kubelet, compute-000025 Unable to mount volumes for pod "mongodb-1-t2cjh_storage-test-mongo-2(e7b53fea-0431-11e9-ae29-000d3a2bb4d5)": timeout expired waiting for volumes to attach or mount for pod "storage-test-mongo-2"/"mongodb-1-t2cjh". list of unmounted volumes=[mongodb-data]. list of unattached volumes=[mongodb-data default-token-mt84l]
```

This is on same cluster for which I reported #944

**Comment by kargakis** [comment]
Do you see this in all of the pods? How many nodes do you have?

**Comment by kargakis** [comment]
What's the output of `oc get pvc --all-namespaces`?

**Comment by ekuric** [comment]
@kargakis , I am starting pods in one project and then after they are ready proceed to other, it happens almost always for different pods which starts on different nodes.  I have 100 nodes. ping me on aos-azure if you want access to cluster, I have it for another 24h. 

``` oc get pvc --all-namespaces``` is below 

```
# oc get pvc --all-namespaces 
NAMESPACE              NAME                                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
openshift-monitoring   alertmanager-data-alertmanager-main-0   Bound     pvc-f1c1041e-f724-11e8-9656-000d3a2fbdfc   32Gi       RWO            azure          16d
openshift-monitoring   alertmanager-data-alertmanager-main-1   Bound     pvc-08852aa2-f725-11e8-9656-000d3a2fbdfc   32Gi       RWO            azure          16d
openshift-monitoring   alertmanager-data-alertmanager-main-2   Bound     pvc-3aba4dcc-f725-11e8-9656-000d3a2fbdfc   32Gi       RWO            azure          16d
openshift-monitoring   prometheus-data-prometheus-k8s-0        Bound     pvc-3dcb3b98-f724-11e8-9656-000d3a2fbdfc   128Gi      RWO            azure          16d
openshift-monitoring   prometheus-data-prometheus-k8s-1        Bound     pvc-9e70a77c-f724-11e8-9656-000d3a2fbdfc   128Gi      RWO            azure          16d
```

**Comment by kargakis** [comment]
> Q: does OpenShift scheduler bear in mind the maximum number of data disks that can be attached to a node?

Isn't this an azure-specific limitation? I doubt there is cloud-specific code in the scheduler.

**Comment by jim-minter** [comment]
> > Q: does OpenShift scheduler bear in mind the maximum number of data disks that can be attached to a node?

> Isn't this an azure-specific limitation? I doubt there is cloud-specific code in the scheduler.

If the kubelet AttachVolumeLimit feature (alpha in 1.11) is enabled, the kubelet posts info about how many data disks it can handle to the Node object, which the scheduler then takes into account via the MaxAzureDiskVolumeCount predicate (which I believe is enabled by default).  This is implemented in the cloud provider.

**Comment by jim-minter** [comment]
AttachVolumeLimit added in #1046

**Comment by jim-minter** [comment]
Note: in 3.11 on Azure, AttachVolumeLimit hard codes the maximum number of data disks to 16 regardless of the instance size.  This is implemented properly in k8s 1.12.

**Comment by jim-minter** [comment]
https://github.com/kubernetes/kubernetes/pull/67772

**Comment by jim-minter** [comment]
multiple similar storage issues have been resolved since this was filed, closing
