### ISSUE TITLE
profile system container

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#956]
For the system container, we need to know how they behave, so we could set appropriate QoS limits., 
We want to make pods guaranteed and system-critical so they would not get terminated. But for this we need to know what values we need to set. In example:
https://github.com/openshift/openshift-azure/issues/934

This need to be done after we get access to Geneva to get proper visibility into our all clusters (perf cluster including)

/kind feature

**Comment by jim-minter** [comment]
closing for #347
