### ISSUE TITLE
split template deployment  test

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#957]
We want to split test to smaller tests so flakes could be identified. 
```
Openshift on Azure end user e2e tests [EndUser][Fake]
 should deploy a template with persistent storage and test failure modes
```
In the example this one would land as:
* build test
* deployment test 
* deployment with PVC
* deployment with Database to check networking
* template deployment to check template service broker

/kind feature

**Comment by kargakis** [comment]
Not sure the deployment test is needed. I would do a
* build test to test builds+registry
* statefulset test that uses exec to test storage
* nginx deployment to test routes

Also, how does the conformance suite fit into the picture? If we cannot get coverage from running it then what's its point?

**Comment by thekad** [comment]
There is two template tests:
* "should deploy a template and ensure a given text is in the contents" which deploys an nginx and makes a request to the router. I think this one can stay (I haven't seen many/any issues with this spec, fairly simple)
* "should deploy a template with persistent storage and test failure modes" is the one that I feel needs to be broken down

The last point in @kargakis' bullets would still be part of the first test, I think.

**Comment by kargakis** [comment]
>     * (I haven't seen many/any issues with this spec, fairly simple

I have seen a couple of them; some are tracked in https://github.com/openshift/openshift-azure/issues/919 but most people just /retest w/o linking the flake back to the issue so it's difficult to discover them. There isn't much difference in most of the failure modes between the two tests.

**Comment by thekad** [comment]
So the idea is then get rid of both template specs? I see value in testing the template instantiation mechanism, and there's hardly a simpler template than the nginx one.

**Comment by mjudeikis** [comment]
didnt saw the underlying issue for a while. Closing this as we have other priorities :)
